### PR TITLE
feat : log files loaded from glob patterns

### PR DESCRIPTION
**Pull request by aktraore**
This new feature logs the files that are loaded using the glob patterns to aid in debugging.

Closes: #4162

### CODE REVIEW

**Comment by vlapo** [comment]
@aktraore could you please do not format code you not change. It is hard to say what is change and what is only formatting. It help us get a quick review :)

**Comment by aktraore** [comment]
😓 damn it, it was done automatically by my editor. Do you want me to recommit without those changes ? I didn't notice it, really sorry.

**Comment by vlapo** [comment]
Do not be sorry. It is common issue. You will know next time ;-) Sure add commit without formatting issues in your branch.

**Comment by aktraore** [comment]
I forced pushed without the formatting, it should be good now

**Pull request merged**
