### PR TITLE
Fix README.md active-record-data-map link missing issue

### PR DESCRIPTION
**Pull request by calebx**

### CODE REVIEW

**Comment by pleerock** [comment]
thank you!

**Comment by jayarjo** [comment]
@calebx @pleerock this PR didn't fix the problem, did it? I think it's a problem in parser (that thing that converts md to the documentation on the site) - it fails to parse # properly.

I already mentioned it in a related PR as well: https://github.com/typeorm/typeorm/pull/4801#issuecomment-544487350

**Comment by calebx** [comment]
@jayarjo it works good on current master branch, for the first two link in README.
is it what we expected?
while I still saw two bad link, maybe more. I will pick it up.

**Comment by jayarjo** [comment]
@calebx I don't think it does. Check the raw MD and then what it is being converted to.

**Comment by calebx** [comment]
@jayarjo 
oh. I see. the ```./docs``` will convert to ```#```
sorry did not see the covert logic in behind for website.

now it would work.
https://github.com/typeorm/typeorm/pull/5065

@pleerock

**Pull request merged**
