### PR TITLE
fixes #8747

### LINKED ISSUE #8747: QueryBuilder update handles Date objects wrong on a `ManyToOne` relation ship.
## Issue Description
When updating a foreign key that uses a Date object, TypeORM seems to ignore the Date object.

### Expected Behavior
Correctly handling the `Date` object

### Actual Behavior
Some internal code is handling the Date object wrong.

### Steps to Reproduce

```typescript
@Entity()
export class Car extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
    uuid: string

  @Column({ type: 'timestamp', precision: 3, nullable: true })
    latestRecordTimestamp?: Date

  @OneToMany(() => Record, record => record.car)
    records: Record[]

  @ManyToOne(() => Record)
  @JoinColumn([
    { name: 'uuid', referencedColumnName: 'carUuid' },
    { name: 'latestRecordTimestamp', referencedColumnName: 'timestamp' }
  ])
    latestRecord?: Record
}
```

```typescript
@Entity()
export class Record extends BaseEntity {
  @CreateDateColumn({ precision: 3, primary: true })
    timestamp: Date

  @Column({ type: 'uuid', primary: true })
    carUuid: string

  @ManyToOne(() => Car, car => car.records, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'carUuid' })
    car: Car
}
```

```typescript
await getManager().createQueryBuilder()
  .update(Car)
  .set({ latestRecordTimestamp: record.timestamp })
  .where('uuid = :uuid', { uuid: car.uuid })
  .execute()
```

### Temporary Workaround

```typescript
await getManager().createQueryBuilder()
  .update(Car)
  .set({ latestRecordTimestamp: record.timestamp.toISOString() })
  .where('uuid = :uuid', { uuid: car.uuid })
  .execute()
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   MacOS 12.1       |
| Node.js version     | v16.13.0 | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.2.45  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by jorenvandeweyer**
### Description of change
Fixes #8747 

Handles the Date object correctly.

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [X] This pull request links relevant issues as `Fixes #0000`
- [X] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change (NA)
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
can you please fix the conflicts and add the test case so we won't have this issue in the future again? thanks.

**Comment by jorenvandeweyer** [comment]
I agree a test case should be added, I think it would be better in a different issue/pr. Testing this would require a good timeseries database setup imo.

@pleerock if you agree I'll create a new issue and create a separate pull request. This way we can already merge/close this one.

**Comment by pleerock** [comment]
why not to make it here? I need test to check what exactly this change does and what error we have without this change.

**Comment by jorenvandeweyer** [comment]
@pleerock I added a test covering the issue.

**Comment by pleerock** [comment]
tests are failing

**Comment by pleerock** [comment]
yes I'll do it once I get the time to checkout your branch and do manual testing

**Comment by pleerock** [comment]
looks like it breaks because of `precision: 3`. Maybe mysql doesn't play well with this value. Do you really need precision in this test?

**Comment by pleerock** [comment]
after removing `precision` I found another problem - mysql tests would not be able to pass because you rely on primary column not explicitly set in your code, instead it set by database's `DEFAULT` (since you are using CreateDateColumn). After TypeORM saves your entity it needs entity id-s to perform mapping operations, it doesn't work if it doesn't have entity ids. So, this scenario is not supported. It works in postgres because it supports `RETURNING` statement which is not supported by mysql and some other drivers.

So, again my question is regarding to your test - why did you use **primary** `CreateDateColumn` ? Is it required in order to fix what you are trying to fix?

**Comment by jorenvandeweyer** [comment]
> looks like it breaks because of `precision: 3`. Maybe mysql doesn't play well with this value. Do you really need precision in this test?

Not sure if it is needed in mysql but it is needed in PostgreSQL. JavaScript timestamps only have a precision of 3 decimals on a second, postgres has 6 by default. So it would be impossible to set the foreign key of the relationship since the timestamps would differ. 

>after removing precision I found another problem - mysql tests would not be able to pass because you rely on primary column not explicitly set in your code, instead it set by database's DEFAULT (since you are using CreateDateColumn). After TypeORM saves your entity it needs entity id-s to perform mapping operations, it doesn't work if it doesn't have entity ids. So, this scenario is not supported. It works in postgres because it supports RETURNING statement which is not supported by mysql and some other drivers.

Thank you! I totally forgot about that. I rewrote the test case, instead of using DEFAULT I used `new Date()` in the code instead.

>So, again my question is regarding to your test - why did you use primary CreateDateColumn ? Is it required in order to fix what you are trying to fix?

CreateDateColumn is not required for the test, the composite primary key only requires a timestamp. I removed the createDateColumn in the latest commit. 

Now it's working for both postgres & mysql.

**Comment by pleerock** [comment]
That's why I ask to keep tests as simple as possible and contain the only code test need. As you can see both of us waste lot of time.

**Comment by AlexMesser** [comment]
thank you for contribution!

**Pull request merged**
