### PR TITLE
feat: MySQL table support comment

### PR DESCRIPTION
**Pull request by sinkhaha**
### Description of change
MySQL table support comment
Fixes https://github.com/typeorm/typeorm/issues/9991

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
Why do you have package-lock file changed?

There is a problem with your implementation - sync doesn't work such way. If you put comment to entity - it will be stored in the database. If you change comment on the same entity later on - it won't sync the changes.

We need implementation to be full-fledged before we can merge the changes.

**Comment by sinkhaha** [comment]
> Why do you have package-lock file changed?
> 
> There is a problem with your implementation - sync doesn't work such way. If you put comment to entity - it will be stored in the database. If you change comment on the same entity later on - it won't sync the changes.
> 
> We need implementation to be full-fledged before we can merge the changes.

**Comment by pleerock** [comment]
@sinkhaha let's say you put comment to entity. Comment now is in database for your table. Now change comment in the entity. Syncer must "catch up" this change and update the table comment in the database. 

Synchronization is made by `dataSource.synchronize()` method.

To understand how it works, play around with let's say columns -> add column, remove column from your entity -> database table will be updated.

To understand how it works from the code perspective - you have to learn how `QueryRunner` (mysql one in your case) work.

**Comment by sinkhaha** [comment]
@pleerock I have made some changes. Please review it again when you have time.

**Comment by yuntian001** [comment]
ci/circleci: build — Your tests failed on CircleCI

Whether you have time to fix

**Comment by sinkhaha** [comment]
@yuntian001 This doesn't seem to be an error caused by my changes. Is it okay to rebuild it? I don't have permission to trigger.

**Comment by sinkhaha** [comment]
@pleerock Please review it again when you have time, thanks

**Review by hinogi — APPROVED** [review]
LGTM

**Comment by sinkhaha** [comment]
Could you help review and handle this PR... If you have time. It's been quite a while, thanks @AlexMesser

**Pull request merged**
