### PR TITLE
Fixing table name comparison in migration process (#1)

### PR DESCRIPTION
**Pull request by sassanh**

### CODE REVIEW

**Comment by sassanh** [comment]
https://github.com/typeorm/typeorm/issues/3951

**Comment by Kononnable** [comment]
Tests are failing.

**Comment by pleerock** [comment]
note my comment in #3951

**Comment by Kononnable** [comment]
Closing as author is no longer interested in the problem and PR isn't completed.
https://github.com/typeorm/typeorm/issues/3951#issuecomment-485251254

**Pull request closed without merging**
