### PR TITLE
fix: add support for mongodb driver v4

### LINKED ISSUE #7907: Add support for mongodb driver v4
## Issue Description
Exactly in [this commit](https://github.com/mongodb/node-mongodb-native/commit/a2d78b22b28ae649fa2c4e28294a3a03c446373e#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L2) mongodb stopped exporting a Cursor object. 

Because of that, every reference to `ParentCursor.Prototype` in `MongoEntityManager ` ([like here](https://github.com/typeorm/typeorm/blob/master/src/entity-manager/MongoEntityManager.ts#L691)) is failing with error "Cannot read property 'prototype' of undefined".

### Expected Behavior
No error expected.

### Actual Behavior
Error "Cannot read property 'prototype' of undefined"

```
TypeError: Cannot read property 'prototype' of undefined
    at FindCursor.cursor.toArray (/entity-manager/MongoEntityManager.ts:679:37)
    at MongoEntityManager.<anonymous> (/entity-manager/MongoEntityManager.ts:97:23)
    at step (/node_modules/tslib/tslib.js:143:27)
    at Object.next (/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Steps to Reproduce

1. Add typeorm dependency
2. Add mongodb v4 dependency.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubuntu 18.04 on wsl2  |
| Node.js version     | v14.17.0 | 
| Typescript version  | v4.0.8 | 
| TypeORM version     | v0.2.34 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [x] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by MatheusMeloAntiquera**
This new fix allow support to mongodb driver v4

Closes: #7907

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [ ] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #7907`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by imnotjames** [comment]
This will break typeorm for those without MongoDB installed.

**Comment by imnotjames** [comment]
This seems to cause tests to fail.  Are you still working through this?

**Comment by MatheusMeloAntiquera** [comment]
> This seems to cause tests to fail. Are you still working through this?

Yes, I am, I will try to fix in this weekend

**Comment by pleerock** [comment]
Closing until this is finished.

**Pull request closed without merging**
