### PR TITLE
fix: resolve issues with quoting column names in groupBy and orderBy

### LINKED ISSUE #9293: No quotes while using orderBy, groupBy by custom column
## Issue Description

I am using Postgres and it is required to use quotes in the queries to wrap tables and columns.
In case when query builder wraps the query as a subquery into the SELECT DISTINCT request, it doesn't add quotes around the custom column added by addSelect.

### Expected Behavior
Typeorm wraps anything was added by addSelect into quotes.

```sql
SELECT DISTINCT "distinctAlias"."Offer_id" AS "ids_Offer_id", "distinctAlias"."rateSum"
FROM (SELECT "Offer"."id"       AS "Offer_id",
             "Offer"."lenderId" AS "Offer_lenderId",
             "Offer"."rate"     AS "Offer_rate",
             "Lender"."id"      AS "Lender_id",
             "Lender"."name"    AS "Lender_name",
             "Lender"."email"   AS "Lender_email",
             1                  AS "rateSum"
      FROM "Offer" "Offer"
               INNER JOIN "Lender" "Lender" ON "Lender"."id" = "Offer"."lenderId"
      GROUP BY "Offer"."id") "distinctAlias"
ORDER BY "distinctAlias".rateSum ASC, "Offer_id" ASC
OFFSET 10
```
"distinctAlias".rateSum should be quoted: "distinctAlias"."rateSum"

### Actual Behavior
Typeorm doesn't wrap column added by addSelect into quotes.
```sql
SELECT DISTINCT "distinctAlias"."Offer_id" AS "ids_Offer_id", "distinctAlias".rateSum
FROM (SELECT "Offer"."id"       AS "Offer_id",
             "Offer"."lenderId" AS "Offer_lenderId",
             "Offer"."rate"     AS "Offer_rate",
             "Lender"."id"      AS "Lender_id",
             "Lender"."name"    AS "Lender_name",
             "Lender"."email"   AS "Lender_email",
             1                  AS "rateSum"
      FROM "Offer" "Offer"
               INNER JOIN "Lender" "Lender" ON "Lender"."id" = "Offer"."lenderId"
      GROUP BY "Offer"."id") "distinctAlias"
ORDER BY "distinctAlias".rateSum ASC, "Offer_id" ASC
OFFSET 10
```
"distinctAlias".rateSum is not qouted

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. clone https://github.com/redwert/typeorm-postgres-example.git
2. npm i
3. docker-compose up -d
4. npm run start

or take a look here:

```typescript
@Entity('Offer')
export default class Offer {
  @PrimaryGeneratedColumn('increment')
  id: number

  @Column('int')
  lenderId: number

  @Column('int')
  rate: number

  @ManyToOne(() => Lender, lender => lender.offers)
  @JoinColumn([ { name: 'lenderId', referencedColumnName: 'id' } ])
  lender: Lender
}

@Entity('Lender')
export default class Lender {
  @PrimaryGeneratedColumn('increment')
  id: number

  @Column('varchar')
  name: string

  @Column('varchar')
  email: string | null

  @OneToMany(() => Offer, offer => offer.lender)
  offers: Offer[]
}

(async () => {
    const conn = await createConnection(typeOrmConfig)
    const rateSumAlias = 'rateSum'

    await conn.getRepository(Offer)
      .createQueryBuilder('Offer')
      .addSelect('1', rateSumAlias)
      .innerJoinAndSelect('Offer.lender', 'Lender')
      .groupBy('Offer.id')
      .orderBy(rateSumAlias, 'ASC')
      .skip(10)
      .getRawAndEntities()
    
    await conn.close()
})();
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  Ubunut 20.04   |
| Node.js version     | 16.16.0  | 
| Typescript version  | 4.7.4  | 
| TypeORM version     | 0.3.7  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by redwert**
### Description of change

Closes: #9293

Fix wrapping custom column into quotes in `orderBy` and `groupBy` statements.
Without this fix, PostgreSQL throws an error in the case of `addSelect` by the custom field.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #9293`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
what if we want to group / order by something that is not an alias? (e.g. `ORDER BY 1`)

**Comment by redwert** [comment]
@pleerock 
Added changes to handle cases (e.g. ORDER BY 1)
Also, having build error, but I don't understand why and what should I fix

**Comment by pleerock** [comment]
Code become weird after your changes. It definitely needs better implementation. 

But I don't think we should add this feature, simply because it's too hard to cover all cases. For example take a look what different expressions ["group by"](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver16) can accept. Also, if we add this feature to order by and group by - we will need to cover all other statements, e.g. SELECT which is too way complicated to cover.

Current behavior is the best tradeoff - it automatically escapes symbols of the aliases you use with the columns registered in the entities, for everything else user do manual escaping. This way we achieve both escaping of 95% use cases + flexibility in edge use cases.

**Comment by redwert** [comment]
@pleerock I agree about groupBy and orderBy cases. Right now it works with the quoted column name e.g. `.addGroupBy(`"${aliasName}"`)`.
But this way it is needed to allow the ability to pass quoted column name to addSelect this way typeorm behaviour will be consistent.
In the example, we have the simple query with addSelect, addGroupBy, addOrderBy with the same alias.
```
const alias = 'rateSum'

repository
   .createQueryBuilder("Offer")
   .addSelect("1", alias)
   .innerJoinAndSelect("Offer.lender", "Lender")
   .groupBy("Offer.id")
   .addGroupBy("Lender.id")
   .addGroupBy(alias)
   .orderBy("Lender.id", "ASC")
   .addOrderBy("Offer.id", "ASC")
   .addOrderBy(alias, "ASC")
   .skip(1)
   .take(10)
   .getRawAndEntities()
```
And these are the outputs for different cases:

- without quoting aliases everywhere we have the next
image

- passing quoted alias in groupBy and orderBy (no "distinctAlias".rateSum in SELECT DISTINCT in query)
image

- passing quoted alias everywhere (addSelect, groupBy, orderBy)
image

As result in every scenario we have the wrong queries. In my understanding it can be two variants: 
- quoting the alias for orderBy and groupBy if an alias was not quoted (this is implemented right now)
- add the ability to pass quoted alias to addSelect (fix issue with `"" rateSum""` in SELECT)

So what would you suggest? I am ready to spend my time and close this bug but I need your assistance

**Comment by pleerock** [comment]
`addSelect` second parameter is `alias`, so we already know that we are dealing with `alias`, that's why we automatically escape it. With order by / group by it's a bit more complicated since it's parameter is actual an expression, so manual escaping is required. That's explains why you have such results.

Regarding to how to handle the issue this PR addresses, see my [previous answer](https://github.com/typeorm/typeorm/pull/9307#issuecomment-1227218253).

**Comment by redwert** [comment]
Umed, current behavior doesn't give an ability to add a custom column and make an order by it. There is no option to do it.

Please take a look on the last changes. It gives ability to pass escaped aliases to addSelect and solves this issue:
image

This doesn't break anything, and fixes issue with wrong query

**Comment by pleerock** [comment]
okay... so now your changes are applied to addSelect...

Let me confirm one thing:

> current behavior doesn't give an ability to add a custom column and make an order by it. There is no option to do it.

what if you do:

```ts
.createQueryBuilder("Offer")
            .addSelect(`1 as "rateSum"`)
            .innerJoinAndSelect("Offer.lender", "Lender")
            .groupBy("Offer.id")
            .addGroupBy("Lender.id")
            .addGroupBy(`"rateSum"`)
            .orderBy("Lender.id", "ASC")
            .addOrderBy("Offer.id", "ASC")
            .addOrderBy(`"rateSum"`, "ASC")
```

are you **sure** it's not going to work?

**Comment by redwert** [comment]
I have tried your variant with `.addSelect(`1 as "rateSum"`)` and `.addOrderBy(`"rateSum"`, "ASC")` but it also doesn't work.  There is no "distinctAlias"."rateSum" after the coma.
image

**Pull request closed without merging**
