### PR TITLE
fix bug when dropping column with index (fix #790)

### LINKED ISSUE #790: [Postgres] Fatal error during schema sync
I had an entity with the following column:

```ts
@Column()
@Index()
foo: string
```

I then deleted that column and replaced it with:

```ts
@ManyToOne(() => Foo, foo => foo.bars)
foo: Foo
```

Now I'm seeing this error on startup (using 0.1.0-alpha.35):

```
0|index    | dropping an index: ind_8531cdf4c5900186c2a8a5cea4
0|index    | executing query: DROP INDEX "ind_8531cdf4c5900186c2a8a5cea4"
0|index    | query failed: DROP INDEX "ind_8531cdf4c5900186c2a8a5cea4"
0|index    | error: { error: index "ind_8531cdf4c5900186c2a8a5cea4" does not exist
0|index    |     at Connection.parseE (/Users/bcherny/Sites/mousepig/server/node_modules/pg/lib/connection.js:546:11)
0|index    |     at Connection.parseMessage (/Users/bcherny/Sites/mousepig/server/node_modules/pg/lib/connection.js:371:19)
0|index    |     at Socket.<anonymous> (/Users/bcherny/Sites/mousepig/server/node_modules/pg/lib/connection.js:114:22)
0|index    |     at emitOne (events.js:115:13)
0|index    |     at Socket.emit (events.js:210:7)
0|index    |     at addChunk (_stream_readable.js:252:12)
0|index    |     at readableAddChunk (_stream_readable.js:239:11)
0|index    |     at Socket.Readable.push (_stream_readable.js:197:10)
0|index    |     at TCP.onread (net.js:589:20)
0|index    |   name: 'error',
0|index    |   length: 124,
0|index    |   severity: 'ERROR',
0|index    |   code: '42704',
0|index    |   detail: undefined,
0|index    |   hint: undefined,
0|index    |   position: undefined,
0|index    |   internalPosition: undefined,
0|index    |   internalQuery: undefined,
0|index    |   where: undefined,
0|index    |   schema: undefined,
0|index    |   table: undefined,
0|index    |   column: undefined,
0|index    |   dataType: undefined,
0|index    |   constraint: undefined,
0|index    |   file: 'tablecmds.c',
0|index    |   line: '762',
0|index    |   routine: 'DropErrorMsgNonExistent' }
0|index    | executing query: ROLLBACK
0|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|index    | Error: Error connecting to Postgres: QueryFailedError: index "ind_8531cdf4c5900186c2a8a5cea4" does not exist
0|index    |     at /Users/bcherny/Sites/mousepig/server/dist/server/src/App.js:75:32
0|index    |     at Generator.throw (<anonymous>)
0|index    |     at rejected (/Users/bcherny/Sites/mousepig/server/dist/server/src/App.js:5:65)
0|index    |     at <anonymous>
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:208:7)

```

### PR DESCRIPTION
**Pull request by bcherny**
See #790

### CODE REVIEW

**Comment by pleerock** [comment]
Im not sure if its a correct fix. It drops index because there is a `indexSchema` for this index. `indexSchema` is representation of this index in the database. If there is no index in the database then such "indexSchema" should not exist and it won't lead to these lines and execute this code. To find correct fix you first need to figure out why there is index schema which does not exist in the database.

Wait... Do I understood it correctly - column was removed but index schema left? If yes, then on column remove we shall remove index schema too. And it won't execute these lines anymore. But you need to check if its a correct behaviour on all platforms (all platforms remove index automatically when column is removed? Also what about composite indices, you need to check that as well.

**Comment by bcherny** [comment]
@pleerock Thanks for the feedback. Unfortunately I am focused on building my product now, and do not have time to diagnose and fix the issue in TypeORM now. I just wanted to surface the bug to you and show you the fix that unblocked my specific use case. I am using my fork of TypeORM until you or another maintainer have time to merge a fix.

**Comment by pleerock** [comment]
Okay, I understood you

**Comment by pleerock** [comment]
@iz-iznogood BTW one another issue related to indices 😇

**Pull request closed without merging**
