### PR TITLE
add tslib

### PR DESCRIPTION
**Pull request by webleaf**
#3457

### CODE REVIEW

**Comment by pleerock** [comment]
but users will have to install it as well, right? e.g. they must do `importHelpers: true` and install tslib in their projects manually, right?

**Comment by webleaf** [comment]
@pleerock Nope.
`importHelpers: true` is ts compiler option. So it works only when you make `typeorm` build. `typeorm` npm package contains only `*.js`, `.d.ts` files and `package.json` which should contain `tslib` dependency.
I add it as dependency to package.json (if `package.json` which I change will be lie in builded `typeorm` npm package).
So it works as all npm-packages works. When user install typeorm via `npm install typeorm` it wiil be automatically dowloaded to one of two places:
- `userProject/node_modules/typeorm/node_modules/tslib`
- `userProject/node_modules/tslib`

To which place it will be automatically placed depends on `tslib` version of user project.
Or if user project have not `tslib` it will be just placed to `userProject/node_modules/typeorm/node_modules/tslib`
For example this screenshot of my `node_modules` dir tree (as you can see there are `typeorm/node_modules` dir with `debug` and `ms` dirs which I don't install manually):

**Comment by pleerock** [comment]
ah okay it only adds `var tslib_1 = require("tslib")`, for some reason I was always thinking it requires a globally included shim-like library.

**Comment by pleerock** [comment]
The only concern I have if mobile-based builds will continue to work.

**Comment by webleaf** [comment]
@pleerock first of all, this feature is important for mobile-based and browser-based builds (reduce package size). I use nativescript, that's why I do this. In the coming hours I will check it one more time and let you know.

**Comment by webleaf** [comment]
@pleerock works like a charm. Tested with [nativescript-vue-typeorm-sample](https://github.com/typeorm/nativescript-vue-typeorm-sample)

**Comment by pleerock** [comment]
Okay lets try to merge it and see how it works for users.

**Comment by vlapo** [comment]
Fixed https://github.com/typeorm/typeorm/issues/3457

**Pull request merged**
