### PR TITLE
add support for UUID column type in PostgreSQL (#271)

### PR DESCRIPTION
**Pull request by MaikelH**
Support for UUID columns in PostgreSQL (see #271)

### CODE REVIEW

**Comment by pleerock** [comment]
thank you! Will be released in next typeorm version. Let me know if you need this release urgently.

**Comment by MaikelH** [comment]
For us currently the sooner would be better. We use use UUID's extensively in our application.

**Comment by pleerock** [comment]
Released in `0.0.9-alpha.3`

**Comment by pleerock** [comment]
yes should be so, also covered by #284

**Pull request merged**
