### PR TITLE
chore(changelog): 0.2.12 changelog + add Unreleased section

### PR DESCRIPTION
**Pull request by vlapo**
- 0.2.12 changelog 
 - I think all PR and changes (or most of them) should include changelog record. So I added **Unreleased** section and added note to the contributing guide

### CODE REVIEW

**Comment by pleerock** [comment]
Thank you!!!!

**Comment by pleerock** [comment]
> I think all PR and changes (or most of them) should include changelog record.

yeah we need to do it. We should also consider automation as you suggested before.

**Comment by rustamwin** [comment]
I've variant too

0.2.13 under development <- when released should change to date

* [change type e.g Bug] [link to issue or issue num] - [description] (username)

**Comment by vlapo** [comment]
Yeah I would love to use automation in future too. I will check some open source github repositories and find some simple way. I love format like angular:
```
```

**Pull request merged**
