### PR TITLE
Mongo driver 3x

### PR DESCRIPTION
**Pull request by pablocarreraest**
#1449 working PR with the changes I made.

### CODE REVIEW

**Comment by pleerock** [comment]
Thank you very much for your contribution! Tests are failing, can you please take a look?

**Comment by pablocarreraest** [comment]
Sure in this day's I will work on this... for beginning I will make a check list for thing I have to change in here:
- [X] Update package.
- [ ] API Changes: 

  - Removed the following API methods.

    - Db.prototype.authenticate
    - Db.prototype.logout
    - Db.prototype.open
    - Db.prototype.db
    - Db.prototype.close
    - Admin.prototype.authenticate
    - Admin.prototype.logout
    - Admin.prototype.profilingLevel
    - Admin.prototype.setProfilingLevel
    - Admin.prototype.profilingInfo
    - Cursor.prototype.nextObject

  - Added the following API methods.

    - MongoClient.prototype.logout
    - MongoClient.prototype.isConnected
    - MongoClient.prototype.db
    - MongoClient.prototype.close
    - MongoClient.prototype.connect
    - Db.prototype.profilingLevel
    - Db.prototype.setProfilingLevel
    - Db.prototype.profilingInfo

- [ ] The legacy construct
- [ ] The legacy operation
- [ ] Connection String
- [ ] BulkWriteResult & BulkWriteError
- [ ] mapReduce inlined results
- [ ] Find
- [ ] Collection.prototype.aggregate
- [ ] updateOne & updateMany
- [ ] keepAlive
- [ ] insertMany
- [ ] geoNear command helper

**Comment by EricRabil** [comment]
Could there be a warning posted somewhere on the project as Mongo 3x on TypeORM is broken until this is resolved?

**Comment by zender** [comment]
Any progress on that issue?

**Comment by pleerock** [comment]
Upgraded mongodb support to latest 3.0.0 version in latest `next`. Test it via `npm i typeorm@next` and please let know if you have any issues.

**Comment by jonathan-casarrubias** [comment]
dude this patch works, I'm so lucky since I just found the issue... No need to wait lol.

Cheers
Jon

**Comment by anyx** [comment]
I see couple issues. 
MongoRepository.save returns object with `id` and `_id` properites for entity with mapping:

```

@Entity()
@DtoResponse(VacancyDto)
export class Vacancy {
    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    user: ObjectID;

    @Column({ length: 255 })
    title: string;

    @Column()
    description: string;

    @Column()
    enabled: boolean;

    @Column()
    @CreateDateColumn()
    createdAt: Date;

    @Column()
    @UpdateDateColumn()
    updatedAt: Date;

    constructor(user: ObjectID, title: string, description: string) {
        this.user = user;
        this.title = title;
        this.description = description;
        this.enabled = true;
    }
}
```

And dates columns are not generating anymore (#1843)

**Comment by ruscon** [comment]
The same problem as @anyx

**Comment by pleerock** [comment]
@jonathan-casarrubias Im sorry about your experience, you may checkout test codebase (there is a travis ci badge), its quite solid, however mongodb is a specific database and it has much less coverage then other rdbms databases. Mongodb is mostly community-driven database in TypeORM and I expect community to contribute in this area, so feel free to contribute!

**Comment by tobydeh** [comment]
Any news on CreateDateColumn / UpdateDateColumn?

You should mention on your website that mongo support is experimental. I decided to use typeorm thinking mongo had full functionality and now I'm running into issues :(

**Comment by ruscon** [comment]
@tobydeh 

quick solution
```
 @BeforeInsert()
    beforeInsert() {
        const now = new Date();
        this.createdAt = now;
        this.updatedAt = now;
    }
```

**Comment by tobydeh** [comment]
Yeah but I wont be able to sleep at night. Also the @Column default values aren't working.

**Comment by pleerock** [comment]
@column default is SQL's `DEFAULT`, there is no such thing in mongodb. If you want to set a default property you simply initialize a class property.

**Comment by anyx** [comment]
Here my attempt to return support `@CreateDateColumn` and `@UpdateDateColumn` decorators
https://github.com/typeorm/typeorm/pull/3335

**Pull request closed without merging**
