### PR TITLE
SQLite Drivers abstraction + PlatformTools chalk integration

### PR DESCRIPTION
**Pull request by daniel-lang**
This is an attempt at having one base sqlite driver that cordova, sqlite (node) and websql extend. I hope this is what you had in mind.
Unfortunately I added something else that was supposed to go in a PR of its own. It is another attempt to fix the compiler error that are caused by my chalk mock in the BrowserPlatformTools file by moving the calls to chalk into the PlatformTools class. Let me know if you like that approach and whether or not you are happy to have it in this PR.

### CODE REVIEW

**Comment by pleerock** [comment]
This is too bulky to review, so I'll merge it by trust, you checked everything, right?

**Comment by pleerock** [comment]
Also is it optimized to make it to work with sqljs as well?

**Comment by daniel-lang** [comment]
Don't merge it yet, i'm removing the chalk thing and I tested cordova and websql not node!

**Comment by daniel-lang** [comment]
This turned into a mess. I will open a new PR

**Pull request closed without merging**
