### PR TITLE
feat: add multi-dimensional cube support for PostgreSQL

### LINKED ISSUE #3577: Add support to cube on posgres
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Add support for the cube type with postgres. https://www.postgresql.org/docs/10/cube.html

### PR DESCRIPTION
**Pull request by liaujianjie**
Implements support for the [`cube`](https://www.postgresql.org/docs/10/cube.html) type on PostgreSQL.

Closes #3577.

### CODE REVIEW

**Comment by liaujianjie** [comment]
Thanks for taking the time to look @vlapo!

Is there anywhere else I should add docs? I'm not sure if this feature warrants its own section like spatial columns.

**Comment by vlapo** [comment]
I think this is only place where we need mention it. Thank you for contribute.

**Comment by ricardovf** [comment]
Is this commit reverted, why? If not, in which version of TypeORM is it?

https://github.com/neverson-silva/typeorm/commit/81dfbdbb4851941c509e602dfee816e089ff0907

**Comment by liaujianjie** [comment]
@ricardovf Looks like it was reverted in @neverson-silva's own fork of TypeORM. The features are still in this codebase.

**Comment by ricardovf** [comment]
It's not on the 0.2.18 release (https://github.com/typeorm/typeorm/blob/0.2.18/src/driver/postgres/PostgresDriver.ts). Do you know if in the next release it will be merged?

**Comment by neverson-silva** [comment]
> @ricardovf Looks like it was reverted in @neverson-silva's own fork of TypeORM. The features are still in this codebase.

@liaujianjie and @ricardovf it wasn't reverted in my fork. In my fork only has 2 commits of mine. My fork was created from the master branch on 14 Jul. 

https://github.com/typeorm/typeorm/pull/4435

**Comment by liaujianjie** [comment]
@neverson-silva My bad, made a mistake there.

@ricardovf I'm not a core maintainer so I wouldn't know.

**Comment by ricardovf** [comment]
Anyone form TypeORM can check this? Thanks!

**Comment by ricardovf** [comment]
Thanks! haggholm

**Pull request merged**
