### PR TITLE
Update issue template brackets to checkboxes

### PR DESCRIPTION
**Pull request by maximelafarie**
It's more user-friendly and easier to check/uncheck if issue editing is needed.

Moreover, it's displayed as an unordered list, which is what we want for choices list. 🤓

🖖

### CODE REVIEW

**Comment by pleerock** [comment]
nooo, sorry, we had this PR so many times, but if we merge it, created issues will have list of "tasks" and github treat them like "2 of 10" items. It's not whats desired. Thank you.

**Comment by maximelafarie** [comment]
Ooops, sorry for this!

**Comment by pleerock** [comment]
FYI

Screenshot 2020-03-11 18 05 32

**Comment by maximelafarie** [comment]
im gonna edit it

I'll edit

**Pull request closed without merging**
