### PR TITLE
Fix the quirk bug that the buffer compare function is not working.

### PR DESCRIPTION
**Pull request by sevenryze**
The buffer compare function shows a quirk bug, see the picture i captured below:

annotation 2019-02-17 123514

The function instanceof Function check failed and we need to add more checks.

BWT. How many frequency we publish a new version? which including bug fix version. 
I think the predictable frequency is very help for more contributing and more robust for formal application.

### CODE REVIEW

**Comment by sevenryze** [comment]
Any update on this PR? @pleerock Please review 😄

**Comment by pleerock** [comment]
Thank you!

Strange that instance of Function doesn't work...

**Comment by pleerock** [comment]
> BWT. How many frequency we publish a new version? which including bug fix version.
I think the predictable frequency is very help for more contributing and more robust for formal application.

I would like to avoid fixed schedule on version publishing to be flexible. I usually release a new version if:

* I feel there is enough changes to make a new release
* there is some critical/important change
* somebody ask to release

**Comment by sevenryze** [comment]
Fine, got your points and thanks for your review.

Will this fix be included in next release?

**Comment by pleerock** [comment]
Just released it.

**Pull request merged**
