### PR TITLE
add initial support for postgres migration generation

### PR DESCRIPTION
**Pull request by llwt**
I wasn't sure how to test this, happy to add some if you've got an example or idea of how to add them. I worked off of the implementation in the MySqlQueryRunner for most of this but didn't see any coverage added when that functionality was added.

Relates to #403.

### CODE REVIEW

**Comment by pleerock** [comment]
Hi and thank you for your work. I think before I can merge this PR you'll need to complete all todos you left.

Regarding to tests, I didn't think how to test it yet... Probably we need to make a change, check if change in in the database, then revert it and check if change was reverted.

**Comment by llwt** [comment]
The TODOs here were just explicitly listing the down steps that weren't implemented in the migrations so they are called out and could be manually implemented. The forward steps should all be there.

In the MysqlQueryRunner there are places where you are currently not passing through the `schemaQuery` function and hitting the DB which seems undesired. I opted for the DB comment down script with a `TODO` statement instead.

For example in [MysqlQueryRunner #L566](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlQueryRunner.ts#L566):
```typescript
        if (newColumn.isUnique === false && oldColumn.isUnique === true)
            await this.query(`ALTER TABLE \`${tableSchema.name}\` DROP INDEX \`${oldColumn.name}\``); // todo: add revert code
```

I'm happy to implement the down steps when I get time, I just figured I'd push up the "up" logic since it seemed like it might be useful to others even without fully implemented "down" generation.

**Comment by pleerock** [comment]
I'll merge it and I hope you'll get some time to finish all todos.

**Comment by llwt** [comment]
Thanks! Sorry I haven't been able to fully flush this out. It's on the top of my list of TODOs, migration support is super helpful for our workflow.

**Pull request merged**
