### PR TITLE
Added an afterBulkLoad subscriber method to EntitySubscriberInterface

### PR DESCRIPTION
**Pull request by csuich2**
See #2700

### CODE REVIEW

**Comment by pleerock** [comment]
Yeah I was thinking about this feature for a while.

I guess it won't be logical to have it only for one `load` method, can you please implement same for all other subscriber methods?

Thank you very much for your contribution!

**Comment by csuich2** [comment]
@pleerock Sure thing. I've added subscribers for before & after insert, update and remove.

**Comment by pleerock** [comment]
changes huge and its hard and time consuming to review them

**Comment by mdmitry01** [comment]
Hi @pleerock!

I think this feature is useful. Is it going to be merged? Is there any reason for this not to be merged?

**Comment by imnotjames** [comment]
There's currently a wide range of conflicts - can they be resolved so I can review this PR?

@mdmitry01 if you'd like to resolve the conflicts and open a new PR / own the feature getting merged in I can close this PR and review yours.

**Review by imnotjames — CHANGES_REQUESTED** [review]
There's currently a wide range of conflicts - can they be resolved so I can review this PR?

**Comment by AlexMesser** [comment]
I'm closing this as it's failing, has conflicts and hasn't been updated in a few years. Anyway, thank you for contribution.

**Pull request closed without merging**
