### PR TITLE
Added test for issue #838

### PR DESCRIPTION
**Pull request by slavafomin**

### CODE REVIEW

**Comment by pleerock** [comment]
Let me merge this test and take a look on it deeply.

**Comment by pleerock** [comment]
What is proper syntax for inserting date time with timezone in postgres? When I do `INSERT INTO "flight" ("id", "date") VALUES (4, '1989-08-16T10:00:00+03:00');`, I have following record in database:

```
4	1989-08-16 14:00:00.000000 +07:00
```

which does not look correct

**Comment by pleerock** [comment]
If you simply do:

```ts

        await postgresConnection.query(`INSERT INTO "flight" ("id", "date") VALUES (1, '1989-08-16 14:00:00.000000 +03:00');`);
        const results = await postgresConnection.query(`SELECT date FROM "flight" WHERE id = 1`);
```

It will give you following:

```
executing query:  INSERT INTO "flight" ("id", "date") VALUES (1, '1989-08-16 14:00:00.000000 +03:00');
executing query:  SELECT date FROM "flight" WHERE id = 1
[ anonymous { date: 1989-08-16T11:00:00.000Z } ]
```

TypeORM DOES NOT DO ANYTHING HERE, 0 ACTIONS, it just delegates query further to pg driver. It means problem is on another layer or there is an issue on how we insert the data into the database.

**Comment by robinsummerhill** [comment]
@pleerock Your insert/select above is showing expected behaviour. Postgres will convert a datetime to UTC when persisting a value to a `timestamp with time zone` field. Any client that displays it (e.g. psql, pgadmin etc) will convert it back to localtime using the current timezone.

It is unfortunate that the name 'timestamp with timezone' is misleading. Postgres **does not** store the timezone at all - it just does a conversion to UTC before persisting it. That's **all** it does.

You input ('1989-08-16 14:00:00.000000 +03:00') and output ('1989-08-16T11:00:00.000Z') are completely equivalent and point to the exact same moment in time.

**Comment by pleerock** [comment]
@robinsummerhill thank you for your explanation, so postgres converts to zero utc whatever date without whatever utc I pass to it

**Pull request merged**
