### PR TITLE
chore(tests): Changed default tests to use mocha directly

### PR DESCRIPTION
**Pull request by pdeszynski**
Changed default test script to use mocha directly instead of running CI tests.

Added precommit script to use tsling with fix flag.

### CODE REVIEW

**Comment by pdeszynski** [comment]
@pleerock I've had locally a lot of tests failed (both using gulp script and running mocha directly from package.json script) like:

```
  1) database schema > column types > mysql
       "before all" hook:
     DataTypeNotSupportedError: Data type "Object" in "PostWithoutTypes.blob" is not supported by "mysql" database.
      at new DataTypeNotSupportedError (src/error/DataTypeNotSupportedError.ts:9:9)
      at src/metadata-builder/EntityMetadataValidator.ts:81:27
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validate (src/metadata-builder/EntityMetadataValidator.ts:78:36)
      at src/metadata-builder/EntityMetadataValidator.ts:42:56
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validateMany (src/metadata-builder/EntityMetadataValidator.ts:42:25)
      at Connection.buildMetadatas (src/connection/Connection.ts:487:33)
      at Connection.<anonymous> (src/connection/Connection.ts:186:18)
      at step (src/connection/Connection.ts:32:23)
      at Object.next (src/connection/Connection.ts:13:53)
      at fulfilled (src/connection/Connection.ts:4:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  2) database schema > column types > mysql
       "after all" hook:
     TypeError: Cannot read property 'map' of undefined
      at Object.closeTestingConnections (test/utils/test-utils.ts:262:36)
      at Context.<anonymous> (test/functional/database-schema/column-types/mysql/column-types-mysql.ts:19:17)

  3) database schema > column types > sqlite
       "before all" hook:
     DataTypeNotSupportedError: Data type "Object" in "PostWithoutTypes.blob" is not supported by "sqlite" database.
      at new DataTypeNotSupportedError (src/error/DataTypeNotSupportedError.ts:9:9)
      at src/metadata-builder/EntityMetadataValidator.ts:81:27
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validate (src/metadata-builder/EntityMetadataValidator.ts:78:36)
      at src/metadata-builder/EntityMetadataValidator.ts:42:56
      at Array.forEach (<anonymous>)
      at EntityMetadataValidator.validateMany (src/metadata-builder/EntityMetadataValidator.ts:42:25)
      at Connection.buildMetadatas (src/connection/Connection.ts:487:33)
      at Connection.<anonymous> (src/connection/Connection.ts:186:18)
      at step (src/connection/Connection.ts:32:23)
      at Object.next (src/connection/Connection.ts:13:53)
      at fulfilled (src/connection/Connection.ts:4:58)
      at <anonymous>
```

would be great if somebody with full development setup could test it.

**Comment by pleerock** [comment]
I'll merge this PR and will check it.

**Comment by pleerock** [comment]
fixed it in latest commit. I was not able to successfully run with ` -r ts-node/register` flag - it completely hangs out for me.

**Comment by pdeszynski** [comment]
@pleerock strange, first run was for me longer, but I didn't have hanging issue.

**Comment by pdeszynski** [comment]
@pleerock Don't you want to make one more try `ts-node`? When comparing times to run 1 test the result is like:

``` 
yarn exec mocha -- -r ts-node/register --file ./test/utils/test-setup.ts test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts


  basic-lazy-relations
    ✓ should persist and hydrate successfully on a relation without inverse side


  1 passing (30ms)

✨  Done in 2.19s.
```

vs the old way:

```
 yarn test  ./build/compiled/test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts
yarn run v1.6.0
$ tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail './build/compiled/test/**/*.js' --timeout 30000 --color ./build/compiled/test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts


  basic-lazy-relations
    ✓ should persist and hydrate successfully on a relation without inverse side


  1 passing (15ms)

✨  Done in 35.08s.
```

Could you try once more to run:

`yarn exec mocha -- -r ts-node/register  --file ./test/utils/test-setup.ts test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts` if it works for you if you use `yarn` or `npx mocha -- -r ts-node/register  --file ./test/utils/test-setup.ts test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts` for npm?

**Pull request merged**
