### PR TITLE
fix: use an empty string enum as the type of a primary key column

### PR DESCRIPTION
**Pull request by BTOdell**
Closes: #3874

### CODE REVIEW

**Comment by pleerock** [comment]
I'm a bit scary to merge this one... Hope it won't break anything.

**Comment by BTOdell** [comment]
I understand your concerns. I was very careful in reading through the code thoroughly before making this change.

The `id` variable will always be a `string`. It will never be `null` or `undefined` because it's the return value from the `Array.join` function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join

That means the ```if (!id)``` condition only succeeds if `id` is an empty string. `id` is used as a key into a `Map` but there is nothing invalid about using an empty string as a Map key.

This pull request will also fix issues with empty strings in `varchar` primary columns.

**Comment by pleerock** [comment]
That's right, it's what we have at the end. However what if there is no primary key at all (someone selected data without `id` column lets say)? With previous changes it wont return anything. With new changes it will treat every selected row as a row of the same entity with id = `""`. Entity selection without id isn't valid case in the framework. But before we returned `[]` for such cases, now we'll return rows - this is more confusing and people may use this behaviour without understanding of what they should do.

**Comment by pleerock** [comment]
I can agree your case is valid, however its super rare I think. Okay, let's merge it and see how it goes.

**Pull request merged**
