### PR TITLE
added test for #1972

### PR DESCRIPTION
**Pull request by Gecko222**

### CODE REVIEW

**Comment by rootsher** [comment]
#2000 !!!

**Comment by rootsher** [comment]
@pleerock https://travis-ci.org/typeorm/typeorm/builds/370098155#L5620

**Comment by rootsher** [comment]
@pleerock why did you merge our PR with the master branch? Our test has not passed after your changes :(

**Comment by pleerock** [comment]
yeah I know, thats okay, Im working on fix currently

**Pull request merged**
