### PR TITLE
0.2.0 release changes

### PR DESCRIPTION
**Pull request by pleerock**
everything is going to land into 0.2.0 final. You can try next TypeORM version by installing it `npm i typeorm@next`

### CODE REVIEW

**Comment by pleerock** [comment]
@daniel-lang can you please check why sqljs fails?

```

  sqljs driver > autosave
    1) should call autoSaveCallback on insert, update and delete


  107 passing (1m)
  4 pending
  1 failing

  1) sqljs driver > autosave should call autoSaveCallback on insert, update and delete:

      AssertionError: expected 0 to equal 7
      + expected - actual

      -0
      +7
      
```

**Comment by pleerock** [comment]
I think I know the reason. Update, insert and delete queries are not wrapped in the transaction anymore (until specific option set) since they always execute only one query

**Comment by daniel-lang** [comment]
@pleerock which commit are you running? I tried the most current one (f1399ee) and the tests run fine locally.

**Comment by pleerock** [comment]
Latest. Looks like I had this issue because of `"autoSave": false` in my local ormconfig.json left.

 I also found that I cannot set "skip: true" in ormconfig - this test fails on connection since createConnection does not return connection if driver is skipped

**Comment by daniel-lang** [comment]
fixed the problem with skipping the tests in #1462

**Comment by tonyxiao** [comment]
@pleerock do you have any estimate for when 0.2.0 will officially come out?

**Comment by pleerock** [comment]
@tonyxiao end of this month, beginning of next. Once I'll get enough feedback from the community about `@next` working fine without problems.

**Comment by daniel-lang** [comment]
There is no problem with packaging (tested on ionic/cordova with webpack). But there seems to be a problem with cascade inserts
```sql
INSERT INTO "author"("name", "birthdate") VALUES (?, NULL) -- PARAMETERS: ["Person"]
INSERT INTO "post"("title", "text", "authorId") VALUES (?, ?, NULL) -- PARAMETERS: ["Control flow based type analysis","TypeScript 2.0 implements a control flow-based type analysis for local variables and parameters."]
INSERT INTO "category"("name") VALUES (?) -- PARAMETERS: ["TypeScript"]
INSERT INTO "category"("name") VALUES (?) -- PARAMETERS: ["Programming"]
INSERT INTO "post_categories_category"("postId", "categoryId") VALUES (NULL, NULL), (NULL, NULL)
```
These queries are taken from the ionic example after updating the entities to the new cascade syntax:
```ts
@ManyToMany(type => Category, {
    cascade: ['insert']
})
@JoinTable()
categories: Category[];

@ManyToOne(type => Author, author => author.posts, {
   cascade: ['insert']
})
author: Author;
```

**Comment by pleerock** [comment]
> There is no problem with packaging (tested on ionic/cordova with webpack). But there seems to be a problem with cascade inserts

@daniel-lang what driver is used? There are tests with cascade inserts running on all drivers (except websql) and they are passing.

**Comment by daniel-lang** [comment]
@pleerock using `cordova` driver. Should I create a seperate issue for it and investigate there?

**Comment by pleerock** [comment]
@daniel-lang issue is not required if you can quickly fix it. Maybe issue is related to how auto-generated value is returned after insertion (driver#createGeneratedMap method)?

**Comment by daniel-lang** [comment]
will take a look at it

**Comment by pleerock** [comment]
thanks!

**Comment by dcworldwide** [comment]
Awesome

**Pull request merged**
