### PR TITLE
fix: correct encode mongodb auth credentials

### PR DESCRIPTION
**Pull request by leoojg**
### Description of change

It fix an unauthorized error when connecting to mongodb using the character `@` in the credentials

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by leoojg** [comment]
@pleerock the tests didn't pass cause i forgot to close the connection?

**Comment by pleerock** [comment]
@leoojg thanks for fixing the linter. I edit files online (via github) that's why it happened from my end.

> @pleerock the tests didn't pass cause i forgot to close the connection?

yes.

**Comment by leoojg** [comment]
I had some issues running tests locally, it would be amazing if in the docs has some kind of docker-composer to pre-set the test environment

**Comment by pleerock** [comment]
@leoojg we already have docker-compose. If you think there is an area to improve - feel free to contribute.

**Comment by leoojg** [comment]
> @leoojg we already have docker-compose. If you think there is an area to improve - feel free to contribute.

Indeed, i just didn't saw it  e.e

**Pull request merged**
