### PR TITLE
Add support for json datatype for sqlite

### LINKED ISSUE #8972: DataTypeNotSupportedError: Data type "json" in "xxx" is not supported by "sqlite" database.
Hi All,

The latest version of SQLite supports `json` type https://www.sqlite.org/json1.html, but in the TypeORM business logic no. Do you have any plan to update it based on the last SQLite version?

https://github.com/typeorm/typeorm/blob/master/src/driver/types/ColumnTypes.ts#L188

https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite-abstract/AbstractSqliteDriver.ts#L128

I need this for e2e testing. By removing this constraint, I will be able to add all my e2e tests very easily without any workaround.

`timestamp` type is supported by SQLite as well.

### PR DESCRIPTION
**Pull request by bahung1221**
### Description of change

Fixes #8972 

SQLite supported the json data type since version 3.38 ([changelog](https://www.sqlite.org/releaselog/3_38_0.html)) but typeorm drivers (sqlite and better-sqlite3) were missing that data type.

both sqlite and better-sqlite3 library are using the sqlite version 3.40:
- sqlite: https://github.com/TryGhost/node-sqlite3/commit/aec0d31253f73794cdc67c637cdece74bc5dea44
- better-sqlite3: https://github.com/WiseLibs/better-sqlite3/commit/36cf1c47bd6ab39146859e48de4b7d957ffb6dca

This PR will allow typeorm's users to use the json data type for both drivers.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AlexMesser** [comment]
@bahung1221 please update [this test](https://github.com/typeorm/typeorm/blob/master/test/functional/database-schema/column-types/sqlite/column-types-sqlite.ts) with the new type to make sure synchronization works as expected

**Comment by bahung1221** [comment]
Thanks @AlexMesser , I added the test 🍻

**Comment by AlexMesser** [comment]
thank you for contribution!

**Comment by KillerCodeMonkey** [comment]
Question: in general simple-json is doing the same things when i see it correcty -> why not simply extend the existing condition there and using the alrady exising helpers?

```TS
if (["json", "simple-json"].includes(columnMetadata.type)) { 
  return DateUtils.simpleJsonToString(value)
}
```

**Comment by AlexMesser** [comment]
since new `sqlite` versions supports `json` type natively, `simple-json` is not needed anymore and will be removed from `SqliteDriver` in future versions.

**Comment by KillerCodeMonkey** [comment]
but even then it would make sense not to have JSON.stringify and .parse in two places?

**Comment by klemti** [comment]
As far as I know, the 'react-native' DataSource implementation uses SQLite driver (exclusively).  Shouldn't this change be replicated to the 'react-native' DataSource type to allow React Native apps to take advantage of the JSON field type?

**Pull request merged**
