### PR TITLE
fix(#7730): Default values filter numeric types, and empty strings

### LINKED ISSUE #7730: TypeError: value.toUpperCase
When Default value is not a string, a method that does not exist is called

image

image
image

https://github.com/typeorm/typeorm/blob/ff28aad27958ef7763a305982f70caeb611f2448/src/driver/mysql/MysqlDriver.ts#L946

### PR DESCRIPTION
**Pull request by jinpy666**
### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #7730`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by imnotjames — CHANGES_REQUESTED** [review]
This should instead just check that it's typeof string shouldn't it?  Probably could live with that instead of the number check.  Why do we add the empty string check? 

If this function can possibly accept non-strongs maybe it should be an `any` in the parameter type?

**Comment by jinpy666** [comment]
> This should instead just check that it's typeof string shouldn't it? Probably could live with that instead of the number check. Why do we add the empty string check?

My case is： **default:()=>''**
That's why you need to determine the empty string.
My intention was to block it at the beginning and not have to go through the following process.
Please look at the second anser.

> If this function can possibly accept non-strongs maybe it should be an `any` in the parameter type?
Yes.
https://github.com/typeorm/typeorm/blob/53b33e105d1b0e25b1594c88c4405cacc34ff5bb/src/driver/mysql/MysqlDriver.ts#L604-L607

When the default is function, can always access to normalizeDatetimeFunction, inside is not very good type judgment, lead to syntax error, and through the Google search the default values demo, mostly use the function to input.

**Comment by imnotjames** [comment]
> My case is： default:()=>''
> That's why you need to determine the empty string.

Your code change will not affect this because the value you're looking for is `"''"`, not an empty string (`""`).

What is the issue you're trying to solve for here?

**Review by imnotjames — CHANGES_REQUESTED** [review]
Please also add tests for this

**Pull request closed without merging**
