### PR TITLE
fix: logMigration has correct logging condition

### PR DESCRIPTION
**Pull request by bejewelkyoungminkim**
Closes: #10322

### Description of change

AbstractLogger has various log method for various type of error.
But only logMigration method has wrong condition.
I have fixed this issue.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by hinogi — APPROVED** [review]
LGTM

**Comment by bejewelkyoungminkim** [comment]
@hinogi Thank you. I just added test description, I missed it : )

**Comment by bejewelkyoungminkim** [comment]
All of ci are passed. I'm waiting for merging this PR. thank you.
@hinogi @AlexMesser

**Comment by AlexMesser** [comment]
thank you for contribution!

**Pull request merged**
