### PR TITLE
fix: Create correct children during cascade saving entities with STI

### LINKED ISSUE #7558: Child entities' wrong discriminator value when embedded in parent entity
## Issue Description

Here are my 3 entities: Each `person` can have a given number of `animal`, which can be either `cat` or `dog`.
```ts

@Entity({ name: 'person' })
export class PersonEntity extends BaseEntity {
  @PrimaryColumn()
  id!: number;

  @OneToMany(() => AnimalEntity, ({ person }: AnimalEntity) => person, {
    onDelete: 'CASCADE',
    cascade: true,
  })
  pets!: AnimalEntity[];
}


@Entity({ name: 'beings' })
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
export class BeingEntity extends BaseEntity {
  @PrimaryColumn()
  id!: number;
}



@ChildEntity('animal')
export class AnimalEntity extends BaseEntity {
  @Column({ type: 'varchar' })
  name!: string;
}

@ChildEntity('cat')
export class CatEntity extends AnimalEntity {
  // Cat stuff
}

@ChildEntity('dog')
export class DogEntity extends AnimalEntity {
  // Dog stuff
}
```

### Expected Behavior

```ts

const pets = [
  this.catRepo.create({
    name: 'felix',
    // Cat stuff
  }),
  this.dogRepo.create({
    name: 'spike',
    // Dog stuff
  }),
];
const person = this.personRepo.create({ pets });


await this.connection.manager.save(person);
```
```ts

// Created [
//     { type: 'cat', personId: 42, name: 'felix', other cat stuff }, 
//     { type: 'dog', personId: 42, name: 'spike', other dog stuff }, 
//     { id: 42, people stuff }
//  ]

```

### Actual Behavior

```ts
// Created [
//     { type: 'animal', personId: 42, name: 'felix', other cat stuff }, 
//     { type: 'animal', personId: 42, name: 'spike', other dog stuff }, 
//     { id: 42, people stuff }
//  ]

```

As you can see, once the `animal` entities as embedded to a `person`, then they lose their specific type.
The entity manager saves them as `animal` (probably because `person` declare an `animal` and not a specific species).

### Workaround

```ts

const pets = [
  this.catRepo.create({
    name: 'felix',
    personId: 42, // assuming i know the personId in advance
    // Cat stuff
  }),
  this.dogRepo.create({
    name: 'spike',
    personId: 42, // assuming i know the personId in advance
    // Dog stuff
  }),
];
const person = this.personRepo.create({  id: 42 });


// What's important here is that the `cat` and `dogs` are saved individually.
// The drawback is that because we dont embed the pet entities, the linking must be done manually.
await this.connection.manager.save([...pets, person]);

// Created [
//     { type: 'cat', personId: 42, name: 'felix', other cat stuff }, 
//     { type: 'dog', personId: 42, name: 'spike', other dog stuff }, 
//     { id: 42, people stuff }
//  ]
```

Here, it works, probably because the real entity types `dog` and `cat` are not morphed-up into `animal`.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v15.11.0 | 
| Typescript version  | typescript@4.2.3 | 
| TypeORM version     | typeorm@0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### LINKED ISSUE #9033: 🤨 Cannot manually insert type in discriminator column of parent entity class when using single table inheritance when creating instance of parent entity
## Issue Description
Not sure if this is the intended behavior or not, but is it possible to directly just use the parent entity class when using STI  and manually set the type? I have been trying to do bulk inserts with fake data by using the parent class, but the 'type' column gets overwritten with the parent entity class's name. 

### Steps to Reproduce

1. Copy paste single table inheritance example from docs,
2. Add column for type in the Content class
3. Attempt to insert data into the Content table using querybuilder, or if you want to implement base entity, the create() method, with the type field set to any of the child entities.
4. Inserts will work, but the results will have type column overwritten with "Content", regardless if it is input or not.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 10         |
| Node.js version     | 14.17.5  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | yes            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅  No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by felix-gohla**
### Description of change

This PR fixes an issue when saving entities from a Single Table Inheritance schema linked to another entity (e.g. one entity, many STI-children). The wrong class was created (wrong discriminator saved to the DB).

Take the example from the issue, then when saving `Animals` (explicitly: `Dogs` and `Cats` inheriting from `Animal`) connected to a `Person`, only `Animals` were created.

Now, the `create` function also checks whether the expected value is an entity of a class of a child entity and creates the correct class.

Fixes #7558
Fixes #9033 

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by felix-gohla** [comment]
@OoDeLally, @francescosalvi and @agwermann, could you please have a look at whether this fixes the problem? 😊

**Comment by francescosalvi** [comment]
@felix-gohla unfortunately I couldn't manage to get your repo/branch to build locally, anyway by looking at the unit test, if I am not mistaken I don't see the test case that I would expect, which would be:

* create parent class (e.g. `Animal`) by setting discriminant column value explicitly (`type:="dog"`)
* save above entity
* load it back (using the `Animal` repository)
* assert loaded entity is of `Dog` sub-type (`instanceof`)
* assert discriminant column (`type`)'s value matches the original one (`"dog"`), instead of the current "lowercase-first" parent class name (which currently would equal to `"animal"`).

**Comment by felix-gohla** [comment]
@francescosalvi Thanks for your quick response and for having a look at the code.

I am not sure, however, how the test you describe is related to the issue mentioned in #7558. Do you maybe mean #9033 or do you think that those two are the same thing?

**Comment by francescosalvi** [comment]
@felix-gohla I don't think I knew about #9033 actually... but yeah it looks like #7558 is just a "more complex" case for what is also described in #9033. In any case the final effect is the same. I mean it should be simple to add the case I described and see if it got fixed by your PR, in such case we can safely infer root cause is the same.

**Comment by francescosalvi** [comment]
@felix-gohla thanks for also addressing #9033!

**Comment by pleerock** [comment]
This one is hard to review. I need people who use STI, can test these changes and approve this PR.

**Comment by felix-gohla** [comment]
Hi @pleerock, thanks for looking into this! Is there anything I can do to make it easier? 🤔 😊

**Comment by pleerock** [comment]
> Hi @pleerock, thanks for looking into this! Is there anything I can do to make it easier? 🤔 😊

Ask other cleaver enough people to review and test your changes and be patient on this PR ☯️

**Comment by AlexMesser** [comment]
@felix-gohla can you merge the latest `master` changes to your branch? Hope it will fix CI issue.

**Comment by pleerock** [comment]
the error CI gives is weird and appear only on some users... maybe users miss some permissions to CircleCI, not sure why this happens...

**Comment by AlexMesser** [comment]
@felix-gohla I am trying to re-trigger CircleCI Pipeline by pushing a small change, but getting `remote: Permission to giz-berlin/typeorm-1.git denied to AlexMesser`. Can you please review permissions and allow me to push.

**Comment by pleerock** [comment]
@felix-gohla the problem is that for some reason CircleCI didn't run the tests for the commit you did. So @AlexMesser wanted to push something to your branch in order to trigger CircleCI to run your tests.

Have no idea why CircleCI behaves this way, e.g. doesn't run the tests for you.

**Comment by felix-gohla** [comment]
I understand that he wanted to push something in order to trigger the tests.
However, I cannot provide him with push access (as I cannot set the access rights myself!).

If it's the changes that should fix something, I am happy to apply them if he pastes them here in the MR as text.
If it's just another push to re-trigger the pipeline, I can also just force push.
If you think that the problem is that @AlexMesser did not push but I did, then I will try my best to give him push access when my superior is back from vacation. :D

**Comment by felix-gohla** [comment]
My suspicion is that our repo was called `typeorm-1` instead of `typeorm`. Could this be the problem? I renamed the repo. Maybe you could re-trigger the pipeline? 😊

**Comment by felix-gohla** [comment]
I fixed the tests. 😊

**Comment by pleerock** [comment]
@felix-gohla I'll merge this PR, but please watch for the issues on STI - it case if it will break something - we need to react. This area is a bit complicated, that's why I can never be 100% sure that all changes are absolutely valid. Thank you.

**Comment by pleerock** [comment]
@felix-gohla tests on master currently fail after I merged it. Can you please take a look? It looks like there are some recent changes (#9786 ?) that conflicted with what you had in your test

**Comment by felix-gohla** [comment]
See #10037

**Pull request merged**
