### PR TITLE
fix: filter create order case empty string

### PR DESCRIPTION
**Pull request by winzaa123**
fix issue : #5114

### CODE REVIEW

**Comment by pleerock** [comment]
Not sure I can merge it right now since I don't remember why we needed that `.replace(",", "")` feature for.

**Comment by winzaa123** [comment]
image

i just don't need "" empty string in createOrderByCombinedWithSelectExpression function

**Comment by imnotjames** [comment]
Can you create tests that verify this fixes the issue?

**Review by imnotjames — CHANGES_REQUESTED** [review]
Can you create tests that verify this fixes the issue?

**Comment by imnotjames** [comment]
Thanks for your contribution!  However, without tests that confirm this fixes the correct behavior we cannot accept this pull request.

Once you're able to get back to working on this and add tests which show this corrects the specified behavior please re-open a new PR.

**Pull request closed without merging**
