### PR TITLE
add mongodb transaction support, add filterArray in mongo update options

### PR DESCRIPTION
**Pull request by chengjia0807**
Hi guys,

I created a pull request for supporting simple mongodb transaction. Also I added filterArray as a mongodb update option.

Please have a play with my changes and let me know if I need to change any more things.

Thanks
CJ

### CODE REVIEW

**Comment by chengjia0807** [comment]
the test failed because the testing environment is using MongoDB 3.6 which does not support transaction.

**Comment by pleerock** [comment]
Can you try to upgrade CI mongodb version?

**Comment by taosher** [comment]
Hi @chengjia0807 , are u still working on this job? 
I found this pull request when I'm trying to  add mongodb transaction support myself.
It seems that this job has been paused for a month.  
If there is some problems on this pull request, I think I may do some help for u.
Or I may create a new pull request on this issue if your pull request is discard, as I need this feature very much.

**Comment by chengjia080787** [comment]
> Hi @chengjia0807 , are u still working on this job?
> I found this pull request when I'm trying to add mongodb transaction support myself.
> It seems that this job has been paused for a month.
> If there is some problems on this pull request, I think I may do some help for u.
> Or I may create a new pull request on this issue if your pull request is discard, as I need this feature very much.

Hey mate, I don't have enough time working on this, the unit test on CI/CD pipeline is a bit hard to fix. Please feel free to do whatever you want. What I did for my project was I built a special version just for my own project. 

Please feel free to contribute or change whatever on this issue. All I can prove is that what I did here can work properly in my own projects.

Cheers bro.

**Review by imnotjames — CHANGES_REQUESTED** [review]
If you are enabling a feature that must have a specific version of mongo to operate either disable the feature on versions that don't support it (ideal) or we will need to wait to the next minor release to do a backwards compatibility break.

Also, can this be split to just the transaction change or just the filter array change?

Lastly, this needs explicit tests to confirm what we are doing is fixing the expected behaviors.

**Comment by AlexMesser** [comment]
I'm closing this as it's failing, has conflicts and hasn't been updated in a few years. Anyway, thank you for contribution.

**Pull request closed without merging**
