### PR TITLE
feat: add support for SQLite ON CONFLICT clause

### PR DESCRIPTION
**Pull request by rsbh**
Sqlite provides `ON CONFLLICT` at the time of table creation. 
https://sqlite.org/conflict.html

### CODE REVIEW

**Comment by pleerock** [comment]
Thanks for contribution.

What if we change `onConflict`? Would ORM properly react on changes? Also, this feature needs a test coverage.

**Comment by rishabh09** [comment]
@pleerock i will add some tests for this change

**Comment by pleerock** [comment]
tests are failing

**Review by imnotjames — CHANGES_REQUESTED** [review]
This still needs tests that confirm this is working as expected

**Pull request closed without merging**
