### PR TITLE
Migrations support

### PR DESCRIPTION
**Pull request by pleerock**

### CODE REVIEW

**Comment by dreamersp** [comment]
You're great!
We are giving it a shot right away!

**Comment by dreamersp** [comment]
In the sample you added, migrations are executed on connection creation, is there a planned option for running them on a cli command?
Thanks a lot!

**Comment by pleerock** [comment]
yes, take a look on source code - it is already there. However there are few things left to finish, this PR is not finished yet

**Comment by pleerock** [comment]
@dreamersp - basic functionality is there. Can you try it and left your feedback here, before it goes to the main branch? 

1. do `npm i typeorm@next -g`
2. run `typeorm -h` to get help

**Comment by pleerock** [comment]
looks like working like a charm. added docs [here](https://typeorm.github.io/migrations.html) and updated [example how to use it](https://github.com/typeorm/typescript-example)

**Comment by dreamersp** [comment]
Your proposed workflow is to first deploy with autoSchemaSync enabled, and later deploy with autoSchemaSync disabled and add new changes in migrations? Or we shall implement the table creation in the first migration by hand to keep autoSchemaSync disabled?

**Comment by dreamersp** [comment]
The generated migration file lacks  `QueryRunner, Connection` dependencies in the `import .. from 'typeorm'` line.

**Comment by pleerock** [comment]
> Your proposed workflow is to first deploy with autoSchemaSync enabled, and later deploy with autoSchemaSync disabled and add new changes in migrations? Or we shall implement the table creation in the first migration by hand to keep autoSchemaSync disabled?

choice is up to you I think. You can disable all flags and use only CLI for both schema sync and migrations run on production.

> The generated migration file lacks QueryRunner, Connection dependencies in the import .. from 'typeorm' line.

I already fixed that. Try latest version of typeorm

**Comment by dreamersp** [comment]
Yup, I saw that a few minutes later version 0.0.5 fixed last comment about the dependencies, sorry!

Going back to the table generation, QueryRunner has a createTable() method that takes a TableSchema. Is there a way to obtain a TableSchema from a class with `@Table()` decorator? That way we can generate swiftly a first migration, although it will not execute the same way depending if there are changes and deployed to a new or old environment.

**Comment by pleerock** [comment]
you can use `connection.getMetadata(Entity)` to get `EntityMetadata` of your entity. This object contains all information about your entity. Then you can manually transform this metadata into TableSchema. Maybe later I'll add some api to simplify this process

**Comment by sandokanelcojo** [comment]
Hi @pleerock, have you come to an automated way to do this process?
I'm facing ths specific need right now.

**Comment by pleerock** [comment]
hey @sandokanelcojo what exactly are you talking about?

**Comment by sandokanelcojo** [comment]
Hi!
About this line in your last comment: **"Maybe later I'll add some api to simplify this process"**

Right now I'm doing exactly what you said, using connection.getMetadata() to get EntityMetadata and then manually transforming it to a TableSchema.

I thought maybe you had time to create this API. Just asking!

**Comment by pleerock** [comment]
not yet.. btw you may want to try to create `SchemaBuilder` and send there only one entity metadata of your newly created entity - maybe that will work

**Comment by sandokanelcojo** [comment]
Hi again @pleerock !

We've been trying to run migrations the way you've suggested and have run into some problems, let's see if you can shed some light in the subject.

Let's illustrate the case with an example. Say we have 3 models User, Role and Session.
User and Role have a m:n relation, ergo they must have a JoinTable (user_role).
Also, we have User and Session, where there is a 1:n relation, so there will be a single FK from Session to User.

There go the simplified models:

// FILE USER.MODEL
```javascript
@Table('user')
export class User {
  @PrimaryGeneratedColumn()
  id: number;  

  @ManyToMany(type => Role, role => role.users)
  @JoinTable({name:'user_role'})
  roles: Role[] = [];
}
```

// FILE ROLE.MODEL
```javascript
@Table()
export class Role {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @ManyToMany(type => User, user => user.roles, {
    cascadeInsert: true,
    cascadeUpdate: true,
    cascadeRemove: true
  })
  users?: User[];
}
```

// FILE SESSION.MODEL
```javascript
@Table()
export class Session implements SessionAttributes {
  @PrimaryGeneratedColumn()
  id: number;

  @OneToOne(type => User, user => user.id)
  user: User;
}
```

And a helper to actually build the tables...

// FILE helpers/migration
```javascript
export async function getTableSchemaFromEntityMetadataAndBuild(entities: Function[], connection: Connection): Promise<void> {
  let metadataArr: EntityMetadata[] = [];
  entities.forEach(entity => metadataArr.push(connection.getMetadata(entity)));
  // connection.entityMetadatas.forEach(em => console.log(em.name));
  let builder: SchemaBuilder = new SchemaBuilder(connection.driver, connection.logger, metadataArr);
  await builder.build();
}
```

If we just call '''connection.syncSchema(false);''' then every table is created and every FK is OK.
But that's not what we want...

**Comment by sandokanelcojo** [comment]
Here is a migration to create the tables User and Session:

// MIGRATION FILE 1
```javascript
import { getTableSchemaFromEntityMetadata } from '../helpers/migration';
import { Role } from './initial-models/role.model';
import { Session } from './initial-models/session.model';
import { User } from './initial-models/user.model';

export class InitialTables1481552406770 implements MigrationInterface {
  models: Function[] = [Role, User];
  async up(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {
    await getTableSchemaFromEntityMetadataAndBuild(this.models, connection);
  }
}
```

The first time we execute it, it creates the tables but fails on creating the FK's (The query is malformed), the second time FK's are created correctly.

Here the outputs:

**1st exec**
```
executing query: START TRANSACTION
User
Session
executing query: SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'ts_bare_devel' AND TABLE_NAME IN ('session', 'user')
executing query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'ts_bare_devel'
executing query: SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'ts_bare_devel' AND INDEX_NAME != 'PRIMARY'
executing query: SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'ts_bare_devel' AND REFERENCED_COLUMN_NAME IS NOT NULL
executing query: START TRANSACTION
executing query: CREATE TABLE `session` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `accessToken` varchar(255) NOT NULL, `refreshToken` varchar(255) NOT NULL, `accessExpiryDate` datetime NOT NULL, `refreshExpiryDate` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `user` int(11)) ENGINE=InnoDB;
executing query: CREATE TABLE `user` (`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `nick` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `surname` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `phone` varchar(255), `picture` varchar(255), `is_active` tinyint(1) NOT NULL DEFAULT '1', `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB; executing query: ALTER TABLE [object Object] ADD CONSTRAINT `fk_13d8bc8fcc13b20a496992863fa` FOREIGN KEY (`user`) REFERENCES `user`(`id`)
query failed: ALTER TABLE [object Object] ADD CONSTRAINT `fk_13d8bc8fcc13b20a496992863fa` FOREIGN KEY (`user`) REFERENCES `user`(`id`)
executing query: ROLLBACK
executing query: ROLLBACK
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[object Object] ADD CONSTRAINT `fk_13d8bc8fcc13b20a496992863fa` FOREIGN KEY ...
```
**2nd exec**
```
executing query: ALTER TABLE `user` CHANGE `is_active` `is_active` tinyint(1) NOT NULL DEFAULT '1'
executing query: ALTER TABLE session ADD CONSTRAINT `fk_13d8bc8fcc13b20a496992863fa` FOREIGN KEY (`user`) REFERENCES `user`(`id`)
executing query: COMMIT
executing query: INSERT INTO migrations(timestamp, name) VALUES (?,?) -- PARAMETERS: [1552406770,"InitialTables1481552406770"]
Migration InitialTables1481552406770 has been executed successfully.
```

**Comment by sandokanelcojo** [comment]
Here is a migration to create the tables User and Role:

// MIGRATION FILE 2
```javascript
import { getTableSchemaFromEntityMetadata } from '../helpers/migration';
import { Role } from './initial-models/role.model';
import { Session } from './initial-models/session.model';
import { User } from './initial-models/user.model';

export class InitialTables1481552406770 implements MigrationInterface {
  models: Function[] = [Role, User];
  async up(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {
    await getTableSchemaFromEntityMetadataAndBuild(this.models, connection);
  }
}
```

In this case there are no errors, but the join table is not created, so something is missisng...

**Comment by dreamersp** [comment]
Hi there!
Any comments or news in the migration front side of life?
@pleerock Did you have a look on @sandokanelcojo 's comments?

Thanks for your great work!

**Comment by pleerock** [comment]
no, completely forgot about it (thats why better to create issues where eyes can see all problems rather then comments in PRs). @dreamersp  Do you have same issue? @sandokanelcojo did you resolve your issue?

**Pull request merged**
