### PR TITLE
feature: add ability to get all registered connections from manager

### PR DESCRIPTION
**Pull request by posgarou**
This PR adds the ability to get all the connections currently registered with a manager.

Use case: In our application, we dynamically establish 0 or more connections.  This change would allow us to simplify shutdown code to something like:

```typescript
const connections = getAllConnections();

for (const connection of connections) {
  if (connection.isConnected) {
    await connection.close();
  }
}
```

### CODE REVIEW

**Comment by pleerock** [comment]
You can simply expose `connections` then. No need to create a separate method that returns them.

**Comment by posgarou** [comment]
The main reason I implemented it this way was to prevent external modifications to the `connections` array.  If that's not a concern, I can change this PR to make `connections` a public property.  Would you prefer that route?

**Comment by pleerock** [comment]
> The main reason I implemented it this way was to prevent external modifications to the connections array. 

yeah I understood that. I don't think its necessary currently. I don't like connection manager design tbh and maybe in the future I'll change its design. For now simply expose connections property.

**Comment by posgarou** [comment]
Sounds good.  I made the change and rebased.  👍

**Comment by pleerock** [comment]
Thank you. Btw you might be interested by #2358

**Pull request merged**
