### PR TITLE
Fixes #3946 - loadRelationCountAndMap fails when entities' primary keys are strings

### LINKED ISSUE #3946: loadRelationCountAndMap fails cause made a wrong IN calculation, when primary key is string
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `6.0.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have 3 tables, **unit**,**word**, and **unit_words** which is records the unit and word's many to many relationship.  
i am going to selelect one unit and the count of the words in it. i found the **loadRelationCountAndMap** method,looks it can help me.so i write code like this:  
```
  const loadedUnit = await connection.manager
            .createQueryBuilder(Unit, "unit")
            .leftJoinAndSelect("unit.words", "words")
            .loadRelationCountAndMap("unit.wordsCount", "unit.words")
            .where("unit.unit_id=:unitId",{unitId:"0fa1c80c-7a80-4809-84c6-daa9d59dccd5"})
            .getManyAndCount();
```
why i run the code ,i got an sql error, and i found the sql typeorm generate is like this
```
SELECT `words_rc`.`unit_id` AS `parentId`, COUNT(`word`.`word_id`) AS `cnt` FROM `word` `word` 
INNER JOIN `unit_words` `words_rc` ON `words_rc`.`unit_id` 
IN (0fa1c80c-7a80-4809-84c6-daa9d59dccd5,1943c3eb-3a6e-450d-8445-704a3dd795fd,46e4a934-fa40-4c82-ab2a-272138c2835a)
 AND `words_rc`.`word_id` = word.word_id GROUP BY `words_rc`.`unit_id`
```
problem is on **IN (0fa1c80c-7a80-4809-84c6-daa9d59dccd5,1943c3eb-3a6e-450d-8445-704a3dd795fd,46e4a934-fa40-4c82-ab2a-272138c2835a)**  

it seems should to be **IN ("0fa1c80c-7a80-4809-84c6-daa9d59dccd5","1943c3eb-3a6e-450d-8445-704a3dd795fd","46e4a934-fa40-4c82-ab2a-272138c2835a")**   

why that? is that a bug or some I did wrong?  
looks this post is a similar issue  
https://github.com/typeorm/typeorm/issues/2338

### PR DESCRIPTION
**Pull request by AntonioAngelino**
Fixes #3946 .

### CODE REVIEW

**Comment by pleerock** [comment]
`loadRelationCountAndMap` is going to be removed in the future versions of ORM, so I would like not to touch that area and recommend to avoid using this method (as well as other loadAndMap methods of QueryBuilder)

**Comment by AntonioAngelino** [comment]
@pleerock even if it's going to be removed (when? ETA?), I think merging this PR is useful because it fixes a bug.

We are using that function in production, please do not force us to fork typeorm and publish an npm package just to fix that bug, thank you. 

When the function is going to be removed, then the code + the unit tests I committed will be deleted and we will refactor our code.

**Comment by vlapo** [comment]
Looks like simple fix, all tests are green. We should merge this.

**Comment by pleerock** [comment]
okay, let's merge it. But @AntonioAngelino please consider changing your implementation in the future (we planning to remove these methods in 0.3.0).

**Pull request merged**
