### PR TITLE
feat: implement postgres ltree

### PR DESCRIPTION
**Pull request by tomSawkins**
This pr implements support for the ltree postgres extension.

Closes: #4193
Extension Docs: [ltree](https://www.postgresql.org/docs/9.1/ltree.html)

### Issue type:

Feature

### Database system/driver:

postgres

### CODE REVIEW

**Comment by pleerock** [comment]
Thank you!

**Comment by alysonfs** [comment]
i need very much. Tanks. but how to use?

**Comment by tomSawkins** [comment]
@alysonfs In case you missed it this feature got released in version 0.2.26 👍

**Comment by alysonfs** [comment]
> @alysonfs In case you missed it this feature got released in version 0.2.26 👍

hi man, yes. I'm use , tks. Perfect!

**Comment by edubskiy** [comment]
Can you make an example on how to use ltree with TypeORM or point the place in the TypeORM docs?

**Comment by alysonfs** [comment]
Yes of course. we will try...

I created a class that uses the typeorm

```javascript
import { Entity, Column, OneToMany } from 'typeorm';

@Entity({ orderBy: { 'id': 'DESC' } })
export default class Network {
  @Column('id', { nullable: true })
   id: string
   
  @ManyToOne(type => Network)
  parent: Network
  
  @OneToMany(type => Network)
  children: [Network]

  @Column(**'ltree'**, { nullable: true })
  way?: string
}
```

I hope it helped you

**Comment by edubskiy** [comment]
Thank you very much. 

`@Column('ltree', {
    nullable: true,
    array: true,
  })
  path: string[];`

and then how do I query them?

Right I query path as string like this:
`if (path) {
      query.andWhere(`program.path ${pathPattern || '~'} '*.${path}.*'`, {
        path,
      });
    }`

How can I convert this sample to query program.path if it contains array of strings?

I highly appreciate your help.

**Pull request merged**
