### PR TITLE
feature: add find operator json contains

### PR DESCRIPTION
**Pull request by ISary-ge**
Description of change
Add "JsonContains" operator to find in json for PostgreSQL

example:

``` TypeScript
this.repo.find({
    where: { id: In(ids), address: JsonContains({ city: { id: 12 } }) },
});
```

Pull-Request Checklist
Feature https://github.com/typeorm/typeorm/issues/9664

- [X] Code is up-to-date with the `master` branch
- [X] `npm run format` to apply prettier formatting
- [X] `npm run test` passes with this change
- [X] This pull request links relevant issues as `Feature #9664`
- [X] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
Great feature. Thank you for contribution. Will be good if you add the documentation to a new feature.

**Comment by sivercone** [comment]
thank you for this feature! can we use operator `In` inside `JsonContains`?

upd: looks like no..

**Comment by vlad-ostrovski** [comment]
Using `JsonContains` on a column that has a transformer will break the operator.

**Comment by Khaaz** [comment]
Is it possible to use this with "Not" operator in order to inverse the JsonContains operation?

**Comment by hfhchan-plb** [comment]
JsonContains should also support passing in raw numbers, strings, and arrays, not just Record.

**Comment by Kolobamanacas** [comment]
Did I understand correctly that I can't use `JsonContains` to find rows, where jsonb cell contains `value2`?

Cell example:

```json
["Value1", "Value2", "Value3"]
```

**Pull request merged**
