### PR TITLE
Fix jsonb comparison.

### PR DESCRIPTION
**Pull request by grin0c**
PR for #3496

### CODE REVIEW

**Comment by vlapo** [comment]
What about `json` data type? Is there same problem? Also `mysql` support `json` data type.

Also please add suitable record to `CHANGELOG.md` file.

**Comment by grin0c** [comment]
@vlapo Only JSONB, I wrote a comment in the code. 
What should I write in the CHANGELOG.md?

**Comment by vlapo** [comment]
Sure but from mysql docs:

> MySQL also discards extra whitespace between keys, values, or elements in the original JSON document. To make lookups more efficient, it also sorts the keys of a JSON object. You should be aware that the result of this ordering is subject to change and not guaranteed to be consistent across releases.

https://dev.mysql.com/doc/refman/8.0/en/json.html

I do not say your solution is bad. Just want have all covered by tests. So maybe add `json` column and enable `mysql` driver in your test would be nice.

> What should I write in the CHANGELOG.md?

Just simple description about fixing json/jsonb column data types comparison and link to issue :-)

**Comment by grin0c** [comment]
I checked on mysql 5.7, doesn't sort. But in any case, the method of comparison is universal for json and jsonb

**Comment by pleerock** [comment]
Thank you very much!

**Pull request merged**
