### PR TITLE
For newest typescript to compile

### PR DESCRIPTION
**Pull request by gintsgints**
Some tests fail to compile with my version of typescript. Small corrections allow to compile.

### CODE REVIEW

**Comment by hielkehoeve** [comment]
Which version of typescript are you using?

**Comment by gintsgints** [comment]
Version 2.9.2

**Comment by pleerock** [comment]
@gintsgints do we still need it?

**Comment by gintsgints** [comment]
@pleerock When I compile without thease changes I get compile warnings/errors

**Comment by pleerock** [comment]
this is strange, we don't have this error, also CI would fail if it had this error. Can you check the version you are using to compile? Maybe you are using global typescript package and not local one?

**Comment by Kononnable** [comment]
I think the point of this PR was to be able to compile typeorm with version different(newer) than installed locally. On typescript@3.1.3 we've got additionally(not fixed by this PR):
```typescript
test/integration/sample2-one-to-one.ts:252:50 - error TS6133: 'savedPost' is declared but its value is never read.

252         let newPost: Post, details: PostDetails, savedPost: Post;
                                                     ~~~~~~~~~

test/integration/sample2-one-to-one.ts:290:50 - error TS6133: 'savedPost' is declared but its value is never read.

290         let newPost: Post, details: PostDetails, savedPost: Post;
                                                     ~~~~~~~~~

test/integration/sample3-many-to-one.ts:252:50 - error TS6133: 'savedPost' is declared but its value is never read.

252         let newPost: Post, details: PostDetails, savedPost: Post;
                                                     ~~~~~~~~~

test/integration/sample3-many-to-one.ts:290:50 - error TS6133: 'savedPost' is declared but its value is never read.

290         let newPost: Post, details: PostDetails, savedPost: Post;
                                                     ~~~~~~~~~

test/integration/sample4-many-to-many.ts:255:50 - error TS6133: 'savedPost' is declared but its value is never read.

255         let newPost: Post, details: PostDetails, savedPost: Post;
                                                     ~~~~~~~~~

test/integration/sample4-many-to-many.ts:294:50 - error TS6133: 'savedPost' is declared but its value is never read.

294         let newPost: Post, details: PostDetails, savedPost: Post;
      
```

**Comment by pleerock** [comment]
mmm okay, we'll need to update dependencies

**Pull request merged**
