### PR TITLE
feat: allow explicitly named primary keys, foreign keys, and indices

### LINKED ISSUE #1355: Allow explicitly named primary keys, foreign keys, and indices
a `constraintName` option on `@Index`, `@PrimaryGeneratedColumn`, and `@JoinColumn` would be nice.

example:
```
@Entity()
class Post {
  @PrimaryGeneratedColumn({ 
    constraintName: 'pk_post_id' 
  })
  id: number

  @ManyToOne(author => Author, author => author.posts)
  @JoinColumn({ 
    constraintName: 'fk_post_author_id'
  })
  author: Author
}
```

### LINKED ISSUE #4572: How to create PRIMARY KEY index  index in typeorm? (index has name)
@index("index_XX")
@Column({ primary:true })
is not  work.

Result:
There are two indexes, one is the primary key index and the other is the normal index.

Expectations:
Only primary key index

### LINKED ISSUE #8321: Use sensible names for Indexes, Foreign Keys, Unique Indexes, etc...
## Feature Description

Use sensible names for Indexes, Foreign Keys, Unique Indexes, etc...

### The Problem

Debugging constraint issues, looking at the database, or looking at stacktraces where constraint's in the database fail, are all made harder than they should be, by having such obfuscated constraint names. Currently we get something like `FK_0b82f0b04f37c25a503fb3883cf` generated for foreign keys which is less than useful for any human viewing it. 

### The Solution

By default, many other frameworks add human readable identifiers to these database constraints. Even if you want to keep the unique part for extra safety, adding human readable identifiers clarifies things a lot. For example

**Best**
`FK_user_role_id`

**Good**
`FK_user_role_id_0b82f0b04f37c25a503fb3883cf`

**Bad**
`FK_0b82f0b04f37c25a503fb3883cf`

The same logic should apply to Indexes, references, unique indexes, etc.

### Relevant Database Driver(s)

| DB Type              | Relevant      |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | yes            |
| `mysql`              | yes            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | yes            |
| `sqlite-abstract`    | no            |
| `sqljs`              | yes            |
| `sqlserver`          | yes            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by AlexMesser**
### Description of change

Includes changes from #8524, fixes issues with existing custom constraint names (indices, uniques) and adds support for custom primary key constraint names.

**Custom FK names:** 

```typescript
@Entity()
export class Post {
    @ManyToOne((type) => Category)
    @JoinColumn({
        name: "cat_id",
        referencedColumnName: "name",
        foreignKeyConstraintName: "fk_cat_id"
    })
    category: Category
}
```

```typescript
@Entity()
export class Post {
    @ManyToMany((type) => Category)
    @JoinTable({
        name: "question_categories",
        joinColumn: {
            name: "question",
            referencedColumnName: "id",
            foreignKeyConstraintName: "fk_question_categories_questionId"
        },
        inverseJoinColumn: {
            name: "category",
            referencedColumnName: "id",
            foreignKeyConstraintName: "fk_question_categories_categoryId"
        },
    })
    categories: Category[]
}
```

**Custom PK names:**

```typescript
@Entity()
export class User {
    @PrimaryColumn({ primaryKeyConstraintName: "pk_user_id" })
    id: number
}
```
```typescript
@Entity()
export class User {
    @Column({ primary: true, primaryKeyConstraintName: "pk_user_id" })
    id: number
}
```
```typescript
@Entity()
export class User {
    @PrimaryGeneratedColumn({ primaryKeyConstraintName: "pk_user_id" })
    id: number
}
```

Fixes #1355
Fixes #4572
Fixes #8321

Closes #8524

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by EPecherkin** [comment]
Beautiful

**Comment by rstoughton** [comment]
This would be huge for my team's current migration. Much love ❤️

**Comment by ePoromaa** [comment]
Much appreciated!

**Comment by jeniasaigak** [comment]
Is there a way to pass `primaryKeyConstraintName` using `EntitySchema`?
```typescript
export const UserSchema = new EntitySchema({
  name: 'User',
  columns: {
    id: {
      primary: true,
      type: 'uuid',
      // primaryKeyConstraintName: 'PK_user_id', // <--- There is no such key 😔
    },
  },
});
```
 Thanks in advance!

**Comment by jeniasaigak** [comment]
> Is there a way to pass `primaryKeyConstraintName` using `EntitySchema`?
> 
> ```ts
> export const UserSchema = new EntitySchema({
>   name: 'User',
>   columns: {
>     id: {
>       primary: true,
>       type: 'uuid',
>       // primaryKeyConstraintName: 'PK_user_id', // <--- There is no such key 😔
>     },
>   },
> });
> ```
> 
> Thanks in advance!

Should be resolved at https://github.com/typeorm/typeorm/issues/9309
Thanks, @AlexMesser 🙏

**Pull request merged**
