### PR TITLE
perf: RelationId is too slow

### PR DESCRIPTION
**Pull request by satanTime**
When we join a lot of relations we can get 1k+ records from db even it is only 10 entities. Then when relationId are loaded the query contains too many duplciates for the same ids. The solution is to check that the relationId query fetches only unique values.

Closes: #5691

### CODE REVIEW

**Comment by satanTime** [comment]
Hi @pleerock,

the PR has been updated.

**Comment by satanTime** [comment]
Hi @pleerock, could you review the PR?

**Comment by pleerock** [comment]
Thanks for contribution!

`@RelationId` is experimental decorator - it it will be removed in the future versions. To prevent spending time on reviewing and fixing functionality that is going to be removed, I recommend you to create a separate package for this decorator and keep all code in there.

**Comment by satanTime** [comment]
Hi @pleerock, thanks for the info. Then I'll create a separate package as you suggest.

**Comment by satanTime** [comment]
Hi @pleerock,

I've started to work on the package and can't find a way how to integrate a separate package into typeorm flow.

All metadata is stored in `MetadataArgsStorage` and it doesn't allow a way how to add custom info here.
Also I didn't find hooks how to influence on query builder from outside.

In `BaseConnectionOptions` I can't see a way of adding plugins too.

Might you point me to a doc or to an example how to write a plugin / package for typeorm?

Thank you in advance.

**Comment by satanTime** [comment]
Hi @pleerock, I would like to bring this PR back and to find a way to merge it.

I need a solution for GraphQL, but with code first approach.
Unfortunately, prisma and sequelize do not solve it as typeorm does,
but the problem with typeorm is this bug.

What should be done to merge it?
If it is an experimental feature - why not to merge this PR until the feature is gone?

**Pull request closed without merging**
