### PR TITLE
filter multi empty string(s) linke ['','']

### PR DESCRIPTION
**Pull request by swfbarhr**
### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
Please provide examples of usages - what minimal code causes this issue.

**Comment by pleerock** [comment]
whats generated SQL for a given query builder expression?

**Comment by pleerock** [comment]
There shouldn't be a redundant comma between two order by-s. You need to add a test to PR profing this behavior

**Comment by swfbarhr** [comment]
> There shouldn't be a redundant comma between two order by-s. You need to add a test to PR profing this behavior

with this commit: 0410f86 we will get an error as wrong SQL like
```
SELECT DISTINCT
	`distinctAlias`.`menu_id` AS "ids_menu_id",
	`distinctAlias`.`menu_createdTime`,
	`distinctAlias`.`menu_index` 
FROM
	(
	SELECT
		`menu`.`id` AS `menu_id`,
		`menu`.`name` AS `menu_name`,
		`menu`.`parentId` AS `menu_parentId`,
		`menu`.`index` AS `menu_index`,
		`menu`.`createdTime` AS `menu_createdTime`,
		`pMenu`.`id` AS `pMenu_id`,
		`pMenu`.`name` AS `pMenu_name`,
		`pMenu`.`parentId` AS `pMenu_parentId`,
		`pMenu`.`index` AS `pMenu_index`,
		`pMenu`.`createdTime` AS `pMenu_createdTime`,
		,
		
	FROM
		`menu` `menu`
		LEFT JOIN `menu` `pMenu` ON `menu`.`parentId` = `pMenu`.`id` 
	) `distinctAlias` 
ORDER BY
	`distinctAlias`.`menu_createdTime` DESC,
	`distinctAlias`.`menu_index` ASC,
	`menu_id` ASC 
	LIMIT 10
```

**Comment by pleerock** [comment]
Okay, problem you are referencing was fixed by #8352 . Thank you for your efforts!

**Comment by swfbarhr** [comment]
> Okay, problem you are referencing was fixed by #8352 . Thank you for your efforts!

OK, thank you for your replies!

**Pull request closed without merging**
