### PR TITLE
feat: add FormattedConsoleLogger

### PR DESCRIPTION
**Pull request by hyzyla**
Add formattedConsoleLogger for pretty printing SQL queries in console

Closes: #1738

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by hinogi — APPROVED** [review]
LGTM

but one test seems to fail, maybe a connection timeout thing. Try to rerun the tests.

**Comment by hyzyla** [comment]
>  Try to rerun the tests.

I'm not sure, that I have rights to do it in CircleCI

**Comment by hinogi** [comment]
> > Try to rerun the tests.
> 
> I'm not sure, that I have rights to do it in CircleCI

That could be, but if you make another commit, I guess they will rerun.

**Comment by danyalutsevich** [comment]
@hyzyla i want this feature, why did you close this PR?

**Comment by hyzyla** [comment]
I  forgot about that PR and removed the fork by mistake. Because of that PR was closed automatically by GitHub. Feel free to reopen it using my code

**Pull request closed without merging**
