### PR TITLE
Fix compilation errors in TypeScript 4.8

### PR DESCRIPTION
**Pull request by andrewbranch**
### Description of change

TypeScript 4.8 will include stricter assignability rules for unconstrained type parameters. Our [error detection infrastructure](https://github.com/microsoft/TypeScript/issues/49461) caught several build failures in your codebase due to that change.

Nearly throughout the codebase, type parameters named `Entity` were unconstrained. However, they were usually eventually assigned to something constrained to `ObjectLiteral` which is guaranteed to be non-nullable. An unconstrained type parameter `Entity` may be instantiated with `null` or `undefined`, so this was unsafe, and TypeScript 4.8 will fix this bug. I went ahead and updated your codebase as I was investigating the real-world effects of this fix.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by andrewbranch** [comment]
I saw those errors but I thought they were unrelated—they didn’t show up as “new” in our infrastructure. I thought maybe I had something misconfigured on my end.

**Comment by andrewbranch** [comment]
It seems like the issue is the way `QueryDeepPartialEntity<T>` operates on `ObjectLiteral` (now the default for an uninferrable `Entity` type parameter).

```
{
    [x: string]: 
      | (() => string)
      | QueryDeepPartialEntity<unknown>[]
      | readonly QueryDeepPartialEntity<unknown>[]
      | QueryDeepPartialEntity<any>
      | undefined;
}
```

This recursive type only terminates on primitives (since those will simply bypass the mapped type—`QueryDeepPartialEntity<string>` → `string`) or types with a `never` index type (e.g. `unknown` or `{}`) since those will produce `{}` in the mapped type. But feeding anything with an `any` type into there creates an infinitely recursive type. That’s what’s happening with `ObjectLiteral`, though it would happen with a type like `QueryDeepPartialEntity<{ name: any }>` too. I can’t really advise what to adjust without actual knowledge of this library, but it looks like an actual underlying typing issue, not something wrong with my change. I’ll leave it to you to proceed however you see fit.

**Comment by pleerock** [comment]
Was able to fix all related errors. Thanks for the contribution @andrewbranch

**Comment by DanielRosenwasser** [comment]
Just as a heads up, there've been a few more introduced (I assume by new changes to the codebase that haven't run on TS 4.8):

   - [src/query-builder/QueryBuilder.ts#L207](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L207)
   - [src/query-builder/QueryBuilder.ts#L214](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L214)
   - [src/query-builder/QueryBuilder.ts#L222](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L222)
   - [src/query-builder/QueryBuilder.ts#L230](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L230)

**Comment by meg2208** [comment]
@andrewbranch Thanks for the response on https://github.com/microsoft/TypeScript/issues/49460. Looking deeper it seems we are using typeorm 0.2.45. That is the latest version before they moved to 0.3 and it came out March 2022. Do you think it would be possible to add a patch for typeorm 0.2 as well? Here is the error we are seeing:

```
$ yarn clean
$ rimraf ./dist
$ tsc
../../node_modules/typeorm/connection/Connection.d.ts(150,69): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/connection/Connection.d.ts(160,79): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/entity-manager/EntityManager.d.ts(318,69): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/entity-manager/EntityManager.d.ts(329,79): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/globals.d.ts(71,119): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/globals.d.ts(83,129): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/repository/AbstractRepository.d.ts(41,70): error TS2344: Type 'T' does not satisfy the constraint 'ObjectLiteral'.
../../node_modules/typeorm/repository/TreeRepository.d.ts(10,64): error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.
```

**Comment by andrewbranch** [comment]
That would need to be initiated by the maintainers of this project (@pleerock I assume). Happy to advise on TypeScript issues, but I’ve never used typeorm and don’t really know what it is, much less the procedure for initiating a backport to an older version. I opened this PR just to try to be helpful when our infrastructure noticed it was going to be broken in a future TS version.

**Comment by notaphplover** [comment]
@andrewbranch I totally agree.

@pleerock pls consider https://github.com/typeorm/typeorm/issues/9331 as an existing issue relating to this topic :smiley:

**Comment by pleerock** [comment]
@meg2208 `0.2.x` isn't maintained anymore. You have two options:

* migrate to `0.3.x`
* fork `0.2.x` version you are using, fix typescript compiler issues, publish new npm version under your npm account

**Comment by regevbr** [comment]
> Just as a heads up, there've been a few more introduced (I assume by new changes to the codebase that haven't run on TS 4.8):
> 
> * `error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.`
>   
>   * [src/query-builder/QueryBuilder.ts#L207](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L207)
>   * [src/query-builder/QueryBuilder.ts#L214](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L214)
>   * [src/query-builder/QueryBuilder.ts#L222](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L222)
>   * [src/query-builder/QueryBuilder.ts#L230](https://github.com/typeorm/typeorm/blob/bb33cd0f23d566c0d87fcb57e42bd611761cc106/src/query-builder/QueryBuilder.ts#L230)

I fixed those in #9357 waiting for it to be merged

**Pull request merged**
