### PR TITLE
chore(build): enable mssql on travis

### PR DESCRIPTION
**Pull request by vlapo**
Lets try travis with mssql. I want to see travis build and try rerun few times if it is stable.

### CODE REVIEW

**Comment by amaranth** [comment]
It looks like this passed but something went weird with the test run on node 10 and it timed out.

**Comment by vlapo** [comment]
Yeah, there is issue with mssql driver. Issue is reported and we are waiting to resolve. Will see in few days :-)

**Comment by pleerock** [comment]
@vlapo can you please provide more info - where issue is reported? btw, today I added CircleCI config, so we can also try to setup it as well.

**Comment by vlapo** [comment]
I think there is problem with unclosed connections in pool. Issue in mssql driver https://github.com/tediousjs/node-mssql/issues/457 and in node-pool library https://github.com/coopernurse/node-pool/issues/159.

The latest mocha do not exit properly if there are unclosed connections or resources. There is simple workaround - adding `--exit` flag for now by I hope issue will be resolved soon.

Note: Just do not know why is this issue only with node v10.

**Comment by dhensby** [comment]
1. You need to close your connection pools
2. You can use the `--exit` flag if you want the old mocha behaviour of terminating processes once all the test callbacks are complete.

**Comment by vlapo** [comment]
1. Yeah I see problem in typeorm code. We do not wait until connection pool is closed in SqlDriver. But I fixed this locally and have same issue with mocha.
2. Sure we know about this possibility but its just a workaround not solution of problem :)

I still thinks that problem is in `node-pool` library. Lets wait to fix and see if it will be help.

**Comment by dhensby** [comment]
@vlapo are you able to track down what connections are left open that are preventing the process from exiting?

I found for my test suites that maintaining a good record of connections and closing them was the solution, I didn't find any underlying issue with `node-pool`

**Comment by vlapo** [comment]
Have a logs provided in `node-mssql` issue:
```
pool(1): connection #3 created
connection(3): establishing
pool(1): connection #4 created
connection(4): establishing
connection(2): borrowed to request #115
request(115): query SELECT ...
connection(2): released
request(115): completed
connection(2): borrowed to request #116
request(116): query SELECT ...
connection(2): released
request(116): completed
connection(2): borrowed to request #117
request(117): query SELECT ...
connection(2): released
request(117): completed
    ✓ should be able to retrieve the whole tree (313ms)
====> before close
====> after close
connection(3): established
connection(4): established
connection(2): destroying
connection(2): destroyed
connection(3): destroying
connection(3): destroyed
```
As you can see there is established connection no. 4 and never destroyed. But this behaviour is not occur every time. In our large test suites it is almost every time but in different tests.

I provided failing test case in `node-pool` and it seem like race condition. Maybe I am totally wrong. Will see.

**Comment by vlapo** [comment]
@dhensby We have a some progress here. https://github.com/coopernurse/node-pool/issues/159#issuecomment-459970428 I tested it on my local environment by replacing `generic-pool` sources in `mssql` package and it works like a sharm. No hanging DB connections anymore.

**Comment by dhensby** [comment]
Let me update the deps on mssql, then :)

**Comment by vlapo** [comment]
We are all green 💯 🔥 🎉  @dhensby, @sandfox thank you for your effort 🍺

**Comment by pleerock** [comment]
Thank you guys!

@vlapo do we use any api of new mssql that doesn't exist in 4.x? (Is it a breaking change for exist mssql users with 4.x installed?)

**Comment by dhensby** [comment]
I can release a 4.x update too, if you like - the change log for 5 is in the mssql repo - there is 1 config change that is different (forced on us by upgrading tedious version) but otherwise tried to keep everything BC

**Comment by dhensby** [comment]
4.3.1 tagged too :)

**Comment by vlapo** [comment]
ok, lets use stable 4.3.1 version instead 5.0.0-beta :-)

**Pull request merged**
