### PR TITLE
fix README link to docs

### PR DESCRIPTION
**Pull request by calebx**
https://github.com/typeorm/typeorm/pull/4928
this should work

### CODE REVIEW

**Comment by jayarjo** [comment]
Chinese docs have to be fixed as well.

**Comment by calebx** [comment]
@jayarjo yeah.
it could make the html page happy.
while, in https://github.com/typeorm/typeorm/blob/master/README-zh_CN.md github readme file.
those links would redirect to EN version. and that is an issue for all link there. 
I'd keep it still since that README is for page only.

**Comment by pleerock** [comment]
It's still seems to be broken. Can you please check how do we do it in other places? Also, we need to make sure that links are working from both site and github when you click the link from the github site.

**Comment by pleerock** [comment]
okay so as was mentioned it was a site parser issue. Fixed in https://github.com/typeorm/typeorm.github.io/commit/2b6a05432eafa7f750023087a4216a37413585b2

**Comment by calebx** [comment]
👍

**Pull request merged**
