### PR TITLE
WIP: Feature(Tests\Functiona): UUUID tests for MongoDB

### PR DESCRIPTION
**Pull request by ovr**
Hey! I am having a problem with 

```
@Column()
@Generated("uuid")
myAwesomeField: string;
```

on MongoDB, it's not working / I am trying to prepare tests for it

Thank

### CODE REVIEW

**Comment by pleerock** [comment]
hey, this feature is only working in rdbms databases (dbs with uuid column type support)

**Comment by ovr** [comment]
@pleerock But Why We cannot genreate it on client side instead of database (for example by https://github.com/kelektiv/node-uuid or another)? Thank

**Comment by pleerock** [comment]
oh I found out that @AlexMesser already generates uuid manually for databases which do not support uuid. Probably we can do that for mongodb. Feel free to contribute.

**Comment by Kononnable** [comment]
@ovr Are you still interested in that PR? It's marked as WIP for a very long time.

**Comment by imnotjames** [comment]
Given that this has been marked as a WIP I'll be closing this.  When you've got it ready to review again please feel free to re-open a new PR!

**Pull request closed without merging**
