### PR TITLE
Fix table name in `deleteExecutedMigration`

### PR DESCRIPTION
**Pull request by vados-p7e**

### CODE REVIEW

**Comment by vados-p7e** [comment]
```
  1) github issues > #1259 Can't sort by fields added with addSelect should order by added selects when pagination is used:

     QueryFailedError: syntax error at or near ","

      at new QueryFailedError (build/compiled/src/error/QueryFailedError.js:9:2673)

      at Query.<anonymous> (build/compiled/src/driver/postgres/PostgresQueryRunner.js:9:18170)

      at bound (domain.js:280:14)

      at Query.runBound (domain.js:293:12)

      at Query.handleError (node_modules/pg/lib/query.js:143:17)

      at Connection.connectedErrorHandler (node_modules/pg/lib/client.js:132:26)

      at Socket.<anonymous> (node_modules/pg/lib/connection.js:118:12)

      at addChunk (_stream_readable.js:265:12)
```

This is the failing check in Travis and doesn't seem to be related to the change I made...

**Comment by pleerock** [comment]
Thank you for the fix, I'll take a look why tests are failing

**Comment by vados-p7e** [comment]
Thank you for the maintenance and contributions!

**Comment by pleerock** [comment]
Don't forget to star a library 😆

**Comment by vados-p7e** [comment]
Oh yeah, I can't believe I forgot! thanks again!

**Pull request merged**
