### PR TITLE
feat: export all errors

### LINKED ISSUE #7000: Export error types for checks on the outside
### The Problem

We use NestJS with the TypeOrm integration and try to catch TypeOrm errors with a NestJs-Filter. Unfortunatley only the `QueryFailedError` is exported from the TypeOrm-Library. This stops us from being able to check something like `error instanceOf EntityNotFoundError`. Worse, we cannot specify this error as part of the `Catch` clause from NestJS.

### The Solution

Export all errrors. 

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by Agreon**
### Description of change

This PR adds the export of all errors.

Fixes #7000

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rubiin** [comment]
@imnotjames can have this in next realease, most awaited feature for me

**Review by imnotjames — COMMENTED** [review]
Instead of exporting each of these individually in the `src/index.ts`, would it be clearer to create an `index.ts` in `error` which iterates through them?

That way we could do `export * from "./error"` and isolate the error export iteration to the error dir.

What do you think?

**Comment by Agreon** [comment]
That's a good idea an i had it myself, i just oriented myself on the existing code to stay consistent. But of course, will do it in a second

**Comment by Agreon** [comment]
@imnotjames ping!

**Comment by rubiin** [comment]
I think this pr can be merged if there are no any alterations to be made

**Comment by Agreon** [comment]
Why is this not merged? It's not even hard to review :/

**Comment by rubiin** [comment]
@imnotjames little help here

**Comment by nebkat** [comment]
There is still the unresolved conversation in #6909. Personally I think the classes should all be exported but there may be reasons not to, for example avoiding creating a public API that will later result in breaking changes if the errors are renamed.

Either way it's not being ignored, pleerock has just not gotten around to all the pending pull requests and there are many others waiting too. If you need it I suggest making a local repo with the changes applied and using `npm link`.

**Comment by pleerock** [comment]
I don't think errors should be part of public API and I don't really like how errors are currently designed, but we can merge this PR if somebody needs it.

**Comment by pleerock** [comment]
Thank you for contribution! Please keep in mind in the future we most probably will change errors public api.

**Pull request merged**
