### PR TITLE
Tests for issues #1989 and #1993 

### PR DESCRIPTION
**Pull request by filipjnc**

### CODE REVIEW

**Comment by pleerock** [comment]
Thank you, glad to see your first PR on github!

Can you please minimize test as much as possible (remove everything that is not related to the issue), so we can cut down until we find a source of problem.

Also, can you please make exactly the same style as other tests? I mean use same create connection syntax and everything else, e.g follow this pattern: 

```ts

describe("github issues > #...", () => {

    let connections: Connection[];
    before(async () => connections = await createTestingConnections({
        entities: [...]
    }));
    beforeEach(() => reloadTestingDatabases(connections));
    after(() => closeTestingConnections(connections));

    it("fail #1", () => Promise.all(connections.map(async connection => {
// ...
    })));

    it("fail #2", () => Promise.all(connections.map(async connection => {
// ...
    })));

});

```

**Comment by filipjnc** [comment]
@pleerock I splitted and striped-down the tests and updated them according to your suggested format. I followed the guide on how to run tests locally but unfortunately my VSCode hangs when I try to to npm test:
```
> tsc && mocha --file ./build/compiled/test/utils/test-setup.js --bail ./build/compiled/test/**/*.js --timeout
30000 --color
```
I hope you can still reproduce on your local!

**Comment by Knockdown26** [comment]
is there a good reason that this PR is still open? is the @filipjnc are you still working on this PR?

**Comment by filipjnc** [comment]
@Knockdown26 this can be closed.

**Pull request closed without merging**
