### PR TITLE
Improve conditional where (andWhere / orWhere)

### PR DESCRIPTION
**Pull request by jojoldu**
### Description of change

Suggest a new method for conditional where queries that were previously discussed(https://github.com/typeorm/typeorm/issues/3103).

If null is received, the corresponding `andWhere` / `orWhere` condition is not added to the conditional statement.

Querydsl library of JAVA language supports similar type.
So there is no big burden to actually make a dynamic query.

```java
// Querydsl)

query.from(customer)
     .where(
         isFirstNameLike(customerQueryInfo.getFirstName()), // if null return then erased condition
         isLastNameLike(customerQueryInfo.getLastName()),
         isStatusEq(customerQueryInfo.getStatus()))
     .list(customer);

private BooleanExpression isFirstNameLike(String firstName){
    return firstName != null ? customer.firstName.like(firstName) : null;        
}

private BooleanExpression isStatusEq(StatusEnum status){
    return status != null ? customer.status.eq(status) : null;
}

```
* https://stackoverflow.com/a/12287074

In typeORM, can use it like this:

Expect the following code.

```javascript
    findAllByDto (dto: ArticleSearchDto) {
        return createQueryBuilder()
            .select("article")
            .from(Article, "article")
            .andWhere(this.eqTitle(dto.title)) // or title? `article.title = :${title}` : null;
            .orderBy("article.id desc")
            .getMany();
    }
  
   // erase or andWhere
    private eqTitle(title: string): string {
        if(!title) {
            return null;
        }

        return `article.title = :${title}`;
    }
```

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by michaelzangl** [comment]
I don't like this idea - if you don't want to add a condition, just don't add it. Just ignoring the addition is an error that is really hard to spot in production.

**Comment by imnotjames** [comment]
The example in your PR is a SQL injection threat.

Can you include the examples you pulled this from?  (Ideally 3 from varying DSLs)

My biggest concern with builders like these is the confusing order of operations.

**Comment by imnotjames** [comment]
Also, to make this more explicit, I think we should - if ever - implement it similar to laravel's `when`.

This implementation makes it very easy to unintentionally omit a `where` clause.

**Comment by AlexMesser** [comment]
Duplicate of #7455 and closing for the same reason:

> This is redundant. We can't continue extending query builder functionality to fit all user demands. You can simply use "if" statement to do same without any changes in the codebase.

**Pull request closed without merging**
