### PR TITLE
fix unknown column error when using relationCount

### PR DESCRIPTION
**Pull request by ruiming**
This pr fix this issue: #772 

I am not familiar with SQL and I do not know whether this change will break something. But this change work for me which solve above issue.

### CODE REVIEW

**Comment by pleerock** [comment]
Relation count currently is almost completely broken functionality. I don't recommend you to use it. TBH I think to remove this functionality at all because of value, complexity and issues it brings

**Comment by ruiming** [comment]
That is a little pity for me because I think `RelationCount` is very powerful and easy to use.

For example, calculate how many people like&comment this article&comment. Without `RelationCount`, I need to always join it manually which brings more code.

Before this being removed, can this pr be merged first in order to fix that issue? I did not find any other questions when using `RelationCount` except the above issue.

**Comment by pleerock** [comment]
Then can you tell me how exactly this change (counting exact column vs *) fixes your issue? I need to understand what exactly your issue is and if your change really fixed root cause of issue

**Comment by ruiming** [comment]
The problem is described in this issue #772 . 
The point is that the exact column to be counted is not existed in that table in the example that issue had described. So I change it to `count(*)` which can work fine and get the result exactly I want.

**Comment by pleerock** [comment]
Okay I'll merge it. However Im not sure if its correct fix. I think problem is in "referencedColumn". It uses original entity id instead of target entity ids. I think proper fix would be to count there multiple primary keys. And, again, I recommend not to use relation count functionality

**Pull request merged**
