### PR TITLE
check for referencing foreign keys when altering a table using sqlite

### PR DESCRIPTION
**Pull request by hielkehoeve**
As described in issue #2576 TypeORM did not take into account whether tables have data and foreign constraints to the given table.

I have created a testcase to illustrate the situation.

### CODE REVIEW

**Comment by dominicdesu** [comment]
Looks like this would also fix #2584 !?

**Comment by hielkehoeve** [comment]
...

**Comment by pleerock** [comment]
looks like CI is failing?

**Comment by hielkehoeve** [comment]
It is. However this is not in the testcase I introduced but in `schema builder > change check constraint`...

**Comment by pleerock** [comment]
no, its not that hard. You can ask people for help in slack if you stuck somewhere. You have to do that because tests are failing because of you changes and you need to check what and why you have broke and fix that.

**Comment by imnotjames** [comment]
I'm gonna close this as it's failing, has conflicts and has not been updared in a few years

**Pull request closed without merging**
