### PR TITLE
doc: roadmap - remove stable release date temporarily

### PR DESCRIPTION
**Pull request by gtpan77**

### CODE REVIEW

**Comment by pleerock** [comment]
Thank you!

**Comment by gtpan77** [comment]
Thanks @pleerock, I am just starting off in open source. I'd like to contribute more in typeorm. Would you like to guide me where I can start as a beginner?

**Comment by gtpan77** [comment]
@pleerock, can you please add `hacktoberfest-accepted` label to this PR.

**Comment by pleerock** [comment]
@gtpan77 join our slack group where you can ask more about what features are currently good to have / in priority to do

**Comment by gtpan77** [comment]
Thanks, Joined slack.

**Pull request merged**
