### PR TITLE
proper oracle offset limit fix

### PR DESCRIPTION
**Pull request by hajekj14**
Fixed createLimitOffsetOracleSpecificExpression method which did bad results.

### CODE REVIEW

**Comment by hajekj14** [comment]
@pleerock  @AlexMesser is everything Ok with this PR?

**Comment by pleerock** [comment]
@hajekj14 I think you'll have to wait with this PR since there are already lot of oracle-related changes in @AlexMesser [branch](https://github.com/typeorm/typeorm/tree/schema-builder-refactoring). Maybe this even was fixed there (would be great if you are able to build and test his branch).

**Comment by hajekj14** [comment]
@pleerock Yeah, in @AlexMesser branch it is fixed, but not for Oracle lesser then v12. I thik its Ok because we upgrade our DB soon. Thanks.

btw.: when it will be release of @AlexMesser branch?

**Comment by pleerock** [comment]
we are planning to do it end of February. This branch contains lot of oracle fix, not only this issue.

**Comment by pleerock** [comment]
@hajekj14 are you able to test latest `@next` which contains all oracle related fixes?

**Comment by hajekj14** [comment]
@pleerock yes, I will test it until the end of week.

**Comment by hajekj14** [comment]
@pleerock Sorry but I have bad news, I strated testing and found out our development Oracle is still v11. I solving this with admins. Stay tuned, I will let you know.

**Comment by pleerock** [comment]
I close it for now. Please let me know if you still want something to add.

**Pull request closed without merging**
