### PR TITLE
no-repository-for-XEntity-was-found

### PR DESCRIPTION
**Pull request by phong-innomizetech**
Adding condition once entity and target have typed is a function

### CODE REVIEW

**Comment by millsmcilroy** [comment]
@phong-innomizetech This is ultimately a revert of this revert: https://github.com/typeorm/typeorm/pull/5486. This change would end up breaking things again that were just fixed for people like this guy: https://github.com/typeorm/typeorm/issues/4958#issuecomment-594092242.

**Comment by seandearnaley** [comment]
@millsmcilroy are there any guidelines for resolving this RepositoryNotFound message, I understand that the update fixed something for some people but it has broken things for people like me and I can't see how to address it: https://github.com/typeorm/typeorm/issues/5592

**Comment by millsmcilroy** [comment]
@seandearnaley Are you running in a serverless environment? If so, this might be an environment issue and not a code issue, one of which has a solution in this thread https://github.com/typeorm/typeorm/issues/3427#issuecomment-549770047. If not, it would be great to have a reproducible example. Introducing changes like this without tests to back them up just adds more even more fragility to a project as complex as this one.

**Comment by seandearnaley** [comment]
@millsmcilroy , the tests fail with the new version on my ubuntu desktop, I don't really see anything special about my test suite, this must be affecting others-- you can see it for yourself here: https://github.com/seandearnaley/brainstrike-typescript-starter/tree/master/server , just pull and upgrade to .24, it'll start failing with yarn test

**Comment by seandearnaley** [comment]
@millsmcilroy , @YoonSeongKyeong has done some work to resolve this, could you take a look at his code on: https://github.com/typeorm/typeorm/issues/5592#issuecomment-600077109 , I'm not sure if it's a similar issue or not.

**Comment by OliverLeighC** [comment]
My coworker just updated typeorm today and we are getting this same error. Code has not changed at all, in fact my git branch is still on the older typeorm version and I'm not getting this error. We are not running it in a serverless environment.

**Comment by seandearnaley** [comment]
@millsmcilroy , note this issue has been reported by many users now:  https://github.com/typeorm/typeorm/issues/5587 , https://github.com/typeorm/typeorm/issues/5676 , https://github.com/typeorm/typeorm/issues/5592

**Comment by rpeg** [comment]
I just wanted to point out that as of right now, no version of typeorm is compatible with Expo SDK 36. .23 and .24 have the repo bug, .22 fails due to a node std lib dependency, and .21 has an issue with SDK 36's new sqlite API.

**Comment by YoonSeongKyeong** [comment]
```javascript
Object.getPrototypeOf(metadata.target) === Object.getPrototypeOf(target)&&metadata.target.name===target.name
```
This condition is more acceptable. because original PR have crash when it allow the non-related function with same name in accident. The condition only check if target is function and name is the same

**Comment by davecarlson** [comment]
@pleerock - is there an for fixing this? it seems to be stopping a lot of people ( myself included ) from moving past 0.2.22

**Comment by lmiller1990** [comment]
I had this problem when upgrading to Node 14. I downgraded to Node 12 (which is LTS) and it worked.

**Comment by imnotjames** [comment]
Thanks for the contribution!  This is indeed basically a revert of #5486 - and would cause new problems instead even if it would fix this one case.

Given that this change only handles a subset of cases and breaks existing working cases in going to be closing this PR as we work towards a more suitable solution.

**Comment by imnotjames** [comment]
I'm going to rebase this

**Pull request closed without merging**
