### PR TITLE
Fix Caching won't work with replication enabled

### LINKED ISSUE #5919: ⚠Caching won't work with replication enabled
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi everyone, I've configured typeorm with replication using two instances, a master(read-write) and a slave(read), so if my understading is correct all the select/get queries are executed in the slave instance and all the updates/set/insert/etc are executed in the master db but today I've enabled caching for my db and it doesn't work, it shows the following error when I try to get something from the db:

`{ error: cannot execute INSERT in a read-only transaction
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 118,
  severity: 'ERROR',
  code: '25006',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'utility.c',
  line: '246',
  routine: 'PreventCommandIfReadOnly' }
`

I suppose that this is being caused when a get request is received on my API and then typeorm selects the slave database in order to execute the query and then it tries to do a `INSERT`  to chache the results using the slave instance and because it is `READ ONLY` it throws that error, so I guess that this is a bug, correct me if I'm wrong, thanks in advance!

### PR DESCRIPTION
**Pull request by madeindjs**
Fix #5919 

### Description of change

I just added a new method `QueryRunner.getReplicationMode` to check if we can insert cache into `DbQueryResultCache.storeInCache`. If query runner is in slave mode, we create a new one in master mode

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x]  `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change N/A
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by imnotjames** [comment]
Adding extra API surface area & exposing more internal details kinda seems.. well, a bit over-kill for a feature that shouldn't be so tightly wound up in TypeORM anyway.

I think it'd be reasonable for `DbQueryResultCache` to just create a new query runner instead.  I'd just need to confirm it resolves the issue.

**Comment by madeindjs** [comment]
@imnotjames , to be sure to have understood correctly, you propose:

1. remove `BaseQueryRunner.getReplicationMode` that I added
2. in `DbQueryResultCache.storeInCache`, remove `queryRunner` options and always create a new `queryRunner` inside

**Comment by imnotjames** [comment]
> @imnotjames , to be sure to have understood correctly, you propose:
> 
> 1. remove `BaseQueryRunner.getReplicationMode` that I added
> 2. in `DbQueryResultCache.storeInCache`, remove `queryRunner` options and always create a new `queryRunner` inside
> 
> 

Yes.  Would that cause much overhead to create a new query runner, you think?

I feel like it's the most consistent.  You'd just need to release the query runner afterwards in a finally block.

**Comment by madeindjs** [comment]
I do not think this is a good idea because:

1. `queryRunner`is passed everywhere. If I remove it from `storeInCache`, I should do it also on theses methods to be consitent
~~~diff
export interface QueryResultCache {
    connect(): Promise<void>;
    disconnect(): Promise<void>;
-   synchronize(queryRunner?: QueryRunner): Promise<void>;
+   synchronize(): Promise<void>;
    getFromCache(options: QueryResultCacheOptions, queryRunner?: QueryRunner): Promise<QueryResultCacheOptions|undefined>;
-   storeInCache(options: QueryResultCacheOptions, savedCache: QueryResultCacheOptions|undefined, queryRunner?: QueryRunner): Promise<void>;
+   storeInCache(options: QueryResultCacheOptions, savedCache: QueryResultCacheOptions|undefined): Promise<void>;
    isExpired(savedCache: QueryResultCacheOptions): boolean;
-   clear(queryRunner?: QueryRunner): Promise<void>;
+   clear(): Promise<void>;
-   remove(identifiers: string[], queryRunner?: QueryRunner): Promise<void>;
+   remove(identifiers: string[]): Promise<void>;
}
~~~
2. if we pass a `queryRunner` from a transaction, this will imply that cache will be stored before transaction commit. Even if we use a master `queryRunner`

What do you think about it?

**Comment by imnotjames** [comment]
> if we pass a queryRunner from a transaction, this will imply that cache will be stored before transaction commit. Even if we use a master queryRunner

This is happening anyway with the code you're suggesting in the case of using a replica.

I almost think we shouldn't fix this at all is that's a concern and instead cause DBResultCache to bail out if you're trying to use it with any sort of replication enabled.

**Comment by madeindjs** [comment]
> This is happening anyway with the code you're suggesting in the case of using a replica.

Not necessary if the user use a `querRunner` from a transaction on `master` server.

> instead cause DBResultCache to bail out if you're trying to use it with any sort of replication enabled.

I don't think so. Currently, I have an application on a production environment I want to scale with Postgres replication but I want to keep the cache system.

But if you ok with [modifications I proposed on `QueryResultCache`](https://github.com/typeorm/typeorm/pull/7694#issuecomment-862225392), I can give it a try and update this PR. What do you think about it?

**Comment by imnotjames** [comment]
> > This is happening anyway with the code you're suggesting in the case of using a replica.
> 
> Not necessary if the user use a `querRunner` from a transaction on `master` server.

Which is why I said in the case of using a replica which is 99% of the time when you're caching.

> 
> > instead cause DBResultCache to bail out if you're trying to use it with any sort of replication enabled.
> 
> I don't think so. Currently, I have an application on a production environment I want to scale with Postgres replication but I want to keep the cache system.

You would be really better off building your own caching mechanism if you need specific code paths.

Also, if you're selecting in the middle of a transaction you maybe shouldn't be caching that value - because then you'd be getting the data from before your operations.  The whole point would be that you know changes have been made.

> 
> But if you ok with [modifications I proposed on `QueryResultCache`](https://github.com/typeorm/typeorm/pull/7694#issuecomment-862225392), I can give it a try and update this PR. What do you think about it?

I think the optimal solution would be to omit query runner's use in the built-in implementation and mark those field as deprecated in the interface but still pass them to the interface.

That would give folks time to migrate away from it for their own implementation.

Then at a later date we can remove these.  Otherwise everyone gets very grumpy. 😄 I mean, understandably.

**Comment by pleerock** [comment]
Okay so here I think you both have valid points @madeindjs  and @imnotjames just different opinions.

If you ask me,

* I'm okay with new `getReplicationMode()` function, it doesn't bring something complex and logically makes sense to be part of QueryRunner

* I'm okay with proposed solution on using given query runner or create new one if needed.

here @imnotjames is right because in scaled app most of times queries will be served by read replicas and having this check doesn't make much sense. However, in specific user scenarios, when for example he opens complex transaction with saves and queries, it will be better to keep using given query runner in the case if transaction fail (e.g. data was inserted, "finds" executed, "cached" in a separate connection, but then transaction fails and we have no data inserted, but we do have data in the cache).  

* if user wants to use db cache for production, that's completely fine. Yes maybe it's not the most performant solution, but its the most performant from simplest solutions. And since we have such solution, and this bug makes this solution unusable - I think we need to fix it.

I'm good with this PR, we just need to fix conflicts.
Sorry for late review.

**Comment by madeindjs** [comment]
Great @pleerock . I currently [use this branch on production](https://www.npmjs.com/package/@optimiz.me/typeorm) since june. So I'll try to correct conflicts as soon as possible.

**Comment by madeindjs** [comment]
@pleerock , I just resolved conflicts.

**Comment by pleerock** [comment]
Thank you for contribution! 🎉

**Pull request merged**
