### PR TITLE
Fixed missing import/export in FindOneOptions, JoinOptions

### PR DESCRIPTION
**Pull request by bartlomiej-korpus**
Fixes issue #501

### CODE REVIEW

**Comment by Lesspion** [comment]
Any news why the travis failed for the node v5 ?

**Comment by AndyBarron** [comment]
https://travis-ci.org/typeorm/typeorm/jobs/236692225

Looks like it might have just flaked out?

**Comment by pleerock** [comment]
before merging, one question what version you were using?

**Comment by AndyBarron** [comment]
0.1.0-alpha.3 here.

**Comment by alfaproject** [comment]
Same as @AndyBarron

**Comment by erikakers** [comment]
I tried 0.1.0-alpha.1 and 0.1.0-alpha.2 and had the same issue.

**Comment by pleerock** [comment]
thx

**Comment by alfaproject** [comment]
@pleerock is there any chance you can make an `alpha.4` version available on `npm`. Even if it only has this fix? I really want to use the new locking stuff, but this is blocking me. ):

**Comment by AndyBarron** [comment]
Yeah, a patch release would be great; I'm currently vendoring typeorm into my repository...

**Comment by pleerock** [comment]
I made `0.1.0-alpha.4` release with this change.

**Pull request merged**
