### PR TITLE
feat(query-builder): Allow WHERE clause on joined columns #2707

### LINKED ISSUE #2707: Allow WHERE clause on joined columns.
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

Hi!

As it said in the documentation of `FindManyOptions#where`:
> Querying a column from an embedded entity should be done with respect to the hierarchy in which it was defined.

It is possible to extend this capability to the joined columns ?

For exemple with 2 entities:
```TypeScript
@Entity()
class Contact {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  name: string;
  @ManyToOne(type => Address)
  address: Address;
}

class Address {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  street: string;
  @Column()
  city: string;
}
```

Make  a request like this:
```TypeScript
contactRepository.find({
  relations: [ 'address' ],
  where: {
    address: {
      city: 'Paris'
    }
  }
});
```

SQL:
```SQL
SELECT `Contact`.`id` AS `Contact_id`
    `Contact`.`id` AS `Contact_id`
    `Contact`.`name` AS `Contact_name`
    `Contact`.`addressId` AS `Contact_addressId`
    `Contact_address`.`id` AS `Contact_address_id`
    `Contact_address`.`street` AS `Contact_address_street`
    `Contact_address`.`city` AS `Contact_address_city`
  FROM `contact` `Contact`
  LEFT JOIN `address` `Contact_address`
    ON `Contact_address`.`id` = `Contact`.`addressId`
  WHERE `Contact_address`.`city` = "Paris";
```

I don't have seen any other options in TypeORM documentation to apply where clauses on joined columns. If there another way I am interested about it.

Thank you in advance for your help.

### PR DESCRIPTION
**Pull request by mtwzim**
### Description of change
Hello, my name is Matheus and this pull requets Fixes #2707 which has been open for almost 3 years, the code is capable of reproducing all the situations mentioned in the comment: https://github.com/typeorm/typeorm/issues/2707#issuecomment-748011818
Regarding the verification of tests I created a new test that is available in the folder `/test/github-issues/2707`, these tests also consider all the scenarios mentioned in the comment above.

One last PR that I created (#7522) was going wrong and the files were disappearing, so I recreated that PR.

See you later!

PS: Sorry for my English, I am not fluent.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #2707 `
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mtwzim** [comment]
Ok, it looks like the oracle test fails, I'll see what the cause is and how I can fix it.

The other 2 tests that failed seem to be problems with the circle ci.

Am I right?

**Comment by tbarusseau** [comment]
@mtwzim Yes, it seems that two tests failed for reasons that are not related to your code

**Comment by csabaxyz** [comment]
@AlexMesser this is empty just as last time. Why did you merge it?

**Comment by AlexMesser** [comment]
I merged my own PR #7561 and your PR merged somehow too.

**Comment by AlexMesser** [comment]
@csabaxyz I think the pull-bot doing something wrong.

**Comment by mtwzim** [comment]
Again: (
@AlexMesser What can I do to prevent this from happening?
Now I have to open a new PR again...

**Comment by vensauro** [comment]
the pull bot "removed" the changes, because of conflict
maybe this is a pull with force?
and the head of this fork the same of the project (with the pull), thus is "merged" with master

**Comment by giyyapan** [comment]
Hi, is any one working on this now? Looking forward to see this PR merged.

**Comment by vensauro** [comment]
> Hi, is any one working on this now? Looking forward to see this PR merged.

this will not be merged, check the details of the issue #2707

**Comment by vensauro** [comment]
> Hi, is any one working on this now? Looking forward to see this PR merged.

this will not be merged, check the details of the issue #2707

**Comment by mtwzim** [comment]
In the last few weeks I've been very busy and I couldn't continue this implementation, however in the next few days I plan to come back and continue the implementation (if someone doesn't do it before)

**Comment by dahlmo** [comment]
I'm a bit confused, I've found two different pull requests (#7535 and #7522) that both seems empty but the related issues for each of them are closed. Are the changes tracked somewhere else? Unfortunately I couldn't find any commit contents or anything searchable so I'm forced to ask (I think)

**Comment by phil294** [comment]
@dahlmo I also don't understand what became of @mtwzim's PRs or why his works seems to have been disregarded (??).

However, there has been another merged PR by james at #7805 which now allows WHERE queries on joined `*toOne` columns. There's also a lot more details about this to be found at #2707

**Comment by mtwzim** [comment]
Hello!!!  Well, my pull request is empty because the pull bot sent the changes to my repository, as my pull request is from master to master happened, anyway, my pull request didn't meet all the requirements, see: https ://github.com/typeorm/typeorm/issues/2707#issuecomment-813798990

**Comment by dahlmo** [comment]
> I think that until recently I used typeorm in a project with these changes, so if you want I can update this pull request, create a new pull request or create a fork for you to test

That would be awesome @mtwzim, a new pull request would probably be the best in order to benefit as many as possible. It might also solve the bounty on #2707 👍

**Comment by dahlmo** [comment]
Sorry I see that the bug bouny is already claimed @mtwzim, but hope you still wanna have a go at it regardless ! If you could do a PR it would be awesome, but would also be of great help if you could share the working implementation that you mentioned was working in your other project – then I might be able to do a PR for it as well if you'd prefer (with you as a co-author ofc.)

**Comment by dahlmo** [comment]
Taking the liberty to mention you one last time @mtwzim just in case you're still willing and able to share the working implementation, it would be a huge time saver if so 🙌  Thanks in advance in that case

**Pull request merged**
