### PR TITLE
test: the column that has a default definition

### PR DESCRIPTION
**Pull request by rianby64**
In order to expose this case, I modified the interface ```TestConnection``` in order to allow to run migrations.

After running the migrations, the following is to catch the case when a field that is defined to have a default value, must be present in the object returned by calling ```save```. That field should behave as behaves the field ```id```.

Related to #2756

### CODE REVIEW

**Comment by imnotjames** [comment]
Can this instead be done by calling the migration executor programmatically?  Instead of calling it on the configured connection?

**Comment by rianby64** [comment]
Yeap... Let met think about it.

**Comment by imnotjames** [comment]
You actually don't need to modify any of this - it's possible to use migrations in tests without changing anything

https://github.com/typeorm/typeorm/blob/2f275816375a58c9ad136d5f02dc3508797152c2/test/github-issues/4697/issue-4697.ts#L25

**Comment by rianby64** [comment]
Hey, @imnotjames I moved the code to its correspondent directory.
Hope this change will reflect the error I mentioned in the issue #2757 .

**Comment by rianby64** [comment]
@imnotjames finally I got the error running. Please, take a look.

**Comment by imnotjames** [comment]
I switched up the `empty` check with a `defined` check and it passes.

Something's up with negating chai's `empty` check, I think.

**Comment by imnotjames** [comment]
Tests passed with that.  Cannot replicate.

**Pull request closed without merging**
