### PR TITLE
feat: added option flag to skip column type normalization for postgres

### PR DESCRIPTION
**Pull request by pmdroid**
### Description of change
The idea of the change ti allow generation of table schema without column name normalization is that it allows to generate schema for databases where you want to use a strict column type. This change only is made currently for postgres but could be added to other database driver as well if needed.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
can you please explain what do you call a `strict column type` and provide a few examples? So, I can better understand motivation of this feature request. Thank you!

**Comment by pmdroid** [comment]
@pleerock sure! we want to use typeorm to create redshift database tables, for example with datatypes like "DOUBLE PRECISION" for this we need the column type normalization to be skipped

**Comment by pleerock** [comment]
I'm trying to understand **why** you want to skip column type normalization. Can you please provide more details and examples if possible?

**Review by imnotjames — CHANGES_REQUESTED** [review]
This needs tests

**Comment by imnotjames** [comment]
Given there's no tests that confirm this behavior & your example is possible today I'll be closing this issue.

**Pull request closed without merging**
