### PR TITLE
feat: modify repository.extend method (for chaining call!)

### PR DESCRIPTION
**Pull request by hunjin-choi**
### Description of change

 I want to use repository.extend method like this.
`const customUserRepository = entityManager.getRepository(User).extend({~~}).extend({~~~~}).extend({~~~~~});
`
So I upgrade the repository.extend method, and now chaining call is possible.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hinogi** [comment]
I don't really see the necessity for this change. Usage of `ts-ignore` seems also bad.

**Comment by sobierajb** [comment]
Hello, @hinogi. This may be particularly useful if you have a set of methods that are shared by all of your repositories and want to propagate them to each custom repository that is specific to an entity. Please review my solution in #10251.

**Comment by hunjin-choi** [comment]
> I don't really see the necessity for this change. Usage of `ts-ignore` seems also bad.

Hi! `ts-ignore` is removed by modify code. Thanks for your review!

**Review by hinogi — APPROVED** [review]
LGTM
But a maintainer has to decide if it is beneficial.

**Comment by pleerock** [comment]
I also don't really see the necessity for this change, but I'm not against it as well. Let's merge it.

**Pull request merged**
