### PR TITLE
Fix: OneToManySubjectBuilder generates incorrect subjects

### PR DESCRIPTION
**Pull request by jbjhjm**
Fixes https://github.com/typeorm/typeorm/issues/8212
Fixes https://github.com/typeorm/typeorm/issues/8175

Edit: On initial PR, I was not 100% right about the source of the issue.
After further investigation, I am now updating the description to better describe what is happening.

In certain cases, OneToManySubjectBuilder will use wrong relation key data which stops it from correctly matching keys of incoming data against database keys.
This will lead to entities being deleted and (re-)inserted instead of being updated and/or staying untouched.

Reason for this is the use of `relation.getEntityValue(subject.databaseEntity)`.
The code assumes that the returned value will only contain the related items key data.
However this can be incorrect. If one uses the afterLoad hook to generate entity properties, the returned object may include additional properties.

### Description of change

The required change is simple:
Pass the data within entityDatabaseValues to getEntityIdMap to get a correct relationId map in all cases.

- [x] Code is up-to-date with the `master` branch
- [X] `npm run lint` passes with this change -- Passed on CircleCI
- [X] `npm run test` passes with this change -- Passed on CircleCI
- [X] This pull request links relevant issues as `Fixes #0000`
- [X] There are new or updated unit tests validating the change -- see info at top
- [X] Documentation has been updated to reflect this change -- not needed
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by imnotjames** [comment]
Lots of test failures.  Can you look into those?

**Comment by pleerock** [comment]
Have you finished with changes? I pulled again, removed changes and still don't see failing tests. Please let me know by pinging me once you finish.

**Comment by jbjhjm** [comment]
@pleerock sorry, forgot to submit the comment it seems.

you were 100% right when asking me to dig deeper.
I discovered that the fix works well, but I was not right about the source of the issue.
I added new commits to reflect new insights.

- refactored the tests for correctly working child composite keys into a new functional test suite, think it's good to have them to ensure it works fine in general
- written a new test that will fail without the fix being applied
- improved notes in source code

The issue does only appear in certain cases, when using a afterLoad subscriber to set some entity data.
This would add additional properties to the child key data item loaded when fetching the parent databaseEntity.
Until now, OneToManySubjectBuilder did not handle this situation correctly,
it tried to match incoming keys against the database keys possibly polluted with additional props.

In this situation, the key mismatch would lead to children being deleted from database and new ones being inserted, also beforeRemove / beforeInsert would be called instead of the expected beforeUpdate.

---

About your most recent comment, it's irritating to hear that.
I just checked if the test would fail if I roll back OneToManySubjectBuilder, and it does fail as expected:

```
 1) github issues > #8221
       afterLoad entity modifier must not make relation key matching fail:

      AssertionError: expected 2 to equal 0
      + expected - actual

      -2
      +0

      at J:\Projects\typeorm\test\github-issues\8221\issue-8221.ts:62:42
```
L62: expect(subscriber.counter.deletes).to.equal(0);
which happens because wrong subjects are being generated.

**Comment by pleerock** [comment]
Yes, they are failing now.

I guess now you have introduced **another bug** because your test is invalid and actually it **must** generated `DELETE` queries, because these lines of code in the test:

```ts
await userRepo.save([{
    id:1,
    settings:[
	    {id:1,name:"A",value:"foobar"},
	    {id:1,name:"B",value:"testvalue"},
    ]
}]);
```

must be:

```ts
await userRepo.save([{
    id:1,
    settings:[
	    {assetId:1,name:"A",value:"foobar"},
	    {assetId:1,name:"B",value:"testvalue"},
    ]
}]);
```

**Comment by pleerock** [comment]
Okay after hours of debugging I can say your solution looks correct. I found magic code that automatically finds first primary key (`assertId`) just based on parent entity and second primary key (`name`). Damn cascades are super complex.

**Comment by jbjhjm** [comment]
> Okay after hours of debugging I can say your solution looks correct. I found magic code that automatically finds first primary key (`assertId`) just based on parent entity and second primary key (`name`). Damn cascades are super complex.

Great! Can you give me a hint on where to find the mentioned magic code? I'd want to take a look and maybe add some notes to the WIP documentation update on cascades https://github.com/typeorm/typeorm/issues/8277

**Comment by pleerock** [comment]
It's subject.identifier gets filled automatically, actually not sure I can explain everything shortly, u need to spend few hours debugging to figure it all out 😆 Also I'm not sure I was completely right in all my assumptions, because some code goes too deeply. Hate cascades. It take too much time and efforts and sometimes I think better not to have this feature TBH.

**Pull request merged**
