### PR TITLE
feat: add "And" operator

### LINKED ISSUE #3113: [Find options] MySQL "where and" on same column
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hi there,

I'm wonder how I can turn simple sql query below:
```sql
select * from user where id < 10 and id in(1, 2, 3);
```
to typeorm find options: https://github.com/typeorm/typeorm/blob/master/docs/find-options.md

Thanks and Best Regards,

### LINKED ISSUE #9466: Feature or documentation: how to add multiple "where conditions" on the same property with FindOptionsWhere ?
### What was unclear or otherwise insufficient?

How to add multiple "where conditions" on the same property with FindOptionsWhere ?

Exemple :

```
const whereCondition: FindOptionsWhere<EntityExemple> = {}

whereCondition.time = MoreThanOrEqual(from)
whereCondition.time = MoreThan(from2)
whereCondition.time = LessThan(to)

await repositoryEntityExemple.find({ where: whereCondition })
```
_ps : I know Between, but it's convenient for me, because not exclusive._

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by iJhefe**
### Description of change
Add "And" operator to handle many "And" in same property

example: 
```ts
await manager.find(User, {
  where: {
    money: And(Not(IsNull()), MoreThan(10), LessThan(100))
 },
})
```

### Pull-Request Checklist
Fixes #3113
Fixes #9466

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Kaladin13** [comment]
@iJhefe This is so amazing and needed! Can we push this as soon as possible?

**Comment by Kaladin13** [comment]
@iJhefe If you need some help or other kind of assistance to push this further, let me know

**Comment by iJhefe** [comment]
> @iJhefe If you need some help or other kind of assistance to push this further, let me know

I think it just needs to be added in the docs with some example

**Comment by divmgl** [comment]
This is super exciting and super useful! Can't wait to see it get merged!

**Comment by pleerock** [comment]
Thank you for contribution! 🎉 Please, please add the documentation to this amazing new feature. Thanks!

**Comment by swatiqman** [comment]
awww......just when i felt lazy to use the query builder, u guys came through....Thank u so much👌

**Pull request merged**
