### PR TITLE
pass [update|insert|remove|load]-events to listeners (as it's done for subscribers)

### PR DESCRIPTION
**Pull request by daweedm**
see #1705 

Make uniform the parameters received by subscribers and listeners

### CODE REVIEW

**Comment by pleerock** [comment]
Can you please add tests to this functionality? (quite easy). Thanks!

**Comment by Kononnable** [comment]
ping @daweedm

**Comment by neuro-sys** [comment]
Looks like this would be very useful. As I just realized that it's not possible to use the surrounding transaction from inside Entity Listeners. So I am planning to move all such logic to Entity Subscribers which get an event object containing the surrounding transaction instance.

**Comment by imnotjames** [comment]
Thanks for your contribution!  However, without tests that confirm this fixes the correct behavior we cannot accept this pull request.

Once you're able to get back to working on this and add tests which show this corrects the specified behavior please re-open a new PR.

**Pull request closed without merging**
