### PR TITLE
Add Select Compatibility for Mongo Driver, Fix issue 1929

### PR DESCRIPTION
**Pull request by wujunyucg**
In the issue 1929, 'select' optionis not effective in mongodb's finds function. So I use mongodb's project function to realize this.

### CODE REVIEW

**Comment by pyk** [comment]
Link to the related issue #1929

**Comment by kingcody** [comment]
@wujunyucg might I suggest, updating the name of this PR to be something a bit more descriptive such as:
> Add Select Compatibility for Mongo Driver

**Comment by kingcody** [comment]
@pleerock would you by chance have any time to review this and report back any issues you might have? Thank you, in advance, for your consideration!

**Comment by RodolfoSilva** [comment]
@daniel-lang can you look this PR? Please.

**Pull request merged**
