### PR TITLE
Documentation Grammar and Punctuation Fixes

### PR DESCRIPTION
**Pull request by matt-neal**
Minor grammar and punctuation fixes to documentation. Some are for readability, some for comprehension, and others to keep formatting in line with surrounding documentation.

### CODE REVIEW

**Comment by matt-neal** [comment]
Since I was reading through the documentation to understand and learn all available functionality within TypeORM, I decided to ensure that I was reading and not skimming by editing the grammar and punctuation within each section of documentation. These are the proposed changes, which all fall in line with professional and formal English standards.

Primarily consists of: 
Adding articles (a, an, the) where missing.
Fixing tense and possessive errors ("'s" vs "s").
Making sure bullet lists ended with a period.
Properly using commas and periods, where appropriate.
Minor rewording work, so as to improve readability and flow for comprehension.

**Comment by pleerock** [comment]
Ohh feeling myself such a dumb seeing so many mistakes. Thank you very much for your efforts.

Can you I mention you in PRs next time I change or add some documentation? Sorry, English isn't my native and Im not a professional in it, so having community support on this question is really appreciated.

**Comment by matt-neal** [comment]
No reason to feel dumb, especially considering how minor the actual changes happened to be.

I am definitely more than willing to help out for future PR's on documentation. I'm glad I can be of assistance.

**Comment by pleerock** [comment]
Thank you!

**Pull request merged**
