### PR TITLE
fix: issue #5613

### PR DESCRIPTION
**Pull request by krazibit**

### CODE REVIEW

**Comment by ohjeyong** [comment]
This PR cause same error as you said on #5613 on my project which means my PR(#5525) breaks yours and this PR breaks mine. I found the problem.

In [PostgresDriver#L606](https://github.com/typeorm/typeorm/blob/b99b4ad869cbf482ae9a5558acf64084157cbedd/src/driver/postgres/PostgresDriver.ts#L606),
```
buildTableName(tableName: string, schema?: string): string {
    return schema ? `${schema}.${tableName}` : tableName;
}
```

This is the problem.
Even though the default value of connection option `schema` is `public`, if `schema` option is set on connection option, then `buildTableName` returns `public.some_table_name` but if not, then `buildTableName` returns just `some_table_name`.

My project doesn't set `schema` option and your project does.

I think there are two solutions.

1. Merge this PR and change `buildTableName` function like below.
```
buildTableName(tableName: string, schema?: string): string {
    return schema ? `${schema}.${tableName}` : `public.${tableName}`;
}
```

2. Change this where statement like this.
```
WHERE (${tablesCondition})
    AND "column_name" = '${tableColumn.name}'
    AND (
        ("table_schema" || '.' || "table_name") = '${table.name}' OR
        "table_name" = '${table.name}'
    )`;
```

Solution 1 is much cleaner and better but `buildTableName` function is referenced a lot, so I don't know is it ok to change like this. @pleerock 

Solution 2 is kind of dirty but it will not make any side effects.

**Comment by krazibit** [comment]
Yeah, you are right @ohjeyong .
I'll add the second solution to the PR

**Comment by krazibit** [comment]
Or even shorter as a `schema` variable is available in the method  can do ` "table_name" = '${table.name.replace(`${schema}.`)}'`

**Comment by cknuteson-firstlook** [comment]
Looking forward to this getting merged. Had to rollback to 0.2.22 for my project

**Comment by ohjeyong** [comment]
@krazibit Can you add the commit?

**Comment by krazibit** [comment]
Sure, would add the commit in a bit

**Comment by krazibit** [comment]
@ohjeyong, can you verify please? thanks

**Comment by ohjeyong** [comment]
Thanks. LTGM. @pleerock Can you verify please?

**Comment by winterec** [comment]
This patch fixes it for me

**Comment by pleerock** [comment]
oh I already merged #5801 before I saw this PR. It looks like author tried to fix same issue, but a bit different way. Is merged approach is correct and I can close this PR? adding @igoraguiar

**Comment by krazibit** [comment]
closing this as already fixed in PR-5801 as per @pleerock last comment

**Pull request closed without merging**
