### PR TITLE
feat: add column comment support for for postgres

### PR DESCRIPTION
**Pull request by nionoku**
Adding a comment to a column when creating a column for postgres.

### CODE REVIEW

**Comment by vlapo** [comment]
Please update formatting. Could you write a simple test?

Related to https://github.com/typeorm/typeorm/issues/4359

**Comment by nionoku** [comment]
Thanks for the comment @vlapo. 

Fix missing ";" and add simple test.

**Comment by vlapo** [comment]
@nionoku Why did you close your PR?

**Comment by rustamwin** [comment]
Looks like @nionoku created a separate PR #4461

**Pull request closed without merging**
