### PR TITLE
pass column name for `SQL expressions` value in update query

### PR DESCRIPTION
**Pull request by s97712**

### CODE REVIEW

**Comment by vlapo** [comment]
Please describe more about this PR. What is problem you want to resolve with this PR.

**Comment by s97712** [comment]
this PR can pass column name to function of generating `SQL expressions`  in update query.
```
        const qb = connection.createQueryBuilder();
        await qb
            .update(User)
            .set({ likesCount: () => qb.escape(`likesCount`) + " + 1" }) 
            /* Replace with 
            .set({ likesCount: name => `${name} + 1` })
            */
            .where("likesCount = 1")
            .execute();
```

**Comment by vlapo** [comment]
okey, but first at all fix all issues with failed build.

**Comment by pleerock** [comment]
I don't think we need it. In practice people use a single database and they don't need cross-database escaping mechanizm. So,  `.set({ likesCount: () => `"likesCount" + 1` })` is already quite fine.

**Comment by Kononnable** [comment]
I believe if you specify db name you also have to specify schema name(at least in some database engines).

Tests failing, author didn't reply. I also think this is very marginal use case(and it's not even complete).
Closing.

**Pull request closed without merging**
