### PR TITLE
Make the `leftJoinAndMapOne` entity definition satisfy a strict TypeScript config

### PR DESCRIPTION
**Pull request by jalada**
#3973

### CODE REVIEW

**Comment by pleerock** [comment]
Yes its matter of strict mode and it really depends how you are using typescript. It complicates docs and isn't consistent with other docs we have. Thank you for PR anyway.

**Comment by jalada** [comment]
Is there information somewhere in the documentation on what TS config has been used to define the docs, and what should be used so that if you _use_ the documentation your code doesn't syntax error?

**Comment by pleerock** [comment]
it will emit error only if strict mode is enabled. If you create a new project with empty tsconfig and start setting up things it won't emit you errors until you add strict flag into tsconfig. As far as I know most of people don't use strict mode

**Comment by jalada** [comment]
OK gotcha, thanks @pleerock.

**Pull request closed without merging**
