### PR TITLE
fix: allow clearing database inside a transaction

### PR DESCRIPTION
**Pull request by varanauskas**
Possible fix for: #8527

### Description of change

This is one of the possible fixes for the issue #8527

It allows to run `clearDatabase` inside a transaction by making `clearDatabase` to check if another transaction is already running and not creating a new transaction in that case

It currently is only developed for/tested with Postgres, if this is the right direction same fix could be applied for other query runners

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
I think we can accept it.

> It currently is only developed for/tested with Postgres, if this is the right direction same fix could be applied for other query runners

if we go with this fix, fix needs to be applied to all other query runners as well.

**Comment by pleerock** [comment]
I think changes still do not cover all drivers.

**Comment by varanauskas** [comment]
Yes, I could not successfully test the changes on other drivers so I did not submit them, I will try to diagnose why I couldn't run some of the docker container tests and submit changes for other drivers. (Any tips on testing with more exotic drivers like SAP Hana or Oracle XD?)

**Comment by pleerock** [comment]
For SAP Hana there is no easy way... Hana's official site provides a trial for their product as I know. For Oracle and MSSQL you can simply commit and check if CI is failing. Since the code you are changing is straightforward, I think you can just copy/paste code in required places without mistakes and everything else should be fine.

**Comment by pleerock** [comment]
I'm going to close this one because I'm doing unfinished PRs cleanup (to prevent conflicts). Please feel free to rebase it on latest master and reopen it with all requested changes applied. Thank you.

**Comment by varanauskas** [comment]
Thank you, I will add the changes to other drivers and reopen

**Pull request closed without merging**
