### PR TITLE
new flag to configure synchronize schema to not drop columns and tables

### PR DESCRIPTION
**Pull request by oxeye-yuvalk**
### Description of change

Add synchronizeWithoutDrops option that set synchronization to not drop columns and tables but only add columns and tables when initializing

related to - https://github.com/typeorm/typeorm/issues/2196

It is very easy to get this wrong and/or make a mistake. synchronization should not drop columns - especially with existing data

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run lint` passes with this change
- [X] `npm run test` passes with this change
- [X] This pull request links relevant issues as `Fixes #0000`
- [X] There are new or updated unit tests validating the change
- [X] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md]

### CODE REVIEW

**Comment by pleerock** [comment]
I'm very pessimistic about this PR. What is the real purpose of this feature?

**Comment by oxeye-yuvalk** [comment]
The purpose is to have an option to run with synchronized option in production and not worry about losing data. For example, I don’t want that if I would remove column from entity, it will remove the whole column with the data. In many ORM’s, synchronize only add columns and meta data and not remove things because it’s very dangerous. This feature would be great for using the powerful of synchronize in production

**Comment by imnotjames** [comment]
**Even with this change, the synchronizing feature will destroy your data, without warning, and without a means to recover.**

I really, really don't think synchronized should be used in production.

It's a development tool, at best.  (I actually think it should be dropped as a feature entirely, but hey, it's tough to remove features..)

It provides no real way to roll back the changes and is not atomic nor is it reproducible.

**Comment by AlexMesser** [comment]
> I don’t want that if I would remove column from entity, it will remove the whole column with the data

Synchronization does exactly what it says - synchronizes your entity with the database table.

In production, you should use migrations instead of synchronization and carefully check the generated migration line by line to prevent data loss.  

So, I agree with @pleerock and @imnotjames - this change makes no sense

**Pull request closed without merging**
