### PR TITLE
Feat: orphanedRowAction=skip to disable auto-orphanage of children that are not loaded during updating parent

### PR DESCRIPTION
**Pull request by jbjhjm**
### Description of change

Fixes https://github.com/typeorm/typeorm/issues/8275

When saving a parent of a OneToMany relation, OneToManySubjectBuilder will currently orphane/delete all items that are not within the list of to-be-saved children.

This is not always wanted behavior. Example:

Let's assume we have a User [parent] with a number of [child] Settings.
Some of these settings may only be modified and visible to admins, others can be seen and edited by users themselves.
The user edits his/her profile and the data is sent to backend - a UserEntity with only those settings that the user can see/edit.

Currently, we'd now have to fetch all settings from database for all endpoints updating users, merge them with incoming changes and then save them - just to let OneToManySubjectBuilder that the persisted rows should not be removed.

Summing up, there are situations where it is just way simpler if one can disable the auto-orphaning mechanism.
Furthermore I believe that the behavior of auto-orphaning on update did not always exist and has been added some time ago.

Fortunately, this can be done very easily:
We add "skip" to allowed values for orphaneRowAction and do a simple if-condition skipping the auto-orphanage section.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` fails 737 times on code not modified by myself
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
The user edits his/her profile and the data is sent to backend - a UserEntity with only those settings that the user can see/edit.

I think this can be easily fixed by controlling what you are sending to save after you receive data from client.
I strongly recommend to do it this way.

e.g. don't send settings that you receive from the client to save method, since it's not a desirable action for you.

**Comment by jbjhjm** [comment]
@pleerock 

I think you misunderstood the intention of this feature. Of course there are other ways to handle data.
But this is about adding one piece of configurability that has not been considered yet.

Currently we can specify HOW orphanage should work. But not IF it should be applied at all.
It is risky, data might be deleted by accident. The behavior of the mechanism is not obvious:

Saving children when saving parent is logical.
Deleting children when deleting parent is local.
Deleting children when updating parent is not obvious at all.

In many cases it is fine to have this feature enabled but one needs to be cautious with it.
For these reasons I strongly believe that we should be able to be in full control of this functionality.
It should be possible to disable it if one does not want to apply this behavior.

**Comment by pleerock** [comment]
Okay since we are continuing merging cascade-related features (which I really hate), let's merge this one as well. I don't really like `skip` name because it sounds like something related to take/skip to me. What about to use `ignore` instead? Or do you have a better options?

**Comment by jbjhjm** [comment]
Great!
Well we should be sure to find a term that makes sense in context to "orphanedRowAction".
"Ignore orphaned row action" might be too ambiguous to immediately understand what it does.
"Disable orphaned row action" sounds more explicit to me. What do you think about keyword `disable`?

Let me know what fits to typeORM, will do a rebase + wording update then.

**Comment by jbjhjm** [comment]
@pleerock need a short feedback here to prepare PR update.
What fits better to typeorm naming conventions:

orphanedRowAction: disable
or
orphanedRowAction: ignore

thanks!

**Comment by pleerock** [comment]
I'm okay with `disable`. Thank you for patience :)

**Comment by jbjhjm** [comment]
closing in favor of rebased/updated PR https://github.com/typeorm/typeorm/pull/8678

**Pull request closed without merging**
