### PR TITLE
Proposed Fix for #4820 

### PR DESCRIPTION
**Pull request by jf214**
Including schema in table path for OracleDriver in EntityMetadata

### CODE REVIEW

**Comment by pleerock** [comment]
as I know in oracle there is no real schema. There is a schema but is equal to user. If so then our schema related functionality might not work properly.

**Comment by jf214** [comment]
So far, in my experience using Typeorm with Oracle, I have not had any issues with how schemas are treated by the library. It wasn't until I updated to latest that my queries ignored the schema I had defined in the entities, which caused my queries to fail in Oracle. I think it started with d8f1c81dcfed33bf73493fccd162dff70f2679f9.

I tested my fix and it seems to work for Oracle. Though in hindsight, it isn't ideal because it doesn't address the issue for other driver types.

**Comment by kdi-1** [comment]
@jf214  I think in number 8 should be 
import {OracleDriver} from "../driver/oracle/OracleDriver";

**Review by imnotjames — CHANGES_REQUESTED** [review]
This needs tests to confirm the behaviors

**Comment by kdi-1** [comment]
@imnotjames @jf214  I think this can be closed as fixed in #6673

**Pull request closed without merging**
