### PR TITLE
First load parent metadata, then create primary columns

### PR DESCRIPTION
**Pull request by eyalhakim**
and only then we can create join columns/foreign keys.

Prior to this fix, creating foreign keys / junction entity metadatas did not work since we didn't yet load join columns.

### CODE REVIEW

**Comment by eyalhakim** [comment]
@pleerock another fix

**Comment by eyalhakim** [comment]
Hi @pleerock, would appreciate your help on this one and the other PR's.
We are relying heavily on TypeORM and really need the inheritance feature.

**Comment by eyalhakim** [comment]
@pleerock can you look why this build is failing?
Doesn't seem like something caused by my changes

**Comment by pleerock** [comment]
I'll close this issue since I decided to remove CTI support from typeorm functionality for now.

**Pull request closed without merging**
