### PR TITLE
Add ILike FindOperator for case insensitive LIKE

### PR DESCRIPTION
**Pull request by brussee**
(depends on support by database driver)

### CODE REVIEW

**Comment by brussee** [comment]
Small contribution, which takes care of the case insensitive LIKE use case.
Solution, until the intended refactor is done at some point: https://github.com/typeorm/typeorm/pull/5574#issuecomment-592302691

**Comment by brussee** [comment]
Fixes #4418

**Comment by brussee** [comment]
Here's a gist for anyone using https://www.npmjs.com/package/patch-package
https://gist.github.com/brussee/d66ebabe8556168b69e61c5420491318

**Comment by pleerock** [comment]
We already have this functionality on `next` branch. There is a failing test - you probably missed the point to exclude unsupported databases.

**Comment by pleerock** [comment]
Also, can you please make sure there is minimal amount of differences with `next` branch? To simplify merge to the `next` branch. Thanks!

**Comment by brussee** [comment]
> ... - you probably missed the point to exclude unsupported databases.

Yes, I don't know how to do that.

> Also, can you please make sure there is minimal amount of differences with `next` branch?

I've just checked and there are no differences on the `next` branch regarding this patch, so I'll close this.

@pleerock Sorry for the delay and thanks for your replies!

**Pull request closed without merging**
