### PR TITLE
fix: support multiple row insert on oracle

### PR DESCRIPTION
**Pull request by wfpena**
change generated insert query to allow inserting an array of objects to oracle

fixes: #2434

### CODE REVIEW

**Comment by imnotjames** [comment]
Can you explain briefly how this works?

**Comment by wfpena** [comment]
@imnotjames 
I've just followed the idea based on this :https://stackoverflow.com/questions/39576/best-way-to-do-multi-row-insert-in-oracle 

You can insert on oracle based on a query. So you can do something like:

```sql
ìnsert into table1
select ...
```

so what this change does is, create a query with the union of all the values on the array to be inserted, then place them on the insert statement.

**Comment by imnotjames** [comment]
Can you add a test that uses a generated column

**Comment by wfpena** [comment]
I've already added that

**Comment by imnotjames** [comment]
Aha, I had only looked at the second model, didn't see the first one 🙈

**Comment by wfpena** [comment]
I've had to add tests with primary generated columns and date columns, etc.

**Comment by wfpena** [comment]
> Aha, I had only looked at the second model, didn't see the first one 🙈 I'll try to fully review this as soon as I can. Trying to get through the backlog while keeping up with new PRs.

Thank you

**Comment by wfpena** [comment]
@imnotjames just realized I dind't leave the id null on the tests with primary generated, I might have to fix that.

**Comment by wfpena** [comment]
> @imnotjames just realized I dind't leave the id null on the tests with primary generated, I might have to fix that.

@imnotjames the tests are fix now.

**Comment by pleerock** [comment]
Good we have oracle tests running on CI now. Probably this can be merged?

**Pull request merged**
