### PR TITLE
Fix uuid length error for issue #1139

### PR DESCRIPTION
**Pull request by huanz**

### CODE REVIEW

**Comment by huanz** [comment]
@havenchyk

**Comment by pleerock** [comment]
Thanks for the fix!

Can you please tell me why is it against `next` and not `master`? Is it a breaking change?

**Comment by huanz** [comment]
@pleerock just bug fix, no breaking changes. @havenchyk told me to place this PR against `next` branch #3168

**Comment by havenchyk** [comment]
oh, my bad, I thought it's a breaking change.

**Comment by pleerock** [comment]
if its not please change base to master

**Comment by huanz** [comment]
@pleerock #3234

**Pull request closed without merging**
