### PR TITLE
Update view-entities.md

### PR DESCRIPTION
**Pull request by Mikkal24**
docs: update view-entities.md

Add @PrimaryColumn() decorator to at least @ViewColumn(). Without the decorator we can't use repository methods such as count(). Was difficult to find the solution so I wanted to include this in the docs to save others time.

### CODE REVIEW

**Comment by pleerock** [comment]
I don't think we should merge this one, since right now its not by design. Instead we should create an issue with the description of the problem for the future to design it and build a proper solution.

**Comment by Mikkal24** [comment]
Okay! I'll open an issue today. Can I use this PR for reference? @pleerock

**Comment by pleerock** [comment]
yes, sure. Thanks @Mikkal24

**Comment by Mikkal24** [comment]
Added issue -> https://github.com/typeorm/typeorm/issues/4699

**Comment by pleerock** [comment]
Thanks!

**Pull request closed without merging**
