### PR TITLE
fix a bug in fetch data from sql.js

### PR DESCRIPTION
**Pull request by vorujack**
### Description of change

when we use sql.js database we have some extra configuration on it.

one of them is to use bigint instead of using js number format.

I update code to use this configuration when fetching data
-->

### Pull-Request Checklist

- [*] Code is up-to-date with the `master` branch
- [*] `npm run lint` passes with this change
- [*] `npm run test` passes with this change
- [N/A] This pull request links relevant issues as `Fixes #0000`
- [N/A] There are new or updated unit tests validating the change
- [N/A] Documentation has been updated to reflect this change
- [*] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
Can you please add a link to the official documentation explaining this behaviour? I was able to find this, however it's unclear purpose and detailed usage of `getAsObject` parameters.

**Comment by vorujack** [comment]
Its not documentted anywhere. but I read sql.js codes and find this option

**Comment by pleerock** [comment]
I'll close it for now. Feel free to re-create it with more details. Thanks.

**Comment by vorujack** [comment]
https://github.com/sql-js/sql.js/#enabling-bigint-support

this is documentation about this pull request

**Pull request closed without merging**
