### PR TITLE
fix: respect database from connection urls

### PR DESCRIPTION
**Pull request by ant45de**
Database names can be defined in the options object. Now also connection urls that contain a database can be used to have the database set in the drivers object.

Closes: #2096

### CODE REVIEW

**Comment by pleerock** [comment]
Cockroachdb is failing because mysql is disabled in there. We need to check in this test if mysql tests were enabled in ormconfig.

**Comment by ant45de** [comment]
Thanks for the hint!
I surrended the connection test with the ormconfig check.

**Comment by glennreyes** [comment]
Can you catch up on this @pleerock? Thanks!

**Comment by ant45de** [comment]
@pleerock can this be merged?

**Comment by pleerock** [comment]
Sorry guys for a late review. Thanks!

**Pull request merged**
