### PR TITLE
Fix for issues #549, #244, #572 and #221.

### LINKED ISSUE #549: Unique Index Name on recreation
Hi,

When using a unique index like this`@Index({ unique: true })` the column is successfully created but when restarting TORM it throws an error complaining that the index does not exist.

The fix is `@Index("myCol", { unique: true })`

What appears to be happening is that the "ALTER TABLE / DROP INDEX" statement is no recognising the index by it's uid. Instead it tries to drop the index using the column Name for the index name. 

`ALTER TABLE `user` DROP INDEX myCol`

instead of

`ALTER TABLE `user` DROP INDEX ind_705816b51e5f6f664aacaa94a75`

An alternative fix is to simply restart TORM again.

cheers

JT

### PR DESCRIPTION
**Pull request by iz-iznogood**
Add normalizeIsUnique method to driver interface and use it to check if a column is isUnique compared to what the DB schema reports. There are differences on how a DB handles the unique column case.

MySQL - MariaDB consider a column as unique if there is a unique index on the column, without the need for a unique constraint. 
So we need to adjust on how we resolve differences so that we take this into account (only for this DB type).

This fixes #549, #244, #572 and #221

### CODE REVIEW

**Comment by pleerock** [comment]
Do you think we shall add tests for this case as well?

**Comment by iz-iznogood** [comment]
Yes I will send the tests shortly, if you agree with the approach though... 

At least 3 of them are exactly the same scenario so for them one test will do. The other (#572) I will see if we need a separate test.

So are you good with how it is implemented so that I can code the tests ?

**Comment by pleerock** [comment]
Implementation does not affect the tests, isnt it?

**Comment by pleerock** [comment]
Im not sure about this implementation yet, I need to understand you why did so and isnt there a better solution....

**Comment by pleerock** [comment]
are you sure this issue is mysql-specific? For example as I see right now posgres has same logic - it creates constraints if unique is used, also it can create an unique index. Then what is the difference? 

```ts
!!column.entityMetadata.indices.find(index => index.isUnique && index.columns.length === 1 && index.columns[0] === column)
```

For example, why this code cannot be applied for other drivers as well?

**Comment by iz-iznogood** [comment]
Ok, I just pushed the test...

**Comment by iz-iznogood** [comment]
The difference is that when you read the schema from the database there is no way to know in MySql if the column is unique or not since they report it unique not because of unique constraint but also because of unique index.

For example in sql server a column is not unique unless you create a unique constraint for that column.
Same for postgres

In mysql this does not work though constraints but directly though indices

**Comment by pleerock** [comment]
Now I completely understood the issue, thx for explanation, however... I don't really like current fix. Maybe we can came up to something more elegant?

**Comment by pleerock** [comment]
Okay we can merge it. I cannot came up to something better. In the future Im planning to refactor this `findChangedColumns` method and maybe move it into the `QueryRunner` and make it completely driver-specific. Then this will be refactored as well

**Pull request merged**
