### PR TITLE
Proper default column for postgres

### LINKED ISSUE #1677: Array type default for Postgres always shows update needed in schema:log
Related to #1532 
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When using an array column in Postgres, using the array literal as a string works to set the default value in the database:

```js
@Column({
  nullable: false,
  type: 'smallint',
  array: true,
  default: '{5}',
})
```

However, when running `schema:log` or `schema:sync` with the cli, it always reports that it needs to update the default value of this column:

```sh
ALTER TABLE "public"."user" ALTER COLUMN "roles" SET DEFAULT '{5}';
```

This is because the actual default value in postgres is `'{5}'::smallint[]`. In other words, the default value needs to be the literal string, wrapped in single quotes, with `::column.type[]` appended to the end.

### PR DESCRIPTION
**Pull request by jdforsythe**
Fixes #1677 for next branch

See #1678

### CODE REVIEW

**Comment by pleerock** [comment]
You did lot of non necessary changes like replacing `defaultValue: string|Function` to `columnMetadata: ColumnMetadata`. Please be careful with changes you bring.

About the problem itself, Im not sure if appending type automatically will not lead to other problems. (for example does type we have always match type user specifies? What if default will be wrapped into a function, for example `xxx(column)`, etc.)

Isn't it better if user simply specify array type on his own?

**Comment by jdforsythe** [comment]
About the parameter change, see my [comment on the issue](https://github.com/typeorm/typeorm/pull/1678#issuecomment-370530178). There was a change in `next` to only pass in the `columnMetadata.defaultValue` string instead of the whole object (as is the case in `master`). In order to know if the column is an array, you also need access to the `columnMetadata.isArray` boolean, so the whole object must be passed in. The parameters have to be the same across all the different drivers, so I changed all references to the function to pass or expect the full `ColumnMetadata`.

If you see the problem in #1677, postgres returns the array default as an array literal with a cast, so without this the `schema:log` and `schema:sync` will _always_ report there is a change to the default value for every array column.

I'm not sure what you mean about the user type - isn't `columnMetadata.type` the type the user specified in the model? The default column as a function is handled - I added the cast to the resulting value of the function.

If you have a different way to fix this bug, I'd be willing to help

**Comment by pleerock** [comment]
Thank you very much.

I mean what if we enforce people to do following:

```ts
@Column({
  nullable: false,
  type: 'smallint',
  array: true,
  default: '{5}::smallint[]',
})
```

Instead of simply {5} ?

**Comment by pleerock** [comment]
Okay, nervermind. 

Yes, we can merge this, however I removed your code from function-style value, I want to left full  control for users who don't want to have this type applied.

**Pull request merged**
