### PR TITLE
feat: Add pool error handler

### PR DESCRIPTION
**Pull request by Ginden**
Add option to customize pool error handling. Users can decide to log these errors with higher level (eg. error), crash application or reconnect.

### CODE REVIEW

**Comment by vlapo** [comment]
Why not use `Logger` (https://typeorm.io/#/logging/using-custom-logger) and add only one new method? e.g. `logPoolError`

**Comment by Ginden** [comment]
Why should I want to put eg. application termination logic in *logger*?

**Comment by vlapo** [comment]
Sorry I read "pool error logger". Could you please update docs?

**Comment by Ginden** [comment]
@vlapo Done!

**Comment by pleerock** [comment]
Thanks guys!

**Pull request merged**
