### PR TITLE
add tests for issue-3226

### PR DESCRIPTION
**Pull request by dimensi**
Hi, it's pr adding tests for issue-3226 as asked me.
https://github.com/typeorm/typeorm/issues/3226#issuecomment-446876193

### CODE REVIEW

**Comment by rustamwin** [comment]
you have syntax error

**Review by rustamwin — CHANGES_REQUESTED** [review]
generated column name is not checked

**Comment by dimensi** [comment]
@rustamwin yea, thx for notice. I fix it.

**Comment by dimensi** [comment]
@rustamwin hello? what about my pr?

**Pull request closed without merging**
