### PR TITLE
Add common type aliases to normalizeTypes (#861)

### PR DESCRIPTION
**Pull request by iz-iznogood**
I have done a (very) simple implementation, I have used "string", "integer", "date" and "boolean".
I believe it would be nice to have something common for float and double. 

Please take a look and if you agree I can add these + tests so that it is complete.

Thanks

### CODE REVIEW

**Comment by pleerock** [comment]
You must remove checks for "date" because there are database types called "date". And this database is not equal to `Date`. Usually "date" is simply dd:mm:yy, but `Date` is more then that - it also contains hrs, mm, ms

**Comment by pleerock** [comment]
any updates on this?

**Comment by iz-iznogood** [comment]
I need aliases for at least the common types including date, otherwise it is useless IMO.
Since we can not use date, what other options are there ?

**Comment by pleerock** [comment]
other option is to use other name. But I don't think we can find name better then "date" =) So we have really only two options: 1. close this PR; 2. Left everything else and exclude date at all.

**Comment by iz-iznogood** [comment]
Right now we need these data types (mabe more in the future):
Boolean, String, Int32, Int64, Int16, Byte, Decimal, Float, Double, Date, Datetime, Time, Guid, ByteArray

As it stands now I maintain the mapping in my own code, which is not a problem. But having something common across the board would be great. Also the user can change the mapping at initialization, you have something like this inside the drivers I believe (I found it while looking on the Version decorator)

We could also use specific names like torm_boolean, torm_string, etc or somenamespacing like torm.commonTypes.string, torm.commonTypes.boolean
So we can have the string names for the json and some constants or enum for the code (decorators) 
I know it is not pretty but at least this reduces the overhead on having to handle DB specific stuff on code that is totally DB agnostic.

What's your opinion ?

**Comment by pleerock** [comment]
> Right now we need these data types (mabe more in the future):
Boolean, String, Int32, Int64, Int16, Byte, Decimal, Float, Double, Date, Datetime, Time, Guid, ByteArray

I don't think so. Int32 ? Why not integer32 ? Double? Why not Numeric or Real? Guid? Why not UUID? Date, Datetime, Time are already busy. See, the problem is to call it "double" or "real" is that its the same meaning, just depend on database (and programmers) preference. Im sure we shall not confuse things even more.

> We could also use specific names like torm_boolean, torm_string, etc or somenamespacing like torm.commonTypes.string, torm.commonTypes.boolean

ahh looks very very bad

My opinion is that we can add "string" and maybe "boolean" and not really more then that. Or not do do anything and simply let user use database-specific types as it was designed.

**Comment by iz-iznogood** [comment]
Ok lets close it then, there is no point in implementing it only for 2 data types.

However I still believe that you have thought of it backwards. 
Usually in ORM design you begin with the abstraction and at a later stage you add the possible overrides. 

In TORM you want to have DB specific types but you don't really use the extra functionality each DB provides, for example in the query builder you have a common interface (which is good) but I do not see how you can use specialized queries that only a few RDBMS's support. And how are you going to handle the cases that a feature is supported in a small subset of databases....

**Pull request closed without merging**
