### PR TITLE
Update AbstractSqliteDriver.ts

### PR DESCRIPTION
**Pull request by Kolesar**
JSON and Timestamp are supported types in the SQLite since version [3.38.0](https://www.sqlite.org/json1.html)

### CODE REVIEW

**Comment by AlexMesser** [comment]
If you want to add new types, you should update [this test](https://github.com/typeorm/typeorm/tree/master/test/functional/database-schema/column-types/sqlite) with new types and make related changes in `AbstractSqliteDriver` and `AbstractSqliteQueryRunner` if these types will not work out of the box.

**Comment by Kolesar** [comment]
> If you want to add new types, you should update [this test](https://github.com/typeorm/typeorm/tree/master/test/functional/database-schema/column-types/sqlite) with new types and make related changes in `AbstractSqliteDriver` and `AbstractSqliteQueryRunner` if these types will not work out of the box.

I will try to do it :)

**Comment by pleerock** [comment]
@Kolesar would be great if you find a time to complete this issue, it's not really hard to add tests! Thank you!

**Comment by AlexMesser** [comment]
I'm going to close it since there are many unrelated changes which makes it impossible to review. Feel free to submit a new PR with your changes and tests.

**Pull request closed without merging**
