### PR TITLE
Fix enum handling in non default namespace, fixes #1997

### LINKED ISSUE #1997: Enum type not working in postgres
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```
type Action =
    'add' |
    'update' |
    'delete';
@Entity()
export class DatasourceAction {

    @PrimaryColumn()
    id: string;

    @Column({ name: 'name', type: 'text', unique: true })
    name: string;

    @Column({ name: 'action', type: 'enum', enum: ['add', 'update', 'delete'] })
    action: Action;
}
```
The SQL quarries executed are as follows
```
CREATE TYPE "test"."datasource_action_action_enum" AS ENUM('add', 'update', 'delete')
ALTER TABLE "test"."datasource_action" ADD "action" "datasource_action_action_enum" NOT NUL
```
and it errors with type "datasource_action_action_enum" does not exist

I think the the ALTER TABLE query should have been as follows.
ALTER TABLE "test"."datasource_action" ADD "action" "test"."datasource_action_action_enum" NOT NUL

### PR DESCRIPTION
**Pull request by evik42**

### CODE REVIEW

**Comment by francosioquim** [comment]
When can we expect this to be merged?

**Comment by evik42** [comment]
@francosioquim pls check the discussion at https://github.com/typeorm/typeorm/issues/1997

**Comment by pleerock** [comment]
Thank you very much!

**Comment by usamasaif** [comment]
@Column({
    type: 'enum',
    enum: ENUM_AUTH_ACCESS_FOR,
    unique: true,
  })
  accessFor: ENUM_AUTH_ACCESS_FOR;


//getting error
3) {
  query: '\n' +
    '            CREATE TABLE "roles" (\n' +
    '                "id" SMALLSERIAL NOT NULL,\n' +
    '                "name" character varying(50) NOT NULL,\n' +
    '                "is_active" boolean NOT NULL DEFAULT true,\n' +
    '                "access_for" "public"."roles_access_for_enum"NOT NULL,\n' +
    '                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT Now(),\n' +
    '                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT Now(),\n' +
    '                CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"),\n' +
    '                CONSTRAINT "UQ_787140beefe68107ef11ce912ce" UNIQUE ("access_for"),\n' +
    '                CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")\n' +
    '            )\n' +
    '        ',
  parameters: undefined,
  driverError: error: type "public.roles_access_for_enum" does not exist

**Pull request merged**
