### PR TITLE
fix: resolve issues ora-00972:identifier is too long

### PR DESCRIPTION
**Pull request by MuratGundes**
Use index instead of parameter name for make it shorter alias name.

Closes: #5067

### CODE REVIEW

**Comment by pleerock** [comment]
@imnotjames right now we have no idea if we can merge this small, but suspicious change because we have no oracle tests on CI running 😭

**Comment by imnotjames** [comment]
We can get them running - they weren't before because they were disabled & I think the Oracle image couldn't be pulled 'cause it's not free.

Happy to take a look at adding an oracle build to the mix - I was poking at it the other day but gave up because it just hasn't been running before.

**Comment by pleerock** [comment]
@imnotjames thanks a lot

**Comment by MuratGundes** [comment]
Thanks a lot guys! We will be appreciated.

**Comment by Rainson12** [comment]
merging this will be much appreciated it seems to be working for us and it seems like there is not other solution other than this to fix the issue with column& table names be longer than 30 characters. Its also not possible to shorten the column names as its a legacy system.

**Comment by imnotjames** [comment]
Just to quickly update this thread on the status of OracleDB CI ---

I've refactored the CI to use docker-compise to start up services.  This
simplifies bringing in other services because they just need to be defined
in docker compose like the others & can even be "private" corporate images
like the OracleDB ones.

https://github.com/imnotjames/typeorm/blob/build/remote-docker/

I'll be trying to get this in as a PR today.

As an extended part of this I've added the client libraries (why would it
need separate libraries like this? Licensing I assume..? Ugh..) for
oracleDB as well as a docker compose service to start up oracle for us to
run tests against it.

However, currently running into an issue with oracle during the first test
that gets run against it - I've got a feeling I've set it up to connect to
the wrong SID? Unclear.

QueryFailedError: ORA-24005: Inappropriate utilities used to perform DDL on
AQ table SYSTEM.DEF$_AQCALL

**Comment by imnotjames** [comment]
Ok - issue with tests is that I had tried to spin up Oracle 11 - which typeorm doesn't support.

**Comment by imnotjames** [comment]
Oracle tests seem to be working and they catch another spot where this happens -

https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1864

The column alias can end up being `30` characters long because of the `ids_` prefix.  I'd fixed it by replacing it with:

https://github.com/imnotjames/typeorm/blob/619b2bd42e6a4abfe116e6cad3a35a0b4a72eb85/src/query-builder/SelectQueryBuilder.ts#L1865-L1871

**Comment by imnotjames** [comment]
Should this instead be done similar to aliases?  if > some predetermined driver specific length, `hash` it?

Like https://github.com/typeorm/typeorm/blob/5516aca07db4137df05ad2c789e10b943a939ae6/src/driver/DriverUtils.ts#L52

**Comment by imnotjames** [comment]
Also @MuratGundes please rebase against `master` - the tests for Oracle should run now :)

**Comment by imnotjames** [comment]
Hey @MuratGundes - I'm gonna open another PR with these changes - the commits will have you as the author, but will be rebased against `master` so the oracle tests will run!

**Comment by pleerock** [comment]
thank you @imnotjames it would be great if we can merge this one as fast as possible

**Pull request closed without merging**
