### PR TITLE
fix: remove the main alias when using from()

### PR DESCRIPTION
**Pull request by rewieer**
Closes: #4015

### CODE REVIEW

**Comment by pleerock** [comment]
It doesn't seem to be a proper fix.

**Comment by rewieer** [comment]
Why and how is it supposed to be fixed?

**Comment by pleerock** [comment]
I'm not sure now. I checked git history and I don't see explanation where it was commented. Maybe since tests aren't failing we can merge this PR, but can you please add tests first?

**Comment by Kononnable** [comment]
@rewieer What about those tests? :)

**Comment by rewieer** [comment]
@Kononnable Didn't check this PR since then. Is this fix awaited for a next release ?

**Comment by rewieer** [comment]
As far as i'm trying to run tests i'm running into the following error : 
```
> typeorm@0.2.19 test-fast-3 /Users/rewieer/Documents/dev/oss/js/typeorm
> mocha --file ./build/compiled/test/utils/test-setup.js --recursive ./build/compiled/test/github-issues


/Users/rewieer/Documents/dev/oss/js/typeorm/build/compiled/test/github-issues/1089/entity/Group.js:31
}(src_1.BaseEntity));
 ^
TypeError: src_1.Entity is not a function
    at /Users/rewieer/Documents/dev/oss/js/typeorm/build/compiled/test/github-issues/1089/entity/Group.js:27:15
    at Object.<anonymous> (/Users/rewieer/Documents/dev/oss/js/typeorm/build/compiled/test/github-issues/1089/entity/Group.js:31:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/mocha.js:327:14)
    at Mocha.run (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/mocha.js:804:10)
    at Object.exports.singleRun (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/lib/cli/cli.js:63:6)
    at Object.<anonymous> (/Users/rewieer/Documents/dev/oss/js/typeorm/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

As stated in the command, this error only happens in the github-issues folder. Tried to seek a reason but can't find one. Just noticed that Entity depends on index.js who depends on Entity, but following this track didn't pay.

Hints are welcome !

**Comment by xmsz** [comment]
So, what is the solution to fix at this time?

**Comment by rewieer** [comment]
@xmsz manually patch this on your code with patch-package until someone helps me getting tests up

**Comment by johanneslumpe** [comment]
This does not actually seem to fix the issue. Event with this change, this still fails:
```ts
createQueryBuilder()
  .from(
    subQuery => subQuery.from(Model, 'model').limit(1), 
    'alias'
  )
```

**Comment by abdullah2993** [comment]
Any update on this? @pleerock this seems to be a deal breaker if you have want to nest queries

**Comment by imnotjames** [comment]
Still awaiting tests that verify this works as expected.

**Comment by imnotjames** [comment]
Thanks for your contribution!  However, without tests that confirm this fixes the correct behavior we cannot accept this pull request.

Once you're able to get back to working on this and add tests which show this corrects the specified behavior please re-open a new PR.

**Pull request closed without merging**
