### PR TITLE
Browser Package: Adds cli.js and fixes wrong naming for the SystemJS build

### PR DESCRIPTION
**Pull request by daniel-lang**
As mentioned in #857 the `cli.js` file was missing from the package, which npm complains about. For consistency, I also renamed the internal name for the SystemJS build since otherwise the package would be called `typeorm-browser` but in the code it would still be `import { Entity } from "typeorm"` instead of `import { Entity } from "typeorm-browser"`. Is this a welcome change?

### CODE REVIEW

**Comment by pleerock** [comment]
I thought it is already `import { Entity } from "typeorm"`, isn't it? [See here](https://github.com/typeorm/browser-example/tree/master/src).

**Comment by daniel-lang** [comment]
It is right now, but this PR would change that so that it would be `import { Entity } from "typeorm-browser"` which would line up with the package name.

**Comment by pleerock** [comment]
No, I would totally like to avoid it.

**Comment by daniel-lang** [comment]
Okay so it should stay `import { Entity } from "typeorm"` for systemjs?

**Comment by pleerock** [comment]
Yes I would like it to stay consistent everywhere. Plus it allows to reuse models between backend and frontend (not something usual, but anyway nice to have feature)

**Comment by daniel-lang** [comment]
Okay I can change it back for the systemjs version but webpack uses the folder name of the package so there it will always be `import { Entity } from "typeorm-browser"`

**Comment by pleerock** [comment]
Thats a problem as well. I don't really like it. Can we change it somehow?

**Comment by daniel-lang** [comment]
> Plus it allows to reuse models between backend and frontend (not something usual, but anyway nice to have feature)
Not sure if that is possible since the PlatformTools are the BrowserPlatformTools in the `typeorm-browser` package

**Comment by daniel-lang** [comment]
> Can we change it somehow?

As far as I know, it looks at the folder name in `node_modules` which is `typeorm-browser`

**Comment by pleerock** [comment]
Maybe some webpack option? Probably something like `map` ?

**Comment by daniel-lang** [comment]
Another option would be to include a browser folder with the normal package and do `import { Entity } from "typeorm/browser"`. Not sure if that's any better and would even work.

**Comment by pleerock** [comment]
> Not sure if that is possible since the PlatformTools are the BrowserPlatformTools in the typeorm-browser package

No, for example if you have a backend with `User` entity and lets say you have a frontend where you use `User` model as well. You can share such entities between frontend and backend, no matter what is inside typeorm package, because all what is used are decorators from "typeorm" namespace

**Comment by pleerock** [comment]
I think its possible to setup webpack, can you please research this question?

**Comment by daniel-lang** [comment]
So it is possible with two modifications
1. for the typescript compiler by adding (tsconfig.json)
```
"baseUrl": ".",
"paths": {
    "typeorm": ["node_modules/typeorm-browser"]
 }
```

2. for webpack (package.json)
```
"browser": {
    "typeorm": "typeorm-browser"
}
```

After that I can write `import { Entity } from "typeorm-browser"` or `import { Entity } from "typeorm"`, since both will work

**Comment by daniel-lang** [comment]
The same changes to `tsconfig.json` have to be done for systemjs as well since the typescript compiler only looks at the folder name

**Comment by pleerock** [comment]
> import { Entity } from "typeorm-browser" or import { Entity } from "typeorm"

I don't think its a good idea to use or even give opportunity to use both ways. We need to keep only one way (preferable second as I told). What step is required to do only `import { Entity } from "typeorm"`? Is it possible to configure only webpack and avoid configuring tsconfig?

**Comment by daniel-lang** [comment]
One way would be to create a factory which loads the right PlatformTools class depending on config or even driver. Than everything could work with one package and the  `import { Entity } from "typeorm"` syntax

**Comment by daniel-lang** [comment]
Not sure, if that would work for the compiler

**Comment by daniel-lang** [comment]
> Is it possible to configure only webpack and avoid configuring tsconfig?

No, since no matter which loader is used (webpack, systemjs or something completely different) the typescript files have to be transpiled to javascript and therefore tsconfig has to be configured so it knows where to look for the package

**Comment by pleerock** [comment]
So what is the conclusion on how it shall work? As I understood we cannot easily make user to use `import { Entity } from "typeorm"` imports. Thus users must use `import { Entity } from "typeorm-browser"` syntax. If for some reason they would want to use `import { Entity } from "typeorm"` syntax instead, they configure their webpack/systemjs and tsconfig. Right?

**Comment by daniel-lang** [comment]
No, I found a way to use `import { Entity } from "typeorm"` everwhere and only have one package for browser and Node.js. I'm going to update the PR in a second

**Comment by daniel-lang** [comment]
So the conclusion is
* use `import { Entity } from "typeorm"` everywhere
* use one package `typeorm` for node and browser which works by including both versions in the same package
  * drawback: the package gets bigger and has a lot of duplicate code
  * advantage: one universal import syntax, easier to maintain
  * webpack looks at the `browser` tag in `package.json` and uses that path if it exists so when using typeorm with webpack it automatically chooses the right version with any config by the user

**Comment by pleerock** [comment]
Solution looks good, are you sure this change does not affect anything in both nodejs and browser usages? Is compiler good in both cases?

**Comment by pleerock** [comment]
Would be great if you update browser example (also we need to create both cordova and ionic example repositories in typeorm organization)

**Comment by daniel-lang** [comment]
I tested the ionic app (webpack) and the modified browser example (systemjs) with this solution and both versions compile and run with no problem. Other than the automated tests, I didn't test the nodejs module but that should not be affected by this.
As soon as a working version is out I will create a PR for the browser example. It is ready but for now I waited for a working package.
How would you handle the cordova and ionic example? Should I create them and you reupload them to the organisation so I can keep them up to date by creating PRs for them?

**Comment by pleerock** [comment]
> How would you handle the cordova and ionic example? Should I create them and you reupload them to the organisation so I can keep them up to date by creating PRs for them?

I think if you create repos we can move them to typeorm organization, even if no we'll figure out something. We probably need two repositories: "ionic-example" and "cordova-example". Both must follow same code style as "browser-example" and contain a very simple and minimal code for users to understand and work with.

If you are planning to continue active contribution on typeorm I'll add you to organization and you'll be able to create repositories on your own, just let me know.

**Comment by pleerock** [comment]
I published a new `0.1.0-alpha.42` version with your changes

**Comment by daniel-lang** [comment]
Thanks!

I can definitely create example repos. The one for cordova already exists and just needs to be updated. And for ionic I can use the app I'm working on as a template.
As of right now I going to continue contributing to typeorm, at least to the browser specific part, maybe also to the rest if I have to time.

**Pull request merged**
