### PR TITLE
fix: improve sql.js v1.0 support in browser environment

### LINKED ISSUE #4291: Cannot read property 'Database' of undefined
**Issue type:**

[x] question

**Database system/driver:**

[ x ] `sqljs`

**TypeORM version:**

[ x ] `@next`

**Steps to reproduce or a small repository showing the problem:**

```js
createConnection({
  type: "sqljs",
  location: "test", 
  autoSave: true,
  entities: [
      User
  ],
  logging: ['query', 'schema'],
  synchronize: true
})
```

image

### PR DESCRIPTION
**Pull request by michaelbromley**
Fixes #4291 and also adds some more documentation on how to use sql.js in the browser.

### CODE REVIEW

**Comment by vlapo** [comment]
Did you test your fix locally? 
Also want to ask you. Do you have experience with running browser (non GUI) tests in travis or circle ci?

**Comment by michaelbromley** [comment]
Yes, I did test it locally. Here is a very simple repo you can also use to verify it: https://github.com/michaelbromley/typeorm-4291-demo

Yes, I have a bit of experience running browser tests on Travis. They are Angular projects and I use Karma & Jasmine to run them on headless Chrome.

**Comment by vlapo** [comment]
Do you have some proposal how to simple test typeorm in browser? Just asking in case you are interest in contributing :)

**Comment by michaelbromley** [comment]
I did have a quick look at the test setup when I was making my PR, but I'm not familiar with mocha/chai. I'd need to spend a bit more time reading up on the best way to do it with those tools. I think it makes sense not to introduce e.g. karma & jasmine just because I know them already.

Right now I've not got a whole lot of time to dedicate, but I'd certainly be interested in contributing more in the near future.

**Comment by pleerock** [comment]
Thank you guys!

**Comment by pleerock** [comment]
damn I forgot to squash and merge it, thus reverted this change. @michaelbromley can you please open PR again. sorry

**Comment by michaelbromley** [comment]
@pleerock sorry, I'm struggling a bit to figure out how to open a PR again with the GitHub UI. When I try to create a new pull request from the branch in which these changes reside, it says there is nothing to compare:

typeorm-gh-pr

any idea how to proceed?

**Comment by pleerock** [comment]
damn it shouldn't be so complicated @github

**Comment by Mehdiway** [comment]
Did you guys merge the changes on master ? Because I can't find them

**Comment by domschmidt** [comment]
@haggholm you merged only the documentation PR? =) what about the code changes? highly required changes are missing :/

**Comment by jjhbw** [comment]
I would like to add to @domschmidt 's comment that the latest `1.2.1` release of `sql.js` doesnt seem to work with TypeORM `0.2.24`. It fails when TypeORM tries to dynamically `require` `sql.js`.

I'm using webpack by the way, with the following overrides:

```javascript
    // Typeorm + SQL.js needs to be packaged with webpack to work in a browser-like environment
    // See https://github.com/typeorm/typeorm/pull/4306/files
    addWebpackPlugin(
        new webpack.ProvidePlugin({
            'window.SQL': 'sql.js'
        })
    ),
    addWebpackPlugin(new CopyPlugin([{ from: 'node_modules/sql.js/dist/sql-wasm.wasm' }])),
```

**Comment by djflex68** [comment]
Hasn't this fix been pushed on master ? I can't find the changes anywhere

**Pull request merged**
