### PR TITLE
fixed: default orderby

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by pleerock** [comment]
Hi and thank you for your fix! Would be great to have a test that will check this functionality, to prevent this functionality break in the future.

**Comment by taoqf** [comment]
@pleerock ,Actually I am not quite familiar with this testing system yet.
A test like [sample30-default-order-by](https://github.com/typeorm/typeorm/tree/master/sample/sample30-default-order-by) will be proper.

**Comment by pleerock** [comment]
` sample30-default-order-by` is a sample, its not a `test`. For tests refer `test` directory. Its easy to write test for this issue, just take a look how other tests are implemented.

**Comment by taoqf** [comment]
I will close this issue because it will resolve all the problems default order causes.

**Comment by pleerock** [comment]
what do you mean? Why did you close it?

**Comment by taoqf** [comment]
I will try to fix this and add test later.

**Pull request closed without merging**
