### PR TITLE
@AbstractEntity missing in documenation.

### PR DESCRIPTION
**Pull request by puttputt**
I'm not sure where you want the updated documentation but I noticed this missing in the docs.

### CODE REVIEW

**Comment by pleerock** [comment]
This is deprecated decorator, and its not required to use this decorator on inherited entities anymore - you can inherit any class you want and parent class will contain all columns and relations from childs

**Comment by puttputt** [comment]
Really? I am using 0.0.11 and this wasn't the case. Or is it fixed in upcoming versions?

**Comment by puttputt** [comment]
Oh. Nevermind I see the 0.1 changelog. Thanks.

**Comment by pleerock** [comment]
I recommend you to upgrade to 0.1.0

**Pull request closed without merging**
