### PR TITLE
Fix issue-9075

### LINKED ISSUE #9075: ESM module: "Could not find a declaration file for module 'typeorm'" (0.3.6)
## Issue Description

A minimal ESM module with only TypeORM does not compile.

### Expected Behavior

The project should compile without error.

### Actual Behavior

```
$ yarn build
yarn run v1.22.18
warning package.json: No license field
$ tsc
src/index.ts:1:17 - error TS7016: Could not find a declaration file for module 'typeorm'. '/home/arsleust/perso/tmp/esm-module-ts-typeorm/node_modules/typeorm/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/typeorm` if it exists or add a new declaration (.d.ts) file containing `declare module 'typeorm';`

1 import orm from "typeorm"
                  ~~~~~~~~~


Found 1 error in src/index.ts:1

error Command failed with exit code 2.
```

```
// include the output in code tags like these!
```

### Steps to Reproduce

`package.json`
```json
{
  "name": "mypackage",
  "type": "module",
  "scripts": {
    "build": "tsc"
  },
  "devDependencies": {
    "typescript": "^4.8.0-dev.20220605"
  },
  "dependencies": {
    "typeorm": "^0.3.6"
  }
}
```

`tsconfig.json`
```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

`src/index.ts`
```ts
import orm from "typeorm"

```

Run `yarn build`

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Node.js version     | 16.14.2  | 
| Typescript version  | 4.8.0-dev.20220605  | 
| TypeORM version     | 0.3.6  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by DemianD**
### Description of change

Fixes issue #9075

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #9075`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
Thank you!

**Comment by AviVahl** [comment]
@pleerock  any chance for a quick bug fix release with this change? was going to PR this change, and noticed it already landed `master`...

**Comment by aminroosta** [comment]
Thanks for the fix, would it be possible to release this as a minor version?

**Comment by pleerock** [comment]
I'll release a new version by the end of this week.

**Pull request merged**
