### PR TITLE
Update ts-node dep version in init command

### LINKED ISSUE #8820: package.json generated by typeorm init has wrong version of ts-node
## Issue Description

It seems like `typeorm init` produces a `package.json` with ts-node version 10.4.0:
```
$ jq .devDependencies package.json
{
  "ts-node": "10.4.0",
  "@types/node": "^16.11.10",
  "typescript": "4.5.2"
}
```

However, typeorm itself has a peer-dependency for `^10.7.0`:
```
$ jq .peerDependencies /home/michael/.nvm/versions/node/v16.14.2/lib/node_modules/typeorm/package.json
{
  "@sap/hana-client": "^2.11.14",
  "better-sqlite3": "^7.1.2",
  "hdb-pool": "^0.1.6",
  "ioredis": "^4.28.3",
  "mongodb": "^3.6.0",
  "mssql": "^6.3.1",
  "mysql2": "^2.2.5",
  "oracledb": "^5.1.0",
  "pg": "^8.5.1",
  "pg-native": "^3.0.0",
  "pg-query-stream": "^4.0.0",
  "redis": "^3.1.1",
  "sql.js": "^1.4.0",
  "sqlite3": "^5.0.2",
  "ts-node": "^10.7.0",
  "typeorm-aurora-data-api-driver": "^2.0.0"
}
```

### Expected Behavior

running `typeorm init` produces a project skeleton and installs dependencies

### Actual Behavior

```
$ typeorm init
Project created inside current directory.
Please wait, installing dependencies...
Error during project initialization:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: typeorm@0.3.4
npm ERR! Found: ts-node@10.4.0
npm ERR! node_modules/ts-node
npm ERR!   dev ts-node@"10.4.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ts-node@"^10.7.0" from typeorm@0.3.4
npm ERR! node_modules/typeorm
npm ERR!   typeorm@"0.3.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: ts-node@10.7.0
npm ERR! node_modules/ts-node
npm ERR!   peerOptional ts-node@"^10.7.0" from typeorm@0.3.4
npm ERR!   node_modules/typeorm
npm ERR!     typeorm@"0.3.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/michael/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2022-03-28T11_06_55_393Z-debug-0.log

```

### Steps to Reproduce

1. install typeorm globally with `npm install -g typeorm`
2. in an empty directory, run `typeorm init`

### Workaround

Edit the generated `package.json` changing 
```
      "ts-node": "10.4.0",
```

to

```
      "ts-node": "10.7.0",
```

then manually run `npm install`
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Ubuntu 20.04.4 running in WSL 2 on Windows 10 |
| Node.js version     | 16.14.2  | 
| Typescript version  | none (didn't get as far as installing TS)  | 
| TypeORM version     | 0.3.4  | 

### Additional Context

Note that I'm running in WSL - I don't think that's relevant to the issue though.

### Relevant Database Driver(s)

N/A

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by mishagale**
Version needs to be compatible with the peerDependency version in typeorm's own package.json

### Description of change

Fixes #8820

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
is it finished?

**Comment by mishagale** [comment]
> is it finished?

The actual fix is a 1-character change, and yes, I finished that. Where I ran into problems was writing a test-case, which became pretty complicated. I've pushed the test as it is so far, but I feel it may be overcomplicated, and involved making a change to the actual init command code to make it testable, which feels like an excessive amount of added complexity for such a small fix.

**Comment by pleerock** [comment]
oh no need to add test in this case

**Comment by pleerock** [comment]
okay I just pushed the same fix, because I need this change in order to release new version. Thank you for your efforts.

**Pull request closed without merging**
