### PR TITLE
fix(aurora): fix ignore statement in aurora-data-api

### PR DESCRIPTION
**Pull request by ArsenyYankovsky**

### CODE REVIEW

**Comment by silentroach** [comment]
please squash your commits. 5 commits just to change 2 lines of code is too much.

**Comment by ArsenyYankovsky** [comment]
Will do when I have a bit more time. Maybe you could squash and merge it please?

**Comment by silentroach** [comment]
no, I can't, i'm just a contributor, like you

**Comment by ArsenyYankovsky** [comment]
Squashed the commits. I'm not sure if that was that necessary as the reviewer can squash and commit with just a click of a button but I agree it looks nicer this way.

**Pull request closed without merging**
