### PR TITLE
Uses defineProperty so that __has_ and __promise_ variables are not enumerable

### PR DESCRIPTION
**Pull request by joelgallant**
Seeing these properties when JSON.stringifying and like functions is jarring, and as far as I can tell there's no need for these properties to be enumerable

### CODE REVIEW

**Comment by pleerock** [comment]
Hey, thanks for the contribution.

Can you please take a look why tests are failing?
Also can you please add test for the change you made?

**Comment by joelgallant** [comment]
I can't really tell what test is failing from the logs. I'll try and add a test for this change, though I'm unfamiliar with the setup.

**Comment by joelgallant** [comment]
As far as I can tell, `test/functional/relations/lazy-relations/basic-lazy-relation` should act as a regression test on this change, since it doesn't introduce any changed or new behavior.

Running the tests locally works (though I like the docs for dev setup could be improved - I'll try and follow up with a different PR for that).

**Comment by amaranth** [comment]
You've made `resolveIndex` read-only but the setter tries to write to it. Making that writable again makes the tests pass.

```diff
diff --git a/src/query-builder/RelationLoader.ts b/src/query-builder/RelationLoader.ts
index da4705bf..9abadbe7 100644
--- a/src/query-builder/RelationLoader.ts
+++ b/src/query-builder/RelationLoader.ts
@@ -206,7 +206,10 @@ export class RelationLoader {
                         this[dataIndex] = result;

                         // ensures enumerable: false
-                        Object.defineProperty(this, resolveIndex, { value: true });
+                        Object.defineProperty(this, resolveIndex, {
+                            value: true,
+                            writable: true,
+                        });

                         delete this[promiseIndex];
                         return this[dataIndex];

```

**Comment by joelgallant** [comment]
Thanks!

**Comment by pleerock** [comment]
Can you please add test as well? Because without test next time somebody makes a change this functionality can break without tests.

**Comment by joelgallant** [comment]
You got it. Added a test that ensures the properties are not enumerable, which would make reverting this break the test.

**Comment by pleerock** [comment]
Thank you very much!

**Comment by pleerock** [comment]
@joelgallant can you please take a look at #3576 ? This PR definitely broke current behaviour. If we won't hotfix it soon I'll have to revert this PR.

**Comment by joelgallant** [comment]
I'll take a look at this sure

**Comment by pinguinjkeke** [comment]
Any news here?

**Pull request merged**
