### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by imnotjames**
This bumps the following dependencies (ignoring `typescript` and `tslib`):

| Name | Is Dev Only? | Old Version | New Version |
| --- | --- | --- | --- |
@types/chai | yes | ^4.1.2 | ^4.2.0
@types/chai-as-promised | yes | 7.1.0 | ^7.1.3
@types/debug | yes | ^4.1.2 | ^4.1.5
@types/mocha | yes | ^5.2.6 | ^8.0.3
@types/node | yes | ^9.6.0 | ^14.6.4
@types/rimraf | yes | ^2.0.2 | ^3.0.0
@types/sinon | yes | ^7.0.8 | ^9.0.5
@types/source-map-support | yes | ^0.4.2 | ^0.5.1
@types/yargs | yes | ^12.0.9 | ^15.0.4
@typescript-eslint/eslint-plugin | yes | ^3.7.0 | ^4.1.0
@typescript-eslint/parser | yes | ^3.7.0 | ^4.1.0
better-sqlite3 | yes | ^7.0.1 | ^7.1.0
conventional-changelog-angular | yes | ^5.0.3 | ^5.0.11
conventional-changelog-cli | yes | ^2.0.21 | ^2.1.0
del | yes | ^3.0.0 | ^5.1.0
eslint | yes | ^7.5.0 | ^7.8.1
gulp | yes | ^4.0.0 | ^4.0.2
gulp-mocha | yes | ^6.0.0 | ^7.0.2
gulp-rename | yes | ^1.2.2 | ^2.0.0
gulp-shell | yes | ^0.6.5 | ^0.8.0
gulp-typescript | yes | ^5.0.0 | ^6.0.0-alpha.1
husky | yes | ^1.3.1 | ^4.2.3
lint-staged | yes | ^8.1.4 | ^10.0.8
mocha | yes | ^6.1.4 | ^8.1.3
mongodb | yes | ^3.1.13 | ^3.5.4
mssql | yes | ^4.3.2 | ^6.1.0
mysql | yes | ^2.15.0 | ^2.18.1
mysql2 | yes | ^1.6.5 | ^2.1.0
redis | yes | ^2.8.0 | ^3.0.2
rimraf | yes | ^2.6.3 | ^3.0.2
sinon | yes | ^7.2.5 | ^9.0.0
sinon-chai | yes | ^3.3.0 | ^3.5.0
source-map-support | yes | ^0.5.10 | ^0.5.16
sql.js | yes | ^1.0.0 | ^1.3.0
sqlite3 | yes | ^4.0.9 | ^5.0.0
ts-node | yes | ^8.0.2 | ^9.0.0
typeorm-aurora-data-api-driver | yes | ^1.3.0 | ^1.4.0
buffer | no | ^5.1.0 | ^5.5.0
chalk | no | ^2.4.2 | ^4.1.0
cli-highlight | no | ^2.0.0 | ^2.1.4
glob | no | ^7.1.2 | ^7.1.6
js-yaml | no | ^3.13.1 | ^3.14.0
mkdirp | no | ^1.0.3 | ^1.0.4
tslib | no | ^1.9.0 | ^1.13.0
xml2js | no | ^0.4.17 | ^0.4.23
yargs | no | ^13.2.1 | ^16.0.3

Also, some typing changes had to be made ~~as well as a change to how `sql.js` handles undefined values as bound parameters~~.

### CODE REVIEW

**Comment by imnotjames** [comment]
This was accomplished via `npm outdated` and upgrading as needed.

**Comment by imnotjames** [comment]
Should get #6698 merged in first

**Comment by pleerock** [comment]
Thank you! There is a conflict however.

**Comment by imnotjames** [comment]
Rebase against master so #6698 is included - drops the need for the sqljs commit.

**Comment by pleerock** [comment]
thank you!

**Pull request merged**
