### PR TITLE
Update transaction interface of Connection class

### LINKED ISSUE #3363: Isolation Level in `transaction()` from `Connection`
**Issue type:**

[x] question
[ ] bug report
[x] feature request (possible?)
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

In documentation we have a parameter to define isolation level from `getManager()`:
 
```typescript
await getManager().transaction("SERIALIZABLE", transactionalEntityManager => {

});
```

But, if we try to do the same thing from `Connection` class, there isn't such definition, only the callback: 

```typescript
transaction(runInTransaction: (entityManager: EntityManager) => Promise<any>): Promise<any>;
```

I'm using Typeorm in a NestJs, so `Connection` class comes from Injection. If i use `getManager()`, it'll get the same "session" in Connection class injected?

### PR DESCRIPTION
**Pull request by victorschinaider**
should resolve #3363

### CODE REVIEW

**Comment by pleerock** [comment]
Conflicts..

**Comment by victorschinaider** [comment]
sorry. I'll recreate the pull request soon.

**Comment by pleerock** [comment]
would be really cool to have tests for those methods :)

**Comment by victorschinaider** [comment]
Thanks for feedback, i will try to implement. @pleerock , there is a way to execute only some tests? It spends too much time to execute all tests of typeorm, and see result. There is a way to execute only one file test, for example?

**Comment by pleerock** [comment]
just add `.only` to `it`, e.g. `it.only("your test", ...)`

**Comment by victorschinaider** [comment]
@pleerock , i think i just did what you asked. Could you review? And more, i noticed that tests are only being executed in first "not skip" connection from the configs (that is, it is running only once), and is not just  onoly mine tests that are like this, is it to work like that?

**Comment by pleerock** [comment]
PR looks fine, I'll merge it. However I didn't get what you mean

>  i noticed that tests are only being executed in first "not skip" connection from the configs (that is, it is running only once), and is not just onoly mine tests that are like this, is it to work like that?

**Comment by victorschinaider** [comment]
> PR looks fine, I'll merge it. However I didn't get what you mean
> 
> > i noticed that tests are only being executed in first "not skip" connection from the configs (that is, it is running only once), and is not just onoly mine tests that are like this, is it to work like that?

Example:

If i have my `ormconfig.json` like this: 

```json
[
  {
    "skip": false,
    "name": "mysql",
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "root",
    "password": "admin",
    "database": "test",
    "logging": false
  },
  {
    "skip": false,
    "name": "mariadb",
    "type": "mariadb",
    "host": "localhost",
    "port": 3307,
    "username": "root",
    "password": "admin",
    "database": "test",
    "logging": false
  },
  {
    "skip": false,
    "name": "sqlite",
    "type": "sqlite",
    "database": "temp/sqlitedb.db",
    "logging": false
  },
  {
    "skip": false,
    "name": "postgres",
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "test",
    "password": "test",
    "database": "test",
    "logging": false
  },
  {
    "skip": true,
    "name": "mssql",
    "type": "mssql",
    "host": "localhost",
    "username": "sa",
    "password": "Admin12345",
    "database": "tempdb",
    "logging": false
  },
  {
    "skip": true,
    "name": "oracle",
    "type": "oracle",
    "host": "localhost",
    "username": "system",
    "password": "oracle",
    "port": 1521,
    "sid": "xe.oracle.docker",
    "logging": false
  },
  {
    "skip": false,
    "disabledIfNotEnabledImplicitly": true,
    "name": "mongodb",
    "type": "mongodb",
    "database": "test",
    "logging": false,
    "useNewUrlParser": true
  }
]
```
And a test like this:

```typescript
 it("test example", () => Promise.all(connections.map(async connection => {
   console.log('test');
 })));
```

The result is to show `test` 5 times, because i have 5 connections with `skip=false`. But it isn't happening. To me, it just show `test` one time, and only for first connection (for `mysql` in this case)

**Comment by victorschinaider** [comment]
Ahh, ok. Later, i'll fix this. Thank you!

**Pull request merged**
