### PR TITLE
10216#fix/inflight veracode issue

### PR DESCRIPTION
**Pull request by Tringapps-Dharshan**
I'm facing Inflight as a vulnerability in TypeORM.

Description of change
------------------------
I cloned and updated the Glob version to 9.0.0. Now there is no dependency Inflight under Glob under TypeORM.

#10245 Pull-Request Checklist 

- [Y] Code is up-to-date with the `master` branch
- [Y] `npm run format` to apply prettier formatting
- [Y] `npm run test` passes with this change
- [Y] This pull request links relevant issues as `Fixes #10245`
- [N] There are new or updated unit tests validating the change
- [Y] Documentation has been updated to reflect this change
- [Y] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by FraneCaleta — APPROVED** [review]

**Comment by retamozo** [comment]
Hey, @AlexMesser /  @pleerock would you mind reviewing/merging this little one? 🙏

**Review by hinogi — CHANGES_REQUESTED** [review]
I am not sure if the changelog is needed here.
Also, the package-lock.json got polluted by this change with changes to other packages across the board.
I really have a problem with major version updates in there by dependencies of dependencies.

**Comment by Tringapps-Dharshan** [comment]
I am still encountering an inflight vulnerability in the Veracode platforms. Could you please merge this pull request to address the Veracode issues?

**Comment by iJoyCode** [comment]
+1

**Comment by kroshner** [comment]
+1

**Comment by pleerock** [comment]
I did a direct push to the latest glob version to the master branch, since this PR contains redundant changes (CHANGELOG)

**Comment by Tringapps-Dharshan** [comment]
> I did a direct push to the latest glob version to the master branch, since this PR contains redundant changes (CHANGELOG)

@pleerock Still updated glob version is not reflected in master branch package.json

**Pull request closed without merging**
