### PR TITLE
fix: lookbehind isn't supported in web / mobile environments

### LINKED ISSUE #7026: QueryBuilder broken on web - Invalid regular expression: invalid group specifier name
## Issue Description
The QueryBuilder is broken in the new 0.2.29 release due to this change: https://github.com/typeorm/typeorm/pull/4760
Regex lookbehinds are not supported in on a lot of web environments, a fallback should be implemented.
This affects any driver that uses JavascriptCore (Safari, React Native, ...)

### Expected Behavior

I'd expect QueryBuilder to work

### Actual Behavior

QueryBuilder crashes with `Invalid regular expression: invalid group specifier name`

### Steps to Reproduce

I would add an reproducible example, however, I feel the issue is clear enough without?

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     React Native, Android     |
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.29 | 

### Additional Context

Relevant:
- https://bugs.webkit.org/show_bug.cgi?id=174931
- https://stackoverflow.com/questions/641407/javascript-negative-lookbehind-equivalent

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [x] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### LINKED ISSUE #7157: typeorm 0.2.29 SyntaxError  Invalid regular expression Bug
更新到0.2.29无论是插入还是保存都报这个错误， 版本用回0.2.19就不会报这个错. 代码是typescript。 是不是没有用new RegExp
 SyntaxError: Invalid regular expression: /(?<=[ =(]|^.{0})RoomModel\.(id|room_id|creator_user_id|game_type|name|create_time|update_time|room_status|room_rule|room_no)(?=[ =),]|.{0}$)/: Invalid group=undefined

@Entity("room")
export class RoomModel {
    @PrimaryGeneratedColumn()
    id: number;
    @Column('bigint')
    @Index("room_id_index")
    room_id : string = "";
    @Column('bigint')
    @Index()
    creator_user_id : string = "";
    @Column("integer")
    @Index()
    game_type: proto.GameType = 0;
    @Column("varchar", {length: 50})
    name : string = ""
    @CreateDateColumn()
    create_time : Date;
    @UpdateDateColumn()
    update_time : Date;
    @Column("integer")
    room_status: proto.RoomStatus = proto.RoomStatus.Idle;
    @Column("integer")
    room_rule: number; 
    @Column("bigint")
    @Index("room_no_index")
    room_no: string = "";
}

### PR DESCRIPTION
**Pull request by pleerock**
This PR changes the code introduced in #4760 and #7042.
Users have problems with the changes in these PRs and React Native driver.

Closes #7026
Closes #7157

### CODE REVIEW

**Comment by ldiqual** [comment]
The changes being reverted were a huge performance boost for us. I'm wondering whether doing a feature check would be the best of both world. Is there a way to check whether the environment supports look-behind regexes? https://caniuse.com/js-regexp-lookbehind

**Comment by pleerock** [comment]
Okay, instead of reverting, I made old code to work only on react-native platform.

**Comment by Vluf** [comment]
Do note that the fallback methods doesn't strictly solve everything. Lookbehinds are not supported on any JavaScriptCore product, i.e. Safari.

**Comment by mohd-akram** [comment]
I'm taking a look at this issue, and should have a proper fix soon.

**Comment by mohd-akram** [comment]
Made a PR with a simple fix at #7270.

**Comment by pleerock** [comment]
closing in favor of #7270

**Pull request closed without merging**
