### PR TITLE
feat: add caching to raw SQL queries for PostgreSQL

### LINKED ISSUE #8958: Caching of raw queries
## Feature Description

Introduce caching of raw sql queries.

### The Problem

The are a lot of cases when QueryBuilder is not enough. For example when you write nested queries (CTE) https://www.postgresql.org/docs/current/queries-with.html  it's very problematic to say the least to write those queries in QueryBuilder. When you use them heavily in your developed app having ability to do a 0(1) lookup in cache is a must have. 

### The Solution

I want a solution to write queries like this 

const sql = '
      WITH regional_sales AS (
          SELECT region, SUM(amount) AS total_sales
          FROM orders
          GROUP BY region
      ), top_regions AS (
          SELECT region
          FROM regional_sales
          WHERE total_sales > (SELECT SUM(total_sales)/10 FROM regional_sales)
      )
      SELECT region,
             product,
             SUM(quantity) AS product_units,
             SUM(amount) AS product_sales
      FROM orders
      WHERE region IN (SELECT region FROM top_regions)
      GROUP BY region, product;';

const data = await conn.manager.query(sql, {cache: 60*60_000});

I expect to store query as a key in cache provider (my focus would be redis) and data as value of that key (the same way it's done now for QueryBuilder). 

In my example I would expect data to be cached for 60 minutes.

### Additional Context

The feature was discussed here - https://github.com/typeorm/typeorm/issues/2105 a while ago. 

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 -  :heavy_multiplication_x: Yes, I have the time, and I know how to start.
 - :white_check_mark: Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by pavelkalin**
### Description of change

add caching to raw SQL queries

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run format` to apply prettier formatting
- [X] `npm run test` passes with this change
- [X] This pull request links relevant issues as `Fixes #8958`
- [X] There are new or updated unit tests validating the change
- [X] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pavelkalin** [comment]
My issue is 8958 and PR is 8985. Lovely

**Comment by guillenotfound** [comment]
Would love to see this merged ❤️

**Comment by pleerock** [comment]
I think it's better to implement this feature as part of QueryBuilder. We can add ability to query builder to set a complete SQL, set cache options and execute query.

**Comment by pleerock** [comment]
Closing as there is no answer from OP. Please feel free to reopen.

**Pull request closed without merging**
