### PR TITLE
Added comments to commands, common folder files 

### PR DESCRIPTION
**Pull request by gmmkmtgk**
### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

I have started reading the codebase, I felt several files are difficult to understand for beginners hence adding comments to such kind of files.

Added comments to common folder files DeepPartial.ts and EntityTarget.ts which is used at many places.

### CODE REVIEW

**Comment by gmmkmtgk** [comment]
Added comments to command folder files also

**Comment by gmmkmtgk** [comment]
Adding comments to decorator folder too

**Comment by codeprokeshav** [comment]
Looks good has not been merged yet?

**Comment by pleerock** [comment]
Thank you for contribution, however most of the comments are too obvious, so I find 95% of them redundant. I'll close this PR.

**Pull request closed without merging**
