### PR TITLE
feat: backport ilike from next

### PR DESCRIPTION
**Pull request by imnotjames**
the next branch has support for ilike and this backports
the FindOperator into the main branch

### CODE REVIEW

**Comment by imnotjames** [comment]
ILike is not supported in oracle.  Need to disable that test for oracle

**Comment by imnotjames** [comment]
HMM, one of the mainline drivers don't support it either but I'm not sure which one.  I'll have to check locally and then publish a change to the tests to disable.

**Comment by pleerock** [comment]
> HMM, one of the mainline drivers don't support it either but I'm not sure which one.

It would be great I think to quickly understand from CI what exact driver failed, to improve our developer experience.

**Comment by imnotjames** [comment]
Definitely - a big reason why it's difficult is because of how we've structured our tests, with the `connections` promises.

**Comment by pleerock** [comment]
Thank you!

**Pull request merged**
