### PR TITLE
Remove links to defunct Vesper project

### PR DESCRIPTION
**Pull request by stim371**
### Description of change

Fixes https://github.com/typeorm/typeorm/issues/11178

The Vesper project repo has not been updated in 6 years and the website is dead.

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by albasyir — APPROVED** [review]
good catch!

**Review by michaelbromley — APPROVED** [review]

**Comment by kasir-barati** [comment]
Just wondering why we did not add https://github.com/TriPSs/nestjs-query as an alternative since it is in active development and people might benefit from getting to know that we have these projects too mix TypeORM and GraphQL easier and faster. Any comment?

**Comment by kasir-barati** [comment]
Lemme know if I am missing something.

**Comment by stim371** [comment]
@kasir-barati I only wanted to remove the link to the defunct project so people wouldn't try to use it in the future. I didn't want to add links to projects that I don't have time to evaluate right now.

If you want to submit a PR to add suggested graphQL packages, I think that'd be welcome, but they're also findable on npm.

**Pull request merged**
