### PR TITLE
Issues #1147

### PR DESCRIPTION
**Pull request by brendan-roche**
This issue was closed, but this fix was never merged to master. 
Also would be nice to get merged back to `next` soon too please

### CODE REVIEW

**Comment by pleerock** [comment]
typescript compilation failed

**Comment by brendan-roche** [comment]
Yeah saw this after I pushed. I thought it was simple fix but fails because this `query` parameter is passed through to the mongo driver on collection.find - MongoQueryRunner.ts:102, which does not accept a string for an sql query.

http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#find

So an option to get around this would be to ignore the string and pass an empty object instead, as mongo is not a sql database. 

Would you be happy with this solution?

**Comment by pleerock** [comment]
yeah looks like we have no option if we want to add a string condition

**Comment by brendan-roche** [comment]
@pleerock ready to review again

**Comment by pleerock** [comment]
Thank you

**Pull request merged**
