### PR TITLE
fix: allow where IsNull for ManyToOne relations

### PR DESCRIPTION
**Pull request by pixtron**
Fixes: #8890

### Description of change

Allows to query ManyToOne relations for records that do not have any relation (IS NULL). 

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pixtron** [comment]
@jczacharia [this workaround](https://github.com/typeorm/typeorm/issues/8890#issuecomment-1194519752) might work for you.

**Comment by pleerock** [comment]
Thank you for contribution! 🎉

**Comment by LoneRifle** [comment]
Hello @pixtron @pleerock - this may have introduced a regression where selecting for OneToMany relations are now disallowed. Is this intended, and if not, should a PR be submitted so that for `relation.isOneToMany` we do not throw the error?

**Comment by pixtron** [comment]
@LoneRifle i just removed the [throw you are mentioning](https://github.com/typeorm/typeorm/blob/f5b93c14b5efa1a55aed0211a4757af1b3d6e66b/src/query-builder/SelectQueryBuilder.ts#L4432-L4434) locally, it wouldn't solve your issue. 
But you are pretty close. `moreThanOrEqual` and `lessThanOrEqual` should probably be implemented [here](https://github.com/typeorm/typeorm/blob/f5b93c14b5efa1a55aed0211a4757af1b3d6e66b/src/query-builder/SelectQueryBuilder.ts#L4324-L4329) for `relation.isOneToMany`, `relation.isManyToManyOwner` and `relation.isManyToManyNotOwner`. 

I had a quick test with this change, which made `moreThanOrEqual` and `lessThanOrEqual` working for `isOneToMany` and probably will for the other relations too.

```diff
diff --git a/src/query-builder/SelectQueryBuilder.ts b/src/query-builder/SelectQueryBuilder.ts
index d3b01053f..11b5b0ea4 100644
--- a/src/query-builder/SelectQueryBuilder.ts
+++ b/src/query-builder/SelectQueryBuilder.ts
@@ -4321,12 +4321,16 @@ export class SelectQueryBuilder<Entity extends ObjectLiteral>
                     }

                     if (InstanceChecker.isFindOperator(where[key])) {
+                        const { type } = where[key];
                         if (
-                            where[key].type === "moreThan" ||
-                            where[key].type === "lessThan"
+                            type === "moreThan" ||
+                            type === "moreThanOrEqual" ||
+                            type === "lessThan" ||
+                            type === "lessThanOrEqual"
                         ) {
-                            const sqlOperator =
-                                where[key].type === "moreThan" ? ">" : "<"
+                            const baseOperator = /^moreThan/.test(type) ? ">" : "<"
+                            const sqlOperator = baseOperator + (/OrEqual$/.test(type) ? '=' : '')
+
                             // basically relation count functionality
                             const qb: QueryBuilder<any> = this.subQuery()
                             if (relation.isManyToManyOwner) {
```

Probably the best is if you open a new issue, and create a PR for that issue. The PR probably has the best chance to get merged if you thoroughly test `moreThanOrEqual` and `lessThanOrEqual` for `isOneToMany`, `isManyToManyOwner` and `isManyToManyNotOwner` relations. 

Also one could argue that the [Find operators](https://orkhan.gitbook.io/typeorm/docs/find-options#advanced-options) `Equal`, `Between` (and maybe some more?) should be supported as well for relations. But thats eventually yet another issue and PR.

**Comment by LoneRifle** [comment]
@pixtron - I got it to work, not by removing the throw, but by changing the `else` to `else if (!relation.isOneToMany)`. Also corroborated this by testing on 0.3.7 (working) and 0.3.8 (not working, contains this change), which was how I discovered this PR.

Felt pretty hacky though, so I did a more invasive change similar to yours (with `String.startsWith` and `String.endsWith` instead of regards) and verified that this other approach works just as well.

I'll see if I can find the time to submit a PR. While MoreThanOrEqual on relations matters to us, we could possibly workaround with the equivalent MoreThan expression.

**Pull request merged**
