### PR TITLE
Fix find by relation entity with compound keys

### PR DESCRIPTION
**Pull request by vlastv**
### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by imnotjames** [comment]
can you add tests that verify this behavior?

**Comment by vlastv** [comment]
I am not an expert on this language. If I have time, I will try to study other tests and write my own.

**Comment by vlastv** [comment]
@imnotjames I added test

**Comment by imnotjames** [comment]
I've grabbed the tests and ran them against the current `master` branch and they pass.  I think this PR may not be relevant any longer?

**Comment by imnotjames** [comment]
It seems like some recent refactoring of the query builder has corrected this issue!  Wonderful.  That means this PR may not be relevant any longer.

These tests are great, though - I'll make sure they get merged in.

https://github.com/typeorm/typeorm/pull/8052

**Pull request closed without merging**
