### PR TITLE
feat: add custom timestamp option in migration creation

### PR DESCRIPTION
**Pull request by carmi2214**
An option in the CLI to specify a custom timestamp when creating or generating a migration.

Closes: #8500

### Description of change

An option in the CLI to specify a custom timestamp when creating / generating a migration.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
What is the real-world usage example of this feature?

**Comment by carmi2214** [comment]
> What is the real-world usage example of this feature?

I have a script that runs `migration:generate` for multiple schemas. <br />
When I activate the script, it results with the same migration, across multiple files + rows in `migrations` table in each schema,
with a little difference - the timestamp.

It could help to have the same exact name from the beginning without changing it manually,
for the case where you need to copy your schema's content into another one (with the same `migrations` table),
or for comparing migrations' history, etc.

**Comment by pleerock** [comment]
Thank you for contribution! 🎉

**Comment by MartinHarkins** [comment]
Perfect I was just needing this !

Usecase:
Using SQLite :memory: for testing. Simple to just generate the full DB migration when the schema changes (instead of piecemeal).
Having a static timestamp will help us avoid some git conflicts/maintenance (timestamp always changes, while not being relevant to our scenario)

**Pull request merged**
