### PR TITLE
Parent entity is now loaded for joined tables as well

### PR DESCRIPTION
**Pull request by eyalhakim**
Prior to this fix, only main entity parent was loaded

### CODE REVIEW

**Comment by eyalhakim** [comment]
@pleerock last one for today

**Comment by eyalhakim** [comment]
@pleerock Hi, any chance you could look at this?

**Comment by eyalhakim** [comment]
@pleerock can you look why this build is failing?
Doesn't seem like something caused by my changes

**Comment by pleerock** [comment]
I'll close this issue since I decided to remove CTI support from typeorm functionality for now.

**Pull request closed without merging**
