### PR TITLE
fixed getCount for oracle alias case sensitivy

### PR DESCRIPTION
**Pull request by hajekj14**
Fixed getCount with Oracle case sensitivity for aliases

### CODE REVIEW

**Comment by hajekj14** [comment]
Is this solution ok for you? Or you prefered add quotas to getCount query(... as "cnt" ...) or complet differet way?

Thanks

**Comment by pleerock** [comment]
probably better to do `add quotas to getCount query(... as "cnt" ...)`. Are you able to do it?

**Comment by hajekj14** [comment]
Ok, no problem.

**Comment by hajekj14** [comment]
problem with travisCI: Cannot create a new connection named "sqlite", because connection with such name already exist and it now has an active connection session

**Comment by pleerock** [comment]
yeah simply restart the build...

**Comment by pleerock** [comment]
thanks for this awesome pr ;)

**Comment by hajekj14** [comment]
:-) no problem, it was be really complicated

Dne 2. 6. 2017 20:56 napsal uživatel "Umed Khudoiberdiev" <
notifications@github.com>:

**Pull request merged**
