### PR TITLE
resolve circular dependency when using vite

### PR DESCRIPTION
**Pull request by vorujack**
### Description of change

There is a problem when using typeorm with vite. in QueryBuilder typeorm used require which is not available in vite builded output. 

I declare a Registery for all query types and fill it when datasource created and remove all required queries.

also there are two problem when using latest version of capacitor

* In capacitorQueryRunner line 65 if query only contain one command without any space command extracted wrong and code does not correct query
* in line 84 also PRAGMA must executed with run command not query

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run format` to apply prettier formatting
- [X] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hinogi** [comment]
I would argue that probably `vite-require` would be a better option and less intrusive. Otherwise, I would opt in for an alias for `require` at the places where it is used. Ideally import syntax would be great to keep the laziness, but that would also change the public API as mentioned in other PRs from sync to async.

**Comment by hinogi** [comment]
duplication of https://github.com/typeorm/typeorm/pull/10196 I think

**Comment by vorujack** [comment]
I test `vite-require` and some other similar plugins. but they do not fix the problem. also alias for require not a good option.

as you can see in this merge there are no changing of sync call to async.

**Comment by vorujack** [comment]
I fix some other bugs than #10196 in this merge

**Comment by jbsn94** [comment]
Will this pr to be merged?, i'm also having the same problem using vite and the `vite-require` did not solve my problem.

**Comment by pleerock** [comment]
Since I already merged #10196, this PR needs to be changed to avoid conflicts with #10196

**Comment by Nickolas-** [comment]
This pull request breaks Capacitor with typeorm on iOS. 
image
Issue that pragma commands executes now as run command that cause sqlite result 100

**Comment by rkreutzer** [comment]
Same issue with result error 100 on Android. Removing PRAGMA from the CapacitorQueryRunner driver files works for me.

**Pull request merged**
