### PR TITLE
Feature: Delete orphaned rows

### PR DESCRIPTION
**Pull request by adenhertog**
Also, fix: https://github.com/typeorm/typeorm/issues/1351

This adds an additional option on one-to-many relationships where child entities are deleted, rather than having their foreign key set to null, when removed from their parent. 

Many times we have the situation where a parent entity "owns" a child. An example of this is when a `User` has a set of `RoleAssignment` in the context of permissions. When a `RoleAssignment` is removed from the user, we expect for the row to be deleted. Previously the row would remain in the database but with the `userId` column set to null, leaving an orphaned row that would clog up the table.

This fix allows for `RoleAssignment` to specify on its relationship with `User` that it should be deleted, rather than orphaned, when the relationship is removed.

By default, the original behaviour of setting the foreign key to `null` is retained.

### CODE REVIEW

**Comment by pleerock** [comment]
Im sorry but I cannot accept this PR. 

First, persistence was completely refactored in `@next`, cascade removes are not working currently in next and Im not yet sure about their design and implementation.

If you want have this feature in `@next` then its better to start discussion before implementation since this area is very sensitive and must be implemented very carefully and right design should be chosen first.

**Comment by guscastro** [comment]
I'd personally really like to have this feature in `@next`. Could we start the discussion with your concerns about the current implementation, @pleerock ?

**Comment by pleerock** [comment]
@adenhertog I see you pushed some changes, but as I told if it will be implemented it must be re-implemented against `next` branch (and all changes it has)

**Comment by adenhertog** [comment]
Hey @pleerock, I'm happy to discuss how this might fit into `@next` as for certain scenarios it fits better than setting FKs to null. 

I'm currently using `0.1.13` in production and needed this change immediately, so can close this PR without merging if you don't think it fits into `@latest`

**Comment by kirliam** [comment]
Just for your information, this is a common use-case for me as well, and it would be nice if I could have the option to tell typeorm to delete the orphan entities, since today I am required to do it manually!

**Comment by kristophjunge** [comment]
Hello Guys,

please note that i have looked on this issue from a bug perspective in #1761 and also filed a pull request against @next.

Having cascade remove working in these cases is essential. Setting the foreign key to NULL only covers a portion of the possible situations.

If cascade remove is not working it basically renders all cascade methods to be unusable. I cannot implement "insert" and "update" one way and have some extra code to fill the missing "remove" part. 

I can go only full with these features or completely without.

**Comment by adenhertog** [comment]
Closing this since master has diverged by a major version. I'd still find it very useful having this addressed in the latest release

**Comment by haroldo-ok** [comment]
I am quite surprised that one of the top JS/TS ORM's does not support orphan removal...

**Pull request closed without merging**
