### PR TITLE
feat(data-api): Introduced a new configuration option "formatOptions.…

### PR DESCRIPTION
**Pull request by ArsenyYankovsky**
### Description of change

Because the list of types supported by the Aurora Data API is limited Data API client [introduced type casts](https://github.com/jeremydaly/data-api-client#type-casting). This pull request introduces a new configuration option for the Aurora drivers called `castParameters` that enables automatic casting based on the column types. To achieve this, TypeORM will delegate the `preparePersistentValue` operation to the driver package. 

The same option will also delegate the `prepareHydratedValue` operation to unpack the Data API value types back to the TypeORM value types.

This pull request fixes existing issues for the following data types:
- [UUID](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/48) and  [#57](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/57)
- [Date/Time](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/51)
- [Enum](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/44)
- JSON

Besides fixing a bunch of existing bugs, moving this part of logic to the driver package will allow us to iterate and fix bugs in it faster as the release cycle there is shorter.

I also introduced new jobs in the driver CI workflows that test against a real server. Previously, this was tested against the local-data-api container which doesn't 100% reflect what real Data API does.

✔ A new version of the driver package for this change has already been released (2.0.0)

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run lint` passes with this change
- [X] `npm run test` passes with this change
- [X] This pull request links relevant issues as `Fixes #0000`
- [X] There are new or updated unit tests validating the change
- [X] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by revmischa** [comment]
@ArsenyYankovsky A thousand blessings upon your soul for this fine work!

**Comment by carlocorradini** [comment]
@ArsenyYankovsky Awesome!

**Comment by filipsuk** [comment]
This will be a game changer for our serverless stack. 🎉

**Comment by revmischa** [comment]
We're working on a template for serverless typescript applications leveraging this module: https://github.com/jetbridge/generator-jkv2
Based on React for frontend and Serverless with no framework on the backend

**Comment by pleerock** [comment]
Thank you!

**Comment by pleerock** [comment]
Hey @ArsenyYankovsky what do you think about adding something like https://github.com/koxudaxi/local-data-api/ to our test infrastructure in order to run tests of these changes in CI?

**Comment by ArsenyYankovsky** [comment]
@pleerock Thanks for merging this. It is possible and would be nice to have tests pointing at the local data api. I have some tests pointing at the local data api in the driver repo as well as the tests pointing at the real data api.

**Pull request merged**
