### PR TITLE
fix: using async datasource to configure typeorm

### LINKED ISSUE #10168: Using async DataSource is broken
### Issue description

When defining an async datasource to use for migrations the typeorm CLI breaks

### Expected Behavior

It should be possible to define async `DataSource` according to:
https://github.com/typeorm/typeorm/issues/8914

And use that for configuring TypeOrm.

### Actual Behavior

When declaring an async data source as mentioned in the original issue https://github.com/typeorm/typeorm/issues/8914

```typescript
const buildDataSource = async () => {
  await ConfigModule.envVariablesLoaded;

  return new DataSource({
    type: 'postgres',
    url: process.env.DATABASE_URL,
    entities: ['dist/domain/**/*.entity.js'],
    migrations: ['dist/database/migrations/*.js'],
  });
};

export default buildDataSource();
```

It fails with 
```shell
Error during migration generation:
TypeError: dataSourceFileExports is not iterable
    at Function.loadDataSource (/Some/Path/backend/node_modules/src/commands/CommandUtils.ts:37:34)
    at async Object.handler ((/Some/Path/backend/node_modules/src/commands/MigrationGenerateCommand.ts:73:26)
```

I have tried numerous approaches to the export but they basically all fail.

### Steps to reproduce

Define an async `DataSource` and run the `migrate:generate` or `migrate:run` command.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v18.15.0  |
| Typescript version  | 4.5.5 |
| TypeORM version     | 0.3.17 |

### Additional Context

After some debugging it turns out that the problem lies in the `CommandUtils.ts` - checking for `someting instanceof Promise` is not stable and it does not work on my machine ™️. The check fails and thus passes the promise up the chain to the `InstanceChecker` which naturally fails.

I have a PR coming.
 

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by nover**
Fixes #10168 

### Description of change

The check in `CommandUtils.ts` for detecting whether the DataSource-source is a promise is broken.

Rather than testing whether it's a promise, simply await the value and use it. The `await` operator is defined in such way that if the thing is not awaitable we simply get the value back

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#return_value

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change - no because all relevant unit tests have been disabled by the code-owners
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hinogi** [comment]
I think another way would be to check if `.then` is available

**Comment by nover** [comment]
> I think another way would be to check if `.then` is available

We could do that explicitly and only await if the object is "thenable" - but this is exactly what await does under the hood (from MDN):

```
Await result 

The fulfillment value of the promise or thenable object, or, if the expression is not thenable, the expression's own value.
```

**Comment by hinogi** [comment]
> > I think another way would be to check if `.then` is available
> 
> We could do that explicitly and only await if the object is "thenable" - but this is exactly what await does under the hood (from MDN):
> 
> ```
> Await result 
> 
> The fulfillment value of the promise or thenable object, or, 
> if the expression is not thenable, the expression's own value.
> ```

Then you are absolutely right.  👍

**Review by hinogi — APPROVED** [review]

**Comment by nover** [comment]
Any chance of getting this merged soon @hinogi ?

**Comment by hinogi** [comment]
@nover I am not a maintainer, I am just helping with reviewing as much as I can to accelerate the process a bit.

**Comment by pleerock** [comment]
thanks @nover @hinogi !

**Pull request merged**
