### PR TITLE
fix: return transformed value on save/update

### LINKED ISSUE #4293: Transformed value not returned on save
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[X] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
class Example extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    transformer: {
      to: value => String(value).toUpperCase(),
      from: value => value,
    },
  })
  name: string;
}

describe('Example', () => {
  it('Should uppercase the name', async () => {
    const saved = await Example.create({name: 'test'}).save();
    expect(saved).to.have.property('name', 'TEST');
    // expected: TEST
    // actual: test
  });
});
```

When saving a column that has a transformer, the un-transformed value is returned from  the save function. This happens even if a `from` transformer is provided -- though none should be necessary. I've spent a while looking into this and can't figure out if it's design intent or not at this point. I'm going to read the source of `@CreateDateColumn` and see how it works, since it behaves the way I would expect.

### PR DESCRIPTION
**Pull request by iam4x**
Hi 👋 

This should closes #4293.
I have taken @loganyott work made into (https://github.com/typeorm/typeorm/pull/4505) and fixed the failing tests.

### CODE REVIEW

**Comment by tobloef** [comment]
Great work! Could we perhaps get it updated and merged?

**Comment by imnotjames** [comment]
Agreed!  You'll need to rebase it, there are conflicts.

**Comment by filipemacedo** [comment]
Hi guys, we need this fix, can you merge the same please?

@iam4x please.

**Comment by iam4x** [comment]
Hey, sorry completely missed the notification for this PR.
Will update the conflicts 👍

**Comment by pleerock** [comment]
Tests are failing. Also this is a breaking change and we should discuss if this is really expected behavior.

**Comment by pleerock** [comment]
I'll close it until we figure out final decision in #4293

**Pull request closed without merging**
