### PR TITLE
Added support for Postgres jsonb type

### PR DESCRIPTION
**Pull request by CreepGin**
#41 

Please give me some pointers on how you would like me to write the tests for this. I just found out about typeorm today and am not sure about your test structure/requirements.

### CODE REVIEW

**Comment by pleerock** [comment]
Hi. Thank you very much for your PR.

Test coverage is required. There is no guide for test requirements yet, I suggest to add your test into `test/functional/your-functionality` and implement tests. You need to cover at least functionality that saves and retrieves data in json format. Also you can use QueryRunner to get a table structure and check if column in the database has a correct type. Just take a look how other tests are implemented. Let me know if you have issues on how to run tests locally if you need that.

Also if you have time would be great if you can add JSON support for other drivers as requested in #41.

**Comment by CreepGin** [comment]
Thanks! I have no problem running the tests locally (though I did spot a few oddities such as hard-coded MySql username+password).

I'll update this patch with the tests hopefully by the end of today. For this PR, I think I'll just focus on getting Postgres jsonb working correctly since us Postgres users really can't live without it. 

Also I do have a few additional questions concerning implementing real (non-text-based) JSON support for other DB's (such as "how are we doing version/compatibility checking here?").

**Comment by CreepGin** [comment]
@pleerock Can you take a look? I'm not sure if there's something wrong with CI. Tests are running fine on my end (all passing).

**Comment by pleerock** [comment]
> failing tests on CI

for some reason sometimes tests are failing on CI. I'll need to figure out what is wrong there. Just try to restart build if it failed for unknown reason

> how are we doing version/compatibility checking here?

right now we don't have versions limitations, so probably we can rely on latest versions of dbs, and maybe in the future change things if someone request it

> test

can you please also add simple check: persist entity with JSON object set in the json column has been succesfully converted and saved, then load it and make sure that your json object has been successfully transformed into javascript object?

**Comment by CreepGin** [comment]
Sure, I added another test case.

Postgres has had real JSON support for ages, but MySql has just added the `json` data type this year. So maybe it's good to do some kind of compatibility check right now. 

I haven't used MySql for a long time. Maybe people using it can give some suggestions.

**Comment by pleerock** [comment]
Great. Also need to add docs [here](https://typeorm.github.io/tables-and-columns.html#column-types) and add release notes [here](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md).

Also it will be great if you can investigate json/jsonb support for other databases too. Im sure its pretty quick. Other drivers need implementation before we can close the issue in tracker + dont really want to add in the docs notes that only postgres support it.

**Comment by pleerock** [comment]
> So maybe it's good to do some kind of compatibility check right now.

I think we can add this feature, and if users will use json (if they do it and realize that its not working)  they will quickly understand that their version of mysql does not support it. We can add version check later, its not a big priority in this case (but if you want to add it go ahead to do it any time :D)

> mysql

what about other dbs, sql server?

**Comment by CreepGin** [comment]
I'm fairly sure that `jsonb` is Postgres-specific. Everything in this patch are just for that. 

As for other DBs, I will have to resort to google as I never used Sql Server, Oracle, and MariaDB.

**Comment by pleerock** [comment]
> Great. Also need to add docs here and add release notes here for next version - 0.0.6.

Hey @CreepGin , any updates on these so far?

**Comment by pleerock** [comment]
Okay I'll add docs by myself, thank you for this PR!

**Comment by pleerock** [comment]
@CreepGin can you take a look on [Subject#buildDiffColumns](https://github.com/typeorm/typeorm/blob/master/src/persistence/Subject.ts#L324) . are you sure you dont need similar code for JSONB type?

**Comment by pleerock** [comment]
This code is used to determine if column value should  be updated or not. Without this code ORM can produce extra query each time when you persist already exist object without need for that

**Pull request merged**
