### PR TITLE
fixed the iss #388

### PR DESCRIPTION
**Pull request by pablocarreraest**
someone can review it, thanks 👀 . The possible solution for #388.

### CODE REVIEW

**Comment by pleerock** [comment]
Hello and thank you for your PR! 
Few notes:

1. tests are failing. Please investigate why they are you failing and try fix them
2. your new functionality should be covered with tests. Please take a look how other tests are organized and create your own test testing functionality you have implemented

**Comment by pablocarreraest** [comment]
🙊 sorry working on it! one tiny question, what branch should work for PR?

**Comment by pleerock** [comment]
0.0.x-version is a correct branch

**Comment by pleerock** [comment]
any news on it?

**Comment by pleerock** [comment]
I'll close it since its already fixed. Fix for this issue is available from `0.1.0-alpha.26`.

**Pull request closed without merging**
