### PR TITLE
Fix Issue 281

### PR DESCRIPTION
**Pull request by mrkmg**
Fix Issue #281 by updating regex

Test is here: https://regex101.com/r/QeSm2I/1

### CODE REVIEW

**Comment by mrkmg** [comment]
Obviously a change like this will cause new tables to be created if the string changed.

Not sure how we want to handle rolling this out, as anyone with a db will need to manually rename their tables to keep their data.

**Comment by pleerock** [comment]
Yes its a breaking change, please update a changelog.

also, can you please take a look why tests are failing?

**Comment by mrkmg** [comment]
The failing tests appears to be an issue in `next` on its own. Looking into the issue now.

**Comment by mrkmg** [comment]
Tests Failing

Issue: https://github.com/typeorm/typeorm/issues/1242
PR: https://github.com/typeorm/typeorm/pull/1243

**Comment by pleerock** [comment]
Thank you!

**Pull request merged**
