### PR TITLE
Add ability to create connection by name

### PR DESCRIPTION
**Pull request by dvp-travis**
Fix for #1648.

### CODE REVIEW

**Comment by pleerock** [comment]
I applied some changes, please check them and add some tests which proof this functionality.

**Comment by dvp-travis** [comment]
I like your changes. I was going to add tests, but I wasn't sure where the proper place was to add them.

Are there existing tests for `createConnection()` that I can modify?

**Comment by pleerock** [comment]
Lets merge this one, thanks for the contribution!

**Comment by arthurwhite** [comment]
It would be nice to also `npm version patch && npm publish` it soon.

I scratched my head for 10 minutes before understanding that the docs are ahead. 😅

**Pull request merged**
