### PR TITLE
 fix: merge generatedMap of insert and update

### LINKED ISSUE #3246: Saving an entity with a 1:1 cascading insert does not return id if entity has nullable many:one relationship
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

- Broker has many Orders
- Orders have one OrderCustomer
- The relationship between Order and Broker is not nullable `{nullable: false}`
- The relationship between Order and OrderCustomer has cascade insert and update on `{ cascade: 'update', 'insert']}`
- Use a customer repository to save an Order and OrderCustomer in one call using cascade
- The save executes with the following query
```
query: START TRANSACTION
query: INSERT INTO "order"("orderReferenceNumber", "orderCustomerId", "createdDate", "modifiedDate", "companyId") VALUES ($1, DEFAULT, DEFAULT, DEFAULT, $2) RETURNING "id", "createdDate", "modifiedDate" -- PARAMETERS: ["abcd",1]
query: INSERT INTO "order_customer"("name", "createdDate", "modifiedDate") VALUES ($1, DEFAULT, DEFAULT) RETURNING "id", "createdDate", "modifiedDate" -- PARAMETERS: ["Dave"]
query: UPDATE "order" SET "orderCustomerId" = $2, "modifiedDate" = CURRENT_TIMESTAMP WHERE "id" = $1 RETURNING "modifiedDate" -- PARAMETERS: [1,1]
query: COMMIT
```
- The data is saved correctly but the object returned back lacks the primary key `Order.id`
```
Order {
  orderReferenceNumber: 'abcd',
  orderCustomer:
   OrderCustomer {
     name: 'Dave',
     id: 1,
     createdDate: 2018-12-13T19:20:36.206Z,
     modifiedDate: 2018-12-13T19:20:36.206Z },
  company:
   Broker {
     name: 'Acme Inc.',
     id: 1,
     createdDate: 2018-12-13T19:20:36.178Z,
     modifiedDate: 2018-12-13T19:20:36.178Z },
  orderCustomerId: 1,
  modifiedDate: 2018-12-13T19:20:36.206Z }
```
- Change the relationship between Order and Broker to be nullable `{nullable: true}`
- Rerun the save
- Save now executes with a different query
```
query: START TRANSACTION
query: INSERT INTO "order_customer"("name", "createdDate", "modifiedDate") VALUES ($1, DEFAULT, DEFAULT) RETURNING "id", "createdDate", "modifiedDate" -- PARAMETERS: ["Dave"]
query: INSERT INTO "order"("orderReferenceNumber", "orderCustomerId", "createdDate", "modifiedDate", "companyId") VALUES ($1, $2, DEFAULT, DEFAULT, $3) RETURNING "id", "createdDate", "modifiedDate" -- PARAMETERS: ["abcd",1,1]
query: COMMIT
```
- The data is saved correctly and the object returned back now has the primary key `Order.id`

```
Order {
  orderReferenceNumber: 'abcd',
  orderCustomer:
   OrderCustomer {
     name: 'Dave',
     id: 1,
     createdDate: 2018-12-13T19:22:56.624Z,
     modifiedDate: 2018-12-13T19:22:56.624Z },
  company:
   Broker {
     name: 'Acme Inc.',
     id: 1,
     createdDate: 2018-12-13T19:22:56.603Z,
     modifiedDate: 2018-12-13T19:22:56.603Z },
  orderCustomerId: 1,
  id: 1, // <= Id is now present
  createdDate: 2018-12-13T19:22:56.624Z,
  modifiedDate: 2018-12-13T19:22:56.624Z }
```

I will submit a pull request with a minimal reproduction. 

Thanks for the great work!

### LINKED ISSUE #4628: Not returning primary generated column value when cascade inserting
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have nullable OneToOne relations in my entity with cascade insert:

```ts
@Entity()
export default class DistributorTags {
  @PrimaryGeneratedColumn()
  id!: number;

  @ManyToOne(type => Distributor, distributor => distributor.tags, {
    nullable: false,
  })
  distributor!: Distributor;
  @Column()
  distributorId!: number;

  @ManyToOne(type => Staff)
  staff!: Staff;
  @Column()
  staffId!: number;

  @Column()
  dateIssued!: Date;

  @Column("int", { width: 4 })
  issueYear!: number;

  @JoinColumn()
  @OneToOne(type => DistributorTagsIssue, {
    nullable: true,
    eager: true,
    cascade: ["insert"],
  })
  blueTags?: DistributorTagsIssue;

  @JoinColumn()
  @OneToOne(type => DistributorTagsIssue, {
    nullable: true,
    eager: true,
    cascade: ["insert"],
  })
  blackTags?: DistributorTagsIssue;
}

@Entity()
export default class DistributorTagsIssue {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column("int")
  noIssued!: number;

  @Column("int")
  startNo!: number;

  @Column("int")
  endNo!: number;
}
```
When I try to insert the new data to database:
```ts
    this.distributorTagsRepository.create({
      staffId: currentUser!.staffId!,
      distributorId,
      dateIssued: getCurrentDate(),
      issueYear,
      tagsRequest,
      ...(tagsColor === TagColor.BLACK
        ? { blackTags: tagsIssue }
        : tagsColor === TagColor.BLUE
        ? { blueTags: tagsIssue }
        : {}),
    });
    await this.distributorTagsRepository.save(distributorTags);
```
the `distributorTags.id` property is undefined.

However when I remove the cascade data:
```ts
   this.distributorTagsRepository.create({
      staffId: currentUser!.staffId!,
      distributorId,
      dateIssued: getCurrentDate(),
      issueYear,
      tagsRequest,
    });
    await this.distributorTagsRepository.save(distributorTags);
```
it properly returns `distributorTags.id` property.

### PR DESCRIPTION
**Pull request by dolsup**
**AS-IS**
generatedMap of insert result is overwritten by generatedMap of updateResult.

It closes #3246. I tested it with a test case from https://github.com/typeorm/typeorm/pull/3247
Also, I think it can close #4628, #4090 (not tested)

🥳

### CODE REVIEW

**Comment by dolsup** [comment]
P.S. If you don't mind, could you put label `hacktoberfest-accepted` on this issue?

**Comment by RAllner** [comment]
Any news on this topic?

**Comment by dolsup** [comment]
It seems to be duplicated by #7336

**Comment by AlexMesser** [comment]
@dolsup I've merged #3247 and it's working with a fixes from #7336. So, your PR is covered by #7336.
Thank you for contribution!

**Pull request closed without merging**
