### PR TITLE
Upgrade ioredis from v4 to v5

### PR DESCRIPTION
**Pull request by DemianD**
### Description of change

This PR will upgrade the `ioredis` peer dependency from v4 to v5. 
All breaking changes are listed [here](https://github.com/luin/ioredis/blob/main/CHANGELOG.md#breaking-changes)

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by sig-code** [comment]
I will hope this PR will be merged 🙏

**Comment by hygo2025** [comment]
:eye:

**Comment by simoneromano96** [comment]
Any news? I'm using ioredis in multiple projects and this upstream dependency is blocking an upgrade to ioredis 5.x.

**Comment by pleerock** [comment]
Thank you for contribution! 🎉

**Pull request merged**
