### PR TITLE
#6442 fix: @JoinTable does not respect inverseJoinColumns referenced column width

### PR DESCRIPTION
**Pull request by michael-golden**
fix: @JoinTable does not respect inverseJoinColumns referenced column width

Closes: #6442

### CODE REVIEW

**Comment by pleerock** [comment]
Thanks for contribution! Looks like you have a CI failed, can you please check that? There are no errors, so I guess you have missed `await` somewhere that's why CI can't finish tests.

**Comment by michael-golden** [comment]
@pleerock - I've added awaits, but I'm not seeing any further reason for the timeout - any ideas?

**Comment by michael-golden** [comment]
@pleerock - Tests are fixed!

**Comment by pleerock** [comment]
Thank you!

**Pull request merged**
