### PR TITLE
hot fix failing browser builds on 0.2.25

### LINKED ISSUE #6110: Typeorm/browser cannot be compiled since version 0.2.25
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.25`

**Steps to reproduce or a small repository showing the problem:**
I have been using Typeorm and Sqljs with Nextjs. I have to [transpile module](https://github.com/Project-Setup/github_sql_pwa/blob/typeorm-0.2.25/next.config.js#L4) `typeorm/browser` at build time to generate static HTML files. This had been working until Typeorm upgraded to 0.2.25.

Here's the example repo: https://github.com/Project-Setup/github_sql_pwa/tree/typeorm-0.2.25
To reproduce:
1. git clone the repo
2. set up node environment
    ```sh
    nvm install; nvm use; npm install
    ```
3. build pages
    ```sh
    npm run build
    ```

an error will come out:
```
Creating an optimized production build  

Failed to compile.

./node_modules/typeorm/browser/driver/DriverFactory.js
Attempted import error: 'AuroraDataApiPostgresDriver' is not exported from './postgres/PostgresDriver'.


> Build error occurred
Error: > Build failed because of webpack errors
```

Reverting Typeorm to 0.2.24 will fix the issue.

I think the issue lies in typescript declaration file `node_modules/typeorm/browser/driver/postgres/PostgresDriver.d.ts`. It may have a problem exporting multiple classes under the current setup, but I wasn't sure.

### PR DESCRIPTION
**Pull request by chriswep**
closes #6110
added `AuroraDataApiPostgresDriver` to `BrowserDisabledDriversDummy.template` to fix typeorm not compiling when using browser target

### CODE REVIEW

**Comment by pleerock** [comment]
Thanks a lot!

**Comment by SanchezSobrino** [comment]
Thank you!

**Comment by chriswep** [comment]
@pleerock what are your release plans for this? just checking if i need to generate a typeorm package locally in the meantime

**Comment by SanchezSobrino** [comment]
For those in a hurry (we needed the feature on setting generated date columns manually), you can use the [patch-package](https://www.npmjs.com/package/patch-package) to locally patch the version 0.2.25 with the changes from the fix by @chriswep (thanks again) using the next patch:

```
diff --git a/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js b/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js
index 26fbcea..8f7bde5 100644
--- a/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js
+++ b/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js
@@ -56,6 +56,16 @@ var PostgresDriver = /** @class */ (function () {
     return PostgresDriver;
 }());
 export { PostgresDriver };
+/**
+ * DO NOT IMPORT THIS CLASS -
+ * This is a dummy class for replacement via `package.json` in browser builds
+ */
+var AuroraDataApiPostgresDriver = /** @class */ (function () {
+  function AuroraDataApiPostgresDriver() {
+  }
+  return AuroraDataApiPostgresDriver;
+}());
+export { AuroraDataApiPostgresDriver };
 /**
  * DO NOT IMPORT THIS CLASS -
  * This is a dummy class for replacement via `package.json` in browser builds
```

**Comment by jrr** [comment]
The patch workaround worked -- thanks -- but watch out that it's not idempotent! If you run "yarn" multiple times on one node_modules (like might happen with CI caching), you'll get the patch applied multiple times and receive an error like this:
```
`AuroraDataApiPostgresDriver` has already been exported. Exported identifiers must be unique. (78:9)
```

To work around _that_, you can make the patch a little more complicated:

```diff
diff --git a/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js b/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js
index 26fbcea..df3d159 100644
--- a/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js
+++ b/node_modules/typeorm/browser/platform/BrowserDisabledDriversDummy.js
@@ -55,12 +55,24 @@ var PostgresDriver = /** @class */ (function () {
     }
     return PostgresDriver;
 }());
+// AAAA - workaround to avoid re-patching
 export { PostgresDriver };
+/**
+ * DO NOT IMPORT THIS CLASS -
+ * This is a dummy class for replacement via `package.json` in browser builds
+ */
+var AuroraDataApiPostgresDriver = /** @class */ (function () {
+  function AuroraDataApiPostgresDriver() {
+  }
+  return AuroraDataApiPostgresDriver;
+}());
+export { AuroraDataApiPostgresDriver };
 /**
  * DO NOT IMPORT THIS CLASS -
  * This is a dummy class for replacement via `package.json` in browser builds
  */
 var SqlServerDriver = /** @class */ (function () {
+// BBBB- workaround to avoid re-patching
     function SqlServerDriver() {
     }
     return SqlServerDriver;
```

 (thanks to @petrbela for https://github.com/ds300/patch-package/issues/238#issuecomment-655617112 )

**Comment by kurthybela** [comment]
Hi. How can i apply this patch? I added it to the dependencies and installed but ionic build throws same error.
Thanks

**Comment by jrr** [comment]
@kurthybela can you write out in more detail the steps you took? Have you read and understood how to use [patch-package](https://github.com/ds300/patch-package)?

**Comment by kurthybela** [comment]
@jrr I could solve it already, I was inattentive, sorry.

**Pull request merged**
