### PR TITLE
Fix/next/date

### LINKED ISSUE #5334: Unable to perform find with where clause containing a date
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**NOTE**: Tested on PSQL, but affects all drivers.

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
@Entity()
export default class SomeEntityWithADate {
    @Column({type: "time without time zone"})
    someDateField: Date;
};

const repository = getRepository(SomeEntityWithADate);

const someEntity = await repository.findOne({
    where: {
        someDateField: new Date("2020-01-13")
     }
}); // Throw error
```

Error is:

> error: invalid input syntax for type timestamp: "{}"

**Cause:**

https://github.com/typeorm/typeorm/blob/next/src/find-options/FindOptionsUtils.ts#L95-L101

`FindOptionsUtils` is attempting to recursively detect where clauses, however it does so by assuming any `Object` that _isn't_ a `FindOperator` is a where clause.

`Date` is of course an object, so `FindOptionsUtils` incorrectly assumes its encountered a where clause and replaces our `Date` with the contents of the evaluated recursively evaluted "where clause" (an empty object in the case of a `Date`).

_PR inbound_.

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Fixed #5334 

Based on https://github.com/typeorm/typeorm/pull/5336 such that the CI runs.

### CODE REVIEW

**Comment by pleerock** [comment]
@Kononnable I think you need to take a look on this

**Comment by Kononnable** [comment]
Tests failed. Anyhow this will have to wait till #5336 is merged(or closed) since it's based on it.

**Comment by imnotjames** [comment]
Is this still a work in progress?

**Comment by imnotjames** [comment]
I'm going close this for now.  Please open a new PR when you've fixed the errors and are ready for a new review.

The issue will also remain open.

**Pull request closed without merging**
