### PR TITLE
Improve DeepPartial using recursive types

### LINKED ISSUE #2904: Type DeepPartial issue when used with generics
**Issue type:**

[ x ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ x ] `@next`
[ x ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```typescript

import {
  EntityManager,
  Transaction,
  TransactionManager,
  DeepPartial,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Connection,
  getConnection,
  getManager
} from 'typeorm';

namespace interfaces {
  export type klass<T> = { new (...args: any[]): T } | Function;
}

export class AuditedEntity {
  @PrimaryGeneratedColumn()
  id: number;

  savedBy: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}

export abstract class AbsBaseDao<E, PK = number> {
  conn: Connection;
  manager: EntityManager;
  baseEntity: interfaces.klass<E>;

  constructor(entity: interfaces.klass<E>) {
    this.conn = getConnection();
    this.manager = getManager();
    this.baseEntity = entity;
  }

  @Transaction()
  async create(entity: DeepPartial<E>, @TransactionManager() manager?: EntityManager) {
    return await manager.create(this.baseEntity, entity);
  }
}
export class TestDao<E extends AuditedEntity, PK = number> extends AbsBaseDao<E, PK> {
  async create(entity: DeepPartial<E>, @TransactionManager() manager?: EntityManager) {
    entity.createdAt = new Date();
    entity.updatedAt = new Date();
    entity.savedBy = 'SomeUSer';

    return super.create(entity);
  }
}
```
Typescript is giving me error on entity.createdAt, entity.updatedAt , entity.savedBy.

[ts] Type 'Date' is not assignable to type 'DeepPartial<E["createdAt"]>'.

But if I change the DeepPartial type from:

export declare type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> };

to

export declare type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> | **T[P]** };

the error disappears.

Could we change the DeepPartial type ?

Regards

Hugo

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

### PR DESCRIPTION
**Pull request by MatthiasKunnen**
### Description of change
Fixes #2904.

This change improves the DeepPartial check and prevents TypeScript from errorring unnecessarily in cases described in the aforementioned issue. On the flipside, it now errors on `.save()` in case a string property is passed instead of a `Date`. As such this PR will be a breaking change. I created a second commit that highlights what resolving the breaking change would look like.

What are your thoughts?

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by imnotjames** [comment]
There's still a few more type issues here.   Are you going to be cleaning those up?

**Comment by MatthiasKunnen** [comment]
Yes, but only if the maintainers are interested in the PR. If they are not interested, then there is not much point to fixing them. I'm waiting for feedback atm.

**Comment by Alwinator** [comment]
@imnotjames @MatthiasKunnen @pleerock Any news here? I would need this feature!

**Comment by pleerock** [comment]
it's postponed since its a breaking change. No estimates for now.

**Comment by pleerock** [comment]
I applied more simple change based on [this SO answer](https://stackoverflow.com/questions/61132262/typescript-deep-partial/). Your test seem to pass and change doesn't look breaking. I think we can merge it.

**Pull request merged**
