### PR TITLE
Add useNewUrlParser to mongodb driver

### PR DESCRIPTION
**Pull request by galkin**
According to issue #2270, I added missed configuration option to MongoDB driver.

### CODE REVIEW

**Comment by galkin** [comment]
@pleerock, could you review this pull?

**Comment by galkin** [comment]
@pleerock, could you review this pull?

**Comment by galkin** [comment]
@nooop3, @pleerock could you merge and publish?

**Comment by galaa2011** [comment]
I faced the same problem. When do you plan to merge this PR? @pleerock

**Comment by pleerock** [comment]
Thanks for the PR. Sorry for letting you to wait so long.

**Pull request merged**
