### PR TITLE
Lint on GitHub actions

### PR DESCRIPTION
**Pull request by stim371**
### Description of change
Add linting step to Github Actions test pipeline.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by michaelbromley** [comment]
This looks good. One thing I'm wondering is whether we can move the node version matrix up to the top level to avoid repeating at every job. This will make it less error-prone when we start to enable more versions.

**Comment by stim371** [comment]
> This looks good. One thing I'm wondering is whether we can move the node version matrix up to the top level to avoid repeating at every job. This will make it less error-prone when we start to enable more versions.

Here's an updated version with the matrix pulled up a level. It requires there to be two sub-files, but it's kind of nice to see that there are two different setups happening.

**Comment by OSA413** [comment]
I would rename `database-tests-oracle-cockroachdb.yml` to something like `database-compose-tests.yml` since it uses docker compose.

**Review by nikelborm — CHANGES_REQUESTED** [review]
Wouldn't it be a good idea to define a matrix with custom parameters for each driver type? I think it will be much more concise.

Nested structures such as `services` which differ across per-driver workflows it seems like could be done without too much effort

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#expanding-or-adding-matrix-configurations

**Comment by stim371** [comment]
> Wouldn't it be a good idea to define a matrix with custom parameters for each driver type? I think it will be much more concise.
> 
> Nested structures such as `services` which differ across per-driver workflows it seems like could be done without too much effort
> 
> https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#expanding-or-adding-matrix-configurations

@nikelborm can you provide a short example?

This PR was originally just for adding linting. We could continue to refactor and improve in follow-on ones further.

**Comment by michaelbromley** [comment]
True, I guess we are mixing concerns here a bit. And now it caused a merge conflict 😅

I suggest let's just get the conflict resolved, merge the linting, and then include any other workflows optimizations in a separate PR

**Review by michaelbromley — APPROVED** [review]

**Pull request merged**
