### PR TITLE
fix: Update DeepPartial for usage of generics with Repository class

### LINKED ISSUE #8681: DeepPartial simplification breaks the `.create()` and `.save()` method in certain cases.
## Issue Description

After the `DeepPartial` simplication of #8187, TypeScript is no longer able to match certain situations using the `.create()` and `.save()` functions. Specifically, when we are trying to pass a relation that is nested within a deep partial entity instance which is also an array, it will no longer match the `DeepPartial<Entity>[]` type signature and fail. See example code.

### Steps to Reproduce

```typescript
@Entity()
class Item {
  @PrimaryGeneratedColumn()
  id!: number

  @ManyToOne(() => Thing, thing => thing.items)
  thing!: Thing
}

@Entity()
class Thing {
  @PrimaryGeneratedColumn()
  id!: number

  @OneToMany(() => Item, item => item.thing)
  items!: Item[]
}


export async function test() {
  const myThing: DeepPartial<Thing> = {
    items: [{ id: 1 }, { id: 2 }]
  }

  const thing = getManager().create(Thing, myThing) // OK
  await getRepository(Thing).save(myThing) // OK

  const items = getManager().create(Item, myThing.items) // Not OK, myThing.items is of type `(Item | undefined)[] | undefined`
  // - or -
  await getRepository(Item).save(myThing.items) // Not OK for the same reason as above.
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 4.17.5  | 
| Typescript version  | 4.5.5  | 
| TypeORM version     | 0.2.43  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by nelsonfleig**
### Description of change

Update DeepPartial to work with a generic passed to Repository then testing on an abstract service.

This issue is related with Fixes #8681 

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #8681`
- [X] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pbrn46** [comment]
It seems after the `create()` call, a non-deeppartial is returned to be used for the `save()` call, The `save()` call doesn't like it, since apparently a _generic_ T can't be used as a parameter expecting a _generic_ DeepPartial<T> in the .`save()` signatures (`save<T extends DeepPartial<Entity>>`, for example). TS won't be able to figure out which overload to use. I would assume this is the same for the `.create()` signatures.

Using a signature like this seems to work:

```diff
-  save<T extends DeepPartial<Entity>>
+  save<T extends Entity | DeepPartial<Entity>>
```

Since the above works, we can instead union the original T as part of the DeepPartial type. This seems to work even better as it has fewer changes to core code, and will be more flexible for future use cases. TS now seems to be able to decide on the right one since the non-deeppartial type is now explicitly available:

```diff
- export type DeepPartial<T> = T extends Array<infer U>
+ export type DeepPartial<T> = T | (T extends Array<infer U>
    ? DeepPartial<U>[]
    : T extends Map<infer K, infer V>
    ? Map<DeepPartial<K>, DeepPartial<V>>
    : T extends Set<infer M>
    ? Set<DeepPartial<M>>
    : T extends object
    ? { [K in keyof T]?: DeepPartial<T[K]> }
-    : T
+    : T)
```

I ran this new DeepPartial through all the tests and they seem to pass as well.

Aside: Also added an await to the service `create` call to pass the test in this PR.

**Comment by nelsonfleig** [comment]
> It seems after the `create()` call, a non-deeppartial is returned to be used for the `save()` call, The `save()` call doesn't like it, since apparently a _generic_ T can't be used as a parameter expecting a _generic_ DeepPartial in the .`save()` signatures (`save<T extends DeepPartial<Entity>>`, for example). TS won't be able to figure out which overload to use. I would assume this is the same for the `.create()` signatures.
> 
> Using a signature like this seems to work:
> 
> ```diff
> -  save<T extends DeepPartial<Entity>>
> +  save<T extends Entity | DeepPartial<Entity>>
> ```
> 
> Since the above works, we can instead union the original T as part of the DeepPartial type. This seems to work even better as it has fewer changes to core code, and will be more flexible for future use cases. TS now seems to be able to decide on the right one since the non-deeppartial type is now explicitly available:
> 
> ```diff
> - export type DeepPartial<T> = T extends Array<infer U>
> + export type DeepPartial<T> = T | (T extends Array<infer U>
>     ? DeepPartial<U>[]
>     : T extends Map<infer K, infer V>
>     ? Map<DeepPartial<K>, DeepPartial<V>>
>     : T extends Set<infer M>
>     ? Set<DeepPartial<M>>
>     : T extends object
>     ? { [K in keyof T]?: DeepPartial<T[K]> }
> -    : T
> +    : T)
> ```
> 
> I ran this new DeepPartial through all the tests and they seem to pass as well.
> 
> Aside: Also added an await to the service `create` call to pass the test in this PR.

Great. Updated DeepPartial with @pbrn46 recommendations. Tests pass!

**Comment by H4ad** [comment]
If merged it will close this issue too https://github.com/typeorm/typeorm/issues/8698

**Comment by pleerock** [comment]
@nelsonfleig cockroachdb is super dumb. I'm going to restart the tests.

**Comment by pbrn46** [comment]
Also, beware the package-lock.json has been updated to lockfile v2 in the first commit. Not sure if that would affect the tests. :)

**Comment by nelsonfleig** [comment]
Unfortunately the same cockroachdb test still fails despite restoring the package-lock.json
```
1) repository > find options > locking
       should allow on a left join:
     Error: You must provide selection conditions in order to find a single row.
```

**Comment by nelsonfleig** [comment]
Any updates on the failing cockroachdb test?

**Comment by pleerock** [comment]
test was failing due to issue on master branch. Let me merge this PR.

**Pull request merged**
