### PR TITLE
Change dotenv to dotenv-flow

### PR DESCRIPTION
**Pull request by TheAifam5**
Related issue: https://github.com/typeorm/typeorm/issues/4354

### CODE REVIEW

**Comment by TheAifam5** [comment]
Should be ready to merge. Please review.

**Comment by pleerock** [comment]
`donenv` is super popular while `dotenv-flow` is a new and not so popular yet. Why they didn't make those changes part of `dontenv` itself? Is it reliable to use them? 

Also, I guess if we would merge it people will start asking about same functionality for other configuration types, e.g. `ormconfig.dev.json` and `ormconfig.prod.json`.

I'm not sure if we should merge it or not, so let's ask @vlapo and @Kononnable opinions.

**Comment by pleerock** [comment]
_(another reason why I don't want a configuration to be core of the framework - people always use different implementations/solutions). But since we still have it, we need to do something with it._

**Comment by TheAifam5** [comment]
The idea with `ormconfig.dev.json` would be really nice too :D 
If you think that PR is not needed, you can close it but that you need to decide.
I use `dotenv-flow` in production and works really well.

**Comment by pleerock** [comment]
Let's see what other people say

**Comment by Kononnable** [comment]
Sorry for being little late for the party.
I'm not comfortable with adding dependency which isn't widely used in the community(yet). It's a matter of cybersecurity.
Typeorm is used by many people(and corporations) and if we introduce a vulnerability we might harm many projects along the way. We don't have the time to check every line of code of dependencies(recursively), but having dependencies which are used by millions gives us a safety net. Popular packages got their code read by more people and even corporations which specialize in node package system security looks at it regularly.

**Comment by TheAifam5** [comment]
@Kononnable 	no problem. we can just leave that PR, and reopen when will be widely used. :)

**Comment by pleerock** [comment]
@TheAifam5 thanks for understanding.

**Pull request closed without merging**
