### PR TITLE
feature: upsert options conflictPaths as Entity keys

### PR DESCRIPTION
**Pull request by redwert**
### Description of change

Add checks that conflictPaths in upsert options relate to Entity

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by redwert** [comment]
`
@Entity()
export class Post {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    title: string
}
`

image

**Comment by pleerock** [comment]
I understand what you are trying to resolve, but I would avoid merging it because:

* there are other methods / options that are not keyof Entity and we need to design everything carefully and apply changes everywhere
* I don't know how currently users are using conflictPaths - do they use it with non-entity columns? If they do, this change is considered as breaking change.

**Comment by redwert** [comment]
reasonable, and what about adding support for the following declaration:
`awai tsomeRepository.upsert(
   {tite;"the title"},
   {conflictPaths: {title: true}}
)`
Add the ability to declare the conflict paths like we declare the relations in find.

**Comment by pleerock** [comment]
Yes, if we would have this feature, it definitely needs to be as `{conflictPaths: {title: true}}` because we need to support columns inside embeds, e.g. `{ {conflictPaths: { nested: { title : true }}}`. But again, this is part of the bigger breaking changes.

**Comment by redwert** [comment]
Please take a look on these changes

**Comment by pleerock** [comment]
I can accept it since it looks like doesn't break anything. Keep in mind embeds in entities are not supported by your changes. Later on we'll need to add this feature as well. Please add a test case for your change.

**Comment by redwert** [comment]
I have added the test

**Comment by redwert** [comment]
@pleerock could you please take a look. I have added the test and probably you can merge it

**Comment by pleerock** [comment]
Thank you for contribution! 🎉

**Comment by frostbytedata** [comment]
Yea this is a bad change for those of us using embedded entities. It is now no longer possible to specify conflict entity keys in the array for `conflictPaths` . Here is a simple example below:

```ts

class User {
  @Column()
  @IsEmail()
  email: string;

  @Column(() => Profile, {
    prefix: false,
  })
  profile: Profile;
}

class Profile {
  @Column()
  @IsString()
  name: string;

  @Column({
    name: 'profile_avatar',
    nullable: true,
  })
  @IsString()
  avatar: string;
}
```

In this example, it is impossible (unless I am using it wrong) to specify `conflictPath: ['profile_avatar']` for `upsert` commands. Is there a way around this for now?

**Pull request merged**
