### PR TITLE
feat: add relation options to all tree queries

### PR DESCRIPTION
**Pull request by TheProgrammer21**
Closes: #8076

### Description of change
Added the `relations` option to all treeRepository methods.

### Pull-Request Checklist
- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

The changes are more or less the same I made in the previous pull request, just that I did it on all other methods too. I created test cases for each method, with and without the option set.

### CODE REVIEW

**Comment by TheProgrammer21** [comment]
Can't really tell why the tests fail 🤔 
Just tried it locally again and they succeed. Maybe the order of the descendens array is not always the same 🤔 ?

**Comment by TheProgrammer21** [comment]
When will this be merged?

**Comment by TheProgrammer21** [comment]
@imnotjames would be nice if you could merge this PR. As you can see many people are waiting for it.
It is the same functionality you already merged a month ago, but now also made available for the other tree methods. 
Best regards :)

**Comment by pleerock** [comment]
@TheProgrammer21 thanks for waiting, it took a bit to me to reach your PR. Thank you for contribution!

**Comment by TheProgrammer21** [comment]
> @TheProgrammer21 thanks for waiting, it took a bit to me to reach your PR. Thank you for contribution!

Thank you for finally merging and for your work in general!

**Pull request merged**
