### PR TITLE
test: multiple primary keys many-to-many can fail with 'Specified key was too long'

### PR DESCRIPTION
**Pull request by kaznovac**
set explicitly lengths of primary key fields

### CODE REVIEW

**Comment by pleerock** [comment]
Motivation? Tests are passing on master without these changes.

**Comment by kaznovac** [comment]
i've run test on mysql 8 and this one was one of the failed.

explicit column lengths also guard against different column lengths between distributions, making this test more deterministic

**Comment by imnotjames** [comment]
Can you create some tests that verify this behavior?

**Comment by kaznovac** [comment]
@imnotjames these are changes in tests to make them more robust and not rely on the default values of column lenght

no need to test the tests

**Comment by imnotjames** [comment]
Oh, duh :) I misread the PR somehow.  I've been looking at a bunch, forgive me. :sweat_smile:  Easy to mix things up!


So then this should be `test:` not `fix:` - I'll update the title.

**Review by imnotjames — APPROVED** [review]
Looks good to me.  Hopefully we'll soon be able to split drivers out and test them against multiple database versions!

**Pull request merged**
