### PR TITLE
Moved `reflect-metadata` to `peerDependencies` and set version to `"^0.1.14 || ^0.2.0"`

### PR DESCRIPTION
**Pull request by OSA413**
This should fix or improve situation about this bug https://github.com/typeorm/typeorm/issues/10671

### CODE REVIEW

**Comment by zetaraku** [comment]
@OSA413 You forgot to update `package-lock.json` too. 👀

**Comment by OSA413** [comment]
@zetaraku how critical is that?

**Comment by OSA413** [comment]
Oh, i see you fixed it.
Did you run npm i to update it?
Thanks

**Comment by zetaraku** [comment]
Yeah, just run `npm i` to update it.
I'm not going to open a new PR so feel free to fix it directly :)

**Comment by OSA413** [comment]
@zetaraku I think you should make the commit as PR so I can either accept it or ask for it to be accepted. (I'm afraid I can break something while getting your changes to this repo, you've already done it, so that would be easier and safer)

**Pull request merged**
