### PR TITLE
Lazy relation promise persistence

### LINKED ISSUE #2729: Issue with updating parent in Lazy relationships
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey, I am not sure if this is a bug, or I am doing something wrong, but I tried a lot of things to get this working and I couldn't. I hope you guys can help.

Basically I have a one to one relationship that I need to lazyLoad. The relation tree is kind of big in my project and I can't load it without promises.

The issue I face is that when I save a child, the parent update generated sql is missing the update fields: ``` UPDATE `a` SET  WHERE `id` = 1 ```

This is working perfectly when I am not using lazyLoading (Promises).

I got a simple example set up using the generated code tool.

**Entity A**
```
@Entity()
export class A {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToOne(
        (type: any) => B,
        async (o: B) => await o.a
    )
    @JoinColumn()
    public b: Promise<B>;
}
```

**Entity B**
```
@Entity()
export class B {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @OneToOne(
        (type: any) => A,
        async (o: A) => await o.b)
    a: Promise<A>;
  
}
```

**main.ts**

```
createConnection().then(async connection => {

    const aRepo = getRepository(A);
    const bRepo = getRepository(B);

    console.log("Inserting a new user into the database...");
    const a = new A();
    a.name = "something";
    const aCreated = aRepo.create(a);
    await aRepo.save(aCreated);
    
    const as = await aRepo.find();
    console.log("Loaded A: ", as);

    const b = new B();
    b.name = "something";
    const bCreated = bRepo.create(b);
    bCreated.a =  Promise.resolve(as[0]);
    await bRepo.save(bCreated);
    
    const as2 = await aRepo.find();
    console.log("Loaded A: ", as2);
    
}).catch(error => console.log(error));
```

**Output**

```
Inserting a new user into the database...
query: SELECT `b`.`id` AS `b_id`, `b`.`name` AS `b_name` FROM `b` `b` INNER JOIN `a` `A` ON `A`.`bId` = `b`.`id` WHERE `A`.`id` IN (?) -- PARAMETERS: [[null]]
query: START TRANSACTION
query: INSERT INTO `a`(`id`, `name`, `bId`) VALUES (DEFAULT, ?, DEFAULT) -- PARAMETERS: ["something"]
query: UPDATE `a` SET  WHERE `id` = ? -- PARAMETERS: [1]
query failed: UPDATE `a` SET  WHERE `id` = ? -- PARAMETERS: [1]
```

If I remove the promises from the entities, everything is working fine:

**Entity A**
```
...
    @OneToOne(
        (type: any) => B,
        (o: B) => o.a
    )
    @JoinColumn()
    public b: B;
}
```

**Entity B**
```
    @OneToOne(
        (type: any) => A,
       (o: A) => o.b)
    a: A;
  
}
```

**main.ts**

```
createConnection().then(async connection => {
...
    const bCreated = bRepo.create(b);
    bCreated.a =  as[0];
    await bRepo.save(bCreated);
...
```

**Output**

```
query: INSERT INTO `b`(`id`, `name`) VALUES (DEFAULT, ?) -- PARAMETERS: ["something"]
query: UPDATE `a` SET `bId` = ? WHERE `id` = ? -- PARAMETERS: [1,1]
query: COMMIT
query: SELECT `A`.`id` AS `A_id`, `A`.`name` AS `A_name`, `A`.`bId` AS `A_bId` FROM `a` `A`
```

I have also created a git project to illustrate this and for easy of testing.

1) using promises (not working) https://github.com/cuzzea/bug-typeorm/tree/promise-issue
2) no lazy loading (working) https://github.com/cuzzea/bug-typeorm/tree/no-promise-no-issue

### PR DESCRIPTION
**Pull request by yazshel**
await and persist resolved value of Promise instances on lazy relation properties (closes #2729)

### CODE REVIEW

**Comment by yazshel** [comment]
I've created this PR to prompt some discussion about how lazy loading might be improved, by enabling the user to provide lazy relation values using `Promise.resolve({ <values> })`, or an unresolved database query `Promise` (both referred hereafter as "dirty" promises - in contrast to the `DatabaseLoader`-created Promises that are used to lazy-load related data).

One of the main advantages to these changes is that they remove the need for nasty TypeScript type casts when assigning object literals to lazy-load properties (which require `Promise<{entity}>`). Similarly, this circumvents the need to manually `await` on any `Promise.resolve(<entity>)` assignments to resolve the `Promise` before persisting a parent entity. 

In addition to the tests for #2729, there are 2 main changes in this PR:
1. Changes to `PlainObjectToNewEntityTransformer` to check for a `Promise` instance on lazy relation properties, and transform this to a `Promise` which recursively applies the transformer to the `Promise`'s resolved value.
2. Changes to the `EntityPersistExecutor` to `await` "dirty" `Promise`s on lazy relation properties, and also persist these where required. This allows the entities created using the logic in 1) to be persisted.

Change #1 enables the user to provide a `Promise` for lazy relation values when creating entities with `EntityManager.create()` or `Repository.create()`, for instance:
```typescript
@Entity()
class Person {
  name: string;
    
  @OneToMany(() => Pet, pet => pet.owner, { lazy: true })
  pets: Promise<Pet[]>;
}
@Entity()
class Pet {
  name: string;
  type: "cat" | "dog" | "dinosaur";
  @ManyToOne(() => Person, person => person.pets, { lazy: true })
  owner: Promise<Person>;
}

const person = getRespository(Person).create({
  name: 'Fred Flintstone',
  pets: Promise.resolve([
    { name: 'Dino', type; "dinosaur" }
  ])
});
// "person" will now be a Person instance, with person.pets a Promise<Pet[]> (ie. the object literal resolved by `Promise.resolve()` is transformed to a `Pet` instance).
```

Change #2 allows saving the entities with unresolved user-provided `Promise` values on lazy-load properties; for example (given the same above entity setup):
```typescript
await 
const person = new Person();
person.name =  'Fred Flintstone';
person.pets = getRespository(Pet).findMany({ name: 'Dino' });
// "findMany" promise has not yet resolved, but "save" will now `await` the user-set `Promise`
getEntityManager().save(person);
});
```

I expect that you TypeORM maintainers will want some improvements to the supporting changes  before merging this PR - particularly those around the identification of "dirty" (ie. user-provided) `Promise`s on lazy properties which is a little nasty as currently implemented.

To identify these "dirty" promises, I've added logic to `RelationLoader` which sets a hidden `entity["__dirty_<propertyName>__"]` flag when a user-provided `Promise` is set. Then changes to `RelationMetadata.getEntityValue()` check for this flag, and if set, returns the dirty Promise instance (even when `getLazyRelationsPromiseValue` argument is `false`). This probably needs to be improved, but I wasn't sure on the best approach.

So I thought rather than having these changes wasting away on my SSD, I'd create this PR and start the discussion :)

Any ideas / suggestions / responses?

**Comment by pleerock** [comment]
Im thinking to drop this feature from TypeORM. From the beginning it was experimental and too many people abuse it. And they all had problems.

**Comment by Kononnable** [comment]
> Im thinking to drop this feature from TypeORM
You mean whole lazy loading or just some part of it?

**Comment by pleerock** [comment]
I mean this `owner: Promise<Person>;` syntax and the way it works, e.g. `await model.owner`, basically drop the whole feature. Alternatively we can implement some insane functionality like `model.owner = repository.loadRelation("owner", model)`

**Comment by seawatts** [comment]
Any updates here?

**Comment by AlexMesser** [comment]
This is quite old PR and there are too many conflicts. Closing for now, if somebody interested in these changes please feel free to create a new issue.

**Pull request closed without merging**
