### PR TITLE
Fixes issue 9327: TypeError: dataSourceFileExports is not iterable

### LINKED ISSUE #9327: Migrations CLI fail with error: TypeError: dataSourceFileExports is not iterable
### Steps to Reproduce

I am following the documentation and installing typeORM with the command:
`npx typeorm init --name MyProject --database postgres`

running migrations with this command:
`yarn typeorm migration:show -d ./src/data-source.ts`

will fail with the error: 
`TypeError: dataSourceFileExports is not iterable
    at Function.loadDataSource (/Users/GitHub/MyProject/src/commands/CommandUtils.ts:37:34)
    at async Object.handler (/Users/GitHub/MyProject/src/commands/MigrationShowCommand.ts:27:26)`

data-source.ts looks like this:

```typescript
import "reflect-metadata"
import { DataSource } from "typeorm"
import { User } from "./entity/User"

export const AppDataSource = new DataSource({
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "test",
    password: "test",
    database: "test",
    synchronize: true,
    logging: false,
    entities: [User],
    migrations: [],
    subscribers: [],
})

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      MacOS    |
| Node.js version     | v18.8.0  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.8  | 

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by bobsingor**
### Description of change

Fixes #9327

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change N/A
- [ ] Documentation has been updated to reflect this change N/A
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by LeydenJar** [comment]
I'm facing the same issue, had to look into typeorm on my node modules to solve. Please merge this :)

**Comment by kakasoo** [comment]
Same problem. thx.

**Comment by alencarandre** [comment]
It would be wonderful if we had a unit test. Even this bug would not have been merged.

**Comment by IzaqueNunes** [comment]
+1

**Comment by zelpe** [comment]
+1

**Comment by araujo-jp** [comment]
+1

**Comment by RobbyKetchell** [comment]
+1

**Comment by pleerock** [comment]
thanks for the fix, looks like I already merged similar fix in #9332 . Will release a new version soon.

**Comment by Fasunle** [comment]
> thanks for the fix, looks like I already merged similar fix in #9332 . Will release a new version soon.

I still got the same error in version 0.3.8. I had to downgrade to 0.3.7.

In which version is the bug fixed?

**Comment by pleerock** [comment]
@Fasunle `0.3.9` contains the fix

**Comment by Fasunle** [comment]
> @Fasunle `0.3.9` contains the fix

Thank you so much. I will test it out 👍

**Pull request closed without merging**
