### PR TITLE
Fixing a few broken links

### LINKED ISSUE #988: Documentation: Connection options page has broken links
Related to #977

Page: http://typeorm.io/#/connection-options
Description: Most of the "Learn more about <blah>" links are still pointing to relative `.md` files. Maybe just needs some updates.

### PR DESCRIPTION
**Pull request by shousper**
Updating "Learn more about ..." links.

Closes #988

### CODE REVIEW

**Comment by daniel-lang** [comment]
Thank you for finding these. I created a PR at [typeorm/typeorm.github.io](https://github.com/typeorm/typeorm.github.io/pull/17) that will change the website to support standard markdown links. I don't know if @pleerock likes these changes, but if he does, this PR wont be needed

**Comment by pleerock** [comment]
Yes it would be better if we fix site. This way we'll have documentation working on both github and website. @daniel-lang I have merged your PR and this issue can be closed I guess? Please confirm that and close it. @shousper thank you very much for your contribution, really appreciate it!

**Comment by shousper** [comment]
@pleerock All good. Kinda why I hesitate to contribute too much -- I don't have that much time to spare :(

**Comment by daniel-lang** [comment]
@pleerock I don't have enough rights to close this.
I create a second PR because I partly messed up the regex to parse links. After that all links should work as expected. Right know only those authored as `./entities.md` work and not `entities.md`.
Maybe @shousper can close the PR.

**Pull request closed without merging**
