### PR TITLE
Make some minor changes to EntitySchema column properties

### PR DESCRIPTION
**Pull request by iz-iznogood**
Make column properties: primary, createDate, updateDate, version, treeChildrenCount and treeLevel optional.
These rarely used properties should not be required for the class, the EntitySchemaTransformer handles the undefined case just fine

Also allow number for column.length it converts to string later on

### CODE REVIEW

**Comment by pleerock** [comment]
Why do you prefer entity schemas over decorators BTW?

**Comment by iz-iznogood** [comment]
I don't !!! 
Depends on what I am doing each time. For statically typed apps I use classes with decorators.
For more dynamic - less typesafe apps I use EntitySchema.

Most of the times I have to use both

**Comment by pleerock** [comment]
There are lot of things need to be finished with EntitySchema btw 😆

**Comment by iz-iznogood** [comment]
I know !!!! Don't worry I am planning to help as much as I can.

However, personally speaking, I have some bigger issues with TORM that must be resolved.
The most important is documentation !!! 
Then is a list of what is supported and you believe that works (mostly) well !!!
Third is a roadmap, small "stable" releases !!!! 

Other than that we are good!!!! 
However since we are "investing" in TORM it would be nice to have some kind of stability !!!!

We can discuss further if you prefer on that in private or in another issue so that we don't disturb people.
If you want to assign issues to me please do,

**Comment by pleerock** [comment]
> Don't worry I am planning to help as much as I can.

Thank you very much for your help. If you are planning to work on typeorm in perspective then I'll add you in typeorm organization, okay?

> The most important is documentation !!!
> Then is a list of what is supported and you believe that works (mostly) well !!!

Documentation is [here](https://github.com/typeorm/typeorm/tree/master/docs). Its not finished yet, Im planning to finish it and publish to website once 0.1.0 is final

> Third is a roadmap, small "stable" releases

Roadmap is [here](https://github.com/typeorm/typeorm/projects). There are some high-level tasks I listed for 0.1.0 and 0.2.0. I would like to finish all tasks listed in 0.1.0 ASAP and make final 0.1.0 release. It will be "small stable release" as you told. I hope to finish them in one-two months, would be great if someone could help me there 😆 

> If you want to assign issues to me please do

👍

**Pull request merged**
