### PR TITLE
#452 First changes for Oracle tests to pass.

### PR DESCRIPTION
**Pull request by gintsgints**
For you to review.

### CODE REVIEW

**Comment by gintsgints** [comment]
Guilty was this one:

```
"sample3_post_metadata"."description" AS "sample3_post_metadata_description" 
```

Of coarse you can shorten also table name. Wish me go that way?

**Comment by pleerock** [comment]
shortening column names isnt a fix there. Do you expect users would be pleasured to do so too? We need some good fix. I don't understand why oracle support on aliases length is so limited.

**Comment by gintsgints** [comment]
May be we can generate aliases somehow shorter?

**Comment by pleerock** [comment]
ahhh Im not sure... Do you have any ideas?

**Comment by gintsgints** [comment]
Hmm just a question. Why you need to give them aliases anyway?

**Comment by pleerock** [comment]
ahhh thats a long story.... we need aliases to map data correctly to entities. You need to learn code of `QueryBuilder` and `RawSqlResultsToEntityTransformer` to understand why they are needed.

**Comment by pleerock** [comment]
Probably we have only one way of fixing this - shorten them. But im not sure what is effective way of doing this. Maybe cut half of table name and column name in query builder? Not really sure. Is there any way we can increase alias length in oracle via orm?

Also, if you are planning to work on QB I recommend to switch [to this](https://github.com/typeorm/typeorm/tree/query-builder-refactoring) branch, because there are latest changes of everything

**Comment by gintsgints** [comment]
How about giving them numbers? Like Alias1, Alias2, .... AliasN

**Comment by pleerock** [comment]
we can try numbers, however it will make things much much more complicated. And its already quite complicated

**Comment by pleerock** [comment]
@gintsgints we are planning to finish complete oracle support in `0.2.0`. @AlexMesser already fixed most of issues oracle has on [his own branch](https://github.com/typeorm/typeorm/tree/schema-builder-refactoring). Soon all those changes will be landed in `next` and final 0.2.0 will be released next month. Thank you very much for your contribution.

**Pull request closed without merging**
