### PR TITLE
Fix 4701

### PR DESCRIPTION
**Pull request by jurasan**
fixing issue with duplicate migrations https://github.com/typeorm/typeorm/issues/4701

### CODE REVIEW

**Comment by ssonne** [comment]
Shouldn't the fix be to throw an error if there are duplicate migrations? In what circumstance would you want to allow duplicate migration names and skip one? IME duplicate names are are a result of creating a new migration by copy/pasting code, and the new migration ends up silently not being run.

**Comment by jurasan** [comment]
@ssonne I agree that throwing error is better. But now when I have duplicate migration class names and I'm applying it separately, that's what's happening (skipping second migration). 
I'd like the behavior at least be consistent.
If we're ok with throwing error I can do it this way, but it could potentially break older duplicate migrations, if they happened to be applied together in one step and thus both were applied correctly. Are we OK with that?

**Comment by ssonne** [comment]
> it could potentially break older duplicate migrations
That's fair, it would be safer to make throwing an error on duplicates an opt-in flag.

> Are we OK with that?
I'm just an interested user; I don't have write access. But I think this PR is a strict improvement since it makes the behavior consistent.

**Comment by jurasan** [comment]
@pleerock 
Would it make sense to have this change to have consistency now and then another PR which would throw exception but with the next major version, as this is kind of breaking change, sorf of.

**Comment by pleerock** [comment]
we do not consider fixing a broken scenario as a breaking change, its a fix.

**Comment by pleerock** [comment]
and yes, I think we should throw exception in this case

**Comment by jurasan** [comment]
@pleerock Changed to throwing error

**Pull request merged**
