### PR TITLE
Fix embedded column prefix option

### LINKED ISSUE #3019: Can't disable prefixes for Embedded columns
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] `all?`
[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Documentation claims `prefix: ''` will disable the prefix but does not
https://github.com/typeorm/typeorm/blob/c56e605e729506e405b3a00a98a9cebaf257ec94/src/metadata/EmbeddedMetadata.ts#L96-L102

Appears to be due to a simple truthy check here, which fails for `''`
https://github.com/typeorm/typeorm/blob/c56e605e729506e405b3a00a98a9cebaf257ec94/src/metadata/EmbeddedMetadata.ts#L231

~~(PR incoming)~~ PR submitted

### PR DESCRIPTION
**Pull request by StrikeForceZero**
- Makes embedded column prefix option behavior match source documentation
  - Resolves #3019
  - Allows boolean to explicitly disable or enable the prefix

### CODE REVIEW

**Comment by victorschinaider** [comment]
#928

**Comment by StrikeForceZero** [comment]
@hlibco I only went with it because the existing types at 

https://github.com/typeorm/typeorm/blob/b7cc62d9e3bf7e016a308ea84bf34ccea8ac02d1/src/metadata/EmbeddedMetadata.ts#L94

and it felt kinda awkward specifying `prefix: ''` instead of having option to do `prefix: false` IMO. But it's easy to remove if that's what's desired.

**Comment by victorschinaider** [comment]
Sometimes I wonder if this project (typeorm) is reliable in the future... 8 days and no news from owners.

**Comment by victorschinaider** [comment]
@pleerock @Kononnable

**Comment by pleerock** [comment]
Thank you!

**Comment by philippspinnler** [comment]
Is it possible to merge this also to "next"?

**Pull request merged**
