### PR TITLE
docs: fix typos & format in migration-related docs

### PR DESCRIPTION
**Pull request by Ayomide-Daniel**
### Description of change

In this PR, I have fixed some typos in the migration-related docs. I found them while reading the documentation recently and experienced some errors when I ran some of the code snippets/ examples.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [ ] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by hinogi — CHANGES_REQUESTED** [review]
That change doesn't look correct, there is a reason for `--`

**Comment by Ayomide-Daniel** [comment]
> That change doesn't look correct, there is a reason for `--`

@hinogi, oh, really? I didn't know this. 

Please enlighten me

**Comment by hinogi** [comment]
https://www.baeldung.com/linux/double-dash-in-shell-commands

**Comment by Ayomide-Daniel** [comment]
> https://www.baeldung.com/linux/double-dash-in-shell-commands
> https://www.cyberciti.biz/faq/what-does-double-dash-mean-in-ssh-command/

Ah, I see. Thank you

**Comment by pleerock** [comment]
I'll close it until it gets finished.

**Pull request closed without merging**
