### PR TITLE
Change so that parameters from "url" connection option can be overridden by specific connection options

### PR DESCRIPTION
**Pull request by jussikinnula**
Based on discussion in https://github.com/typeorm/typeorm/issues/3159, it would be desirable to allow users to override parameters set in *url* connection option (only in mysql/mariadb, postgres, mssql and mongodb).

The current implementation prioritises `url` over the other parameters.

For example...

```
const options = {
  url: 'postgres://localhost:5432',
  username: 'myuser',
  password: 'mypass',
  ...
};```

...would get initial options from url, and then set username and password as defined in options.

### CODE REVIEW

**Comment by havenchyk** [comment]
Ah, since it's a breaking change again, should it be opened against next @pleerock @Kononnable ?

**Comment by pleerock** [comment]
@havenchyk its unclear when next is going to be released.

Since we already did a breaking change for this url stuff probably its okay to merge this one. We'll need to add notes in the changelog.

**Comment by marines** [comment]
This PR breaks the previous fix #2843 for TYPEORM_URL. `Object.assign(urlDriverOptions, options)` overwrites all the credentials taken from the URL with undefineds if only the URL is being passed.
@pleerock @jussikinnula

**Comment by jussikinnula** [comment]
@marines, it should work so that single parameters come first, then larameters from TYPEORM_URL.

We also had a new PR to allow using only TYPEORM_URL lately (handy with typeorm cli).

We did had regression before this PR, which was TYPEORM_URL overriding single parameters - which after discussed we found undesirable.

Do you think something still should be changed or have you actually had problems with new versions?

**Comment by marines** [comment]
I'm fine with single parameters taking precedence over the URL but currently TYPEORM_URL can't be used to define connection string (as of 0.2.12-rc2). I will create a new issue if you think we should move the conversation from here.

**Comment by marines** [comment]
Unsurprisingly it doesn't work with TYPEORM_CONNECTION defined. If you don't provide single parameters then those empty values overwrite the actual credentials provided by TYPEORM_URL while they should be ignored if empty (as I mentioned in my first comment).

**Comment by jussikinnula** [comment]
@marines, you were right. There was still an issue with the Object.assign(). It's now fixed in https://github.com/typeorm/typeorm/pull/3442. Sorry about that. I simplified the structure now even more, so it should clearly work as needed.

@pleerock, we should pick https://github.com/typeorm/typeorm/pull/3442 also for the upcoming next RC.

**Comment by marines** [comment]
No problem at all! I didn't expect it to be fixed so quickly. Thanks a lot!

**Pull request merged**
