### PR TITLE
Removes duplicate columns in select builder

### LINKED ISSUE #1726: Unable to use Paging while Joining Entities with Id of Related Entity
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Using `.findAndCount` or `getManyAndCount` and joining on related entities that also have a property with the same name as a property defined in the source entity WHILE also using skip and take (or offset and limit).  For example:

Location.accountId
Program.accountId

The following error is returned when attempting to do so:

`The column 'Location_accountId' was specified multiple times for 'distinctAlias'`

I have a PR that addresses the issue by removing duplicate columns in the select builder.

### PR DESCRIPTION
**Pull request by kjaenicke**
Fixes #1726

### CODE REVIEW

**Comment by pleerock** [comment]
Thanks for the contribution.

Fixes are not accepted without tests in PRs, since functionality you made can break quite fast if it will not be covered by tests.

Also, can you please provide an example of how we can face this issue (code example, reproduction of issue), so I can understand where exactly issue is.

**Comment by pleerock** [comment]
please make this PR against `next` brach (check if this functionality is broken on `next` first, npm i typeorm@next)

**Comment by kjaenicke** [comment]
Sorry for the delayed response on this. Turns out that the issues were related to our implementation and incorrectly setting up entity relationship.  Thanks for the great project!

**Comment by bssergy** [comment]
> issues were related to our implementation and incorrectly setting up entity relationship

@kjaenicke what do you mean here? I have the same issues but I can not find any solution

**Comment by kjaenicke** [comment]
@bssergy - It turned out that I was improperly using the library. My entities weren't set up correctly. Essentially, I was specifying a column multiple times via JoinTable and defining the related ID property on the models too. Sorry I don't have any example code but hopefully that gives you a starting point as to where to look.

**Comment by bssergy** [comment]
@kjaenicke thanks, I described my issue here #2200

**Pull request closed without merging**
