### PR TITLE
Caching from repository

### PR DESCRIPTION
**Pull request by aj-liptak**
[#1057](https://github.com/typeorm/typeorm/issues/1057)

### CODE REVIEW

**Comment by pleerock** [comment]
Hi and thank you for your contribution!

You missed tests that check functionality you added. If there were tests they show you that your functionality is broken. You added cache property into find options, however they don't do anything - you forgot to call a code which actually enables caching in query builder.

**Comment by aj-liptak** [comment]
Hey, I'm sorry about that. I was working in another branch and didn't properly bring in all the changes. I apologize for my oversight. This PR now includes the query builder call and a test to validate functionality.

**Comment by pleerock** [comment]
Thank you very much for this clean and well-made PR!

**Comment by pleerock** [comment]
This will be released in `0.1.2`. I forgot to mention to update find options docs and add this change into changelog, can you please do it?

**Comment by aj-liptak** [comment]
Absolutely, here's the PR for those additions: https://github.com/typeorm/typeorm/pull/1074

**Comment by pleerock** [comment]
Thank you!

**Pull request merged**
