### PR TITLE
Doc: Migration commands should be singular

### PR DESCRIPTION
**Pull request by clouless**
The docs say

```
typeorm migrations:*
```

It should be

```
typeorm migration:*
```

### CODE REVIEW

**Comment by pleerock** [comment]
What version are you using? We already have this change in `next` docs

**Comment by clouless** [comment]
I am using `0.2.0-alpha.40` and just did a `yarn add typeorm`

and then `./node_modules/.bin/typeorm -v`

So if you already have another PR for that you can just close this one :)

**Comment by pleerock** [comment]
Looks like we accidentally pushed 0.2.0 to the `latest`, I've fixed that, thanks for the report. 
Feel free to use `0.2.0-alpha.40` since final 0.2.0 will be released in a few days.
This PR can be closed since once we release 0.2.0 we are going to merge `next` branch into `master` which already contains those changes.

**Comment by clouless** [comment]
ok cool thx :) Really love the whole "design" of the framework.
I checked a lot of other ORMs but this is my favorite :) great work!

**Pull request closed without merging**
