### PR TITLE
Added pagination 'wrapper' function

### PR DESCRIPTION
**Pull request by bashleigh**
Added a pagination wrapper around findAndCount to return an defined object. Example:

```javascript
{
    items: [
        {
            id: 1,
            ...
        },
        ...
    ],
    count: 10,
    pages: 2,
    total: 20,
}
```
The pagination interface accepts {page: 1, limit: 10} to avoid confusion with skip and take. Where skip is page times limit. 

To be used like: 

```javascript
const result = await blogRepository.paginate({
    page: 2,
    limit: 10,
});
```

I had to disable MSSQL during testing due to MSSQL throwing an exception on FETCH ROW which seems to be a known issue?

### CODE REVIEW

**Comment by bashleigh** [comment]
That's cool, are you cool if I make a package for this? And or is there anything you'd like me to contribute to?

**Comment by bashleigh** [comment]
it's fine :) I did however make another pull request for nestjs https://github.com/nestjs/typeorm/pull/36 and again they rejected it! Again I was unsure whether to add the functionality to typeorm or nestjs/typeorm.

**Comment by pleerock** [comment]
Thank you. But please don't hesitate to do other contributions! But next time probably better to start with an issue and discussion to prevent loosed efforts.

**Comment by bashleigh** [comment]
will do 👍

**Pull request closed without merging**
