### PR TITLE
feat: add fulltext parser option

### LINKED ISSUE #3777: MySQL Fulltext index with ngram parser
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

We're able to create full text indexes in MySQL like so:
```
@Index(["name"], { fulltext: true })
```
This generates SQL like so:
```
CREATE FULLTEXT INDEX `name` ON `table`(`name`)
```

However, MySQL allows you to also specify a parser for fulltext indexes, specifically `ngram`. This lets you perform fuzzy search.
```
CREATE FULLTEXT INDEX `name` ON `table`(`name`) WITH PARSER ngram
```

It would be great if we could have an additional index option for this. I'm thinking this could be something like
```
@Index(["name"], { fulltext: true, ngram: true })
```
or
```
@Index(["name"], { fulltext: true, parser: 'ngram'|'mecab'|null })
```

That way, we can still use generated migrations and schema sync without losing specific parsers.

### PR DESCRIPTION
**Pull request by bizen241**
This adds support for parser option for fulltext index.

[MySQL > ngram Full-Text Parser](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search-ngram.html)
[MySQL > Full-Text Parser Plugins](https://dev.mysql.com/doc/refman/8.0/en/plugin-types.html#full-text-plugin-type)

Closes #3777

### CODE REVIEW

**Comment by pleerock** [comment]
Thanks for contribution!

We need to read information about parser being used on a table, store this information about compare with what we have in entity to make a proper updates on a schema changes. Looks like there is no such code. Try to apply parser on exist index, or remove it from exist index, ORM won't update a schema and this is bug.

You need to modify code on line 1410...

**Comment by bizen241** [comment]
To synchronize parser, I tried using `COMMENT` clause.

**Comment by pleerock** [comment]
sorry, we can't use "comment" clause. What if user already using COMMENT for different purposes - problem. What if user don't want to have dirty comments - problem? What if we'll have some other property that will be relying on COMMENT - problem. We need to read information on parser being applied from INFORMATION_SCHEMA, other approaches are not acceptable.

**Comment by bizen241** [comment]
Thank you for your reviewing.

I can't read information about parser from `INFORMATION_SCHEMA`.
[MySQL Bugs > no metadata for parser name of fulltext index](https://bugs.mysql.com/bug.php?id=87974)

Sorry for lack of consideration.

**Comment by pleerock** [comment]
If you are sure there is no way - please revert back "comment" changes, we'll just add support without schema sync working, its okay if its not supported by the database.

**Comment by pleerock** [comment]
Thanks

**Pull request merged**
