### PR TITLE
test(postgres): add test case for zero-arity cubes

### PR DESCRIPTION
**Pull request by liaujianjie**
Add test case for a bug where Postgres `cube` of zero arity incorrectly hydrates as `[0]` instead of `[]`.

### CODE REVIEW

**Comment by liaujianjie** [comment]
The broken test has to do with the Postgres version. Test fails on `9.6.11` but works on `10.6`. Not sure how to proceed from here.

**Comment by pleerock** [comment]
@liaujianjie looks like we already have this change in #4848 ? If so, can we just left a test from this PR since it looks like is missing in #4848

**Comment by liaujianjie** [comment]
@pleerock The test are still failing because CircleCI uses Postgres v9.6.11 though.

```sql
CREATE EXTENSION cube;
CREATE TABLE test (color CUBE);
INSERT INTO test(color) VALUES ('()'); -- works for Postgres v10.6 but not v9.6
```

Error throw in Postgres v9.6:

```
ERROR:  bad cube representation
LINE 1: INSERT INTO test(color) VALUES ('()');
                                        ^
DETAIL:  syntax error at or near ")"
```

**Comment by pleerock** [comment]
maybe we should update a postgres version in config to make these tests pass?

**Comment by liaujianjie** [comment]
I'm all for it, but that means we're not going to guarantee support for Postgres versions <10. Are we ok with that?

**Comment by pleerock** [comment]
then maybe we can add some check to this test - test if its a postgres >= 10 then execute it, otherwise ignore?

**Comment by liaujianjie** [comment]
Sounds good. How can I check the Postgres version?

**Comment by swim** [comment]
Adding a getVersion to the QueryRunner (SHOW server_version) would be nice however, it would need to be implemented for each driver.

**Comment by liaujianjie** [comment]
> Adding a getVersion to the QueryRunner (SHOW server_version) would be nice however, it would need to be implemented for each driver.

I think he was referring to just the codebase.

**Pull request merged**
