### PR TITLE
feat: implements QueryFailedError generic for driverError typing

### LINKED ISSUE #10254: possibility to type driver error
### Feature Description

In some applications with stricter typing rules, type any is disallowed. With that in mind, I believe a way to type the error coming from the driver is necessary.

### The Solution

Implement a generic typing on QueryFailedError class with Error being de default type.

### Considered Alternatives

I don't think of a better alternative with less impact.

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by guilopesn**
### Description of change

Implements optional generic to type driverError on QueryFailedError class.

### Pull-Request Checklist

- [X] Code is up-to-date with the `master` branch
- [X] `npm run format` to apply prettier formatting
- [X] `npm run test` passes with this change
- [X] This pull request links relevant issues as `Fixes #10254`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [X] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by guilopesn** [comment]
FIX #10254

**Comment by guilopesn** [comment]
Fixes #10254

**Comment by hinogi** [comment]
LGTM

**Review by hinogi — APPROVED** [review]

**Comment by pleerock** [comment]
Thank you for contribution! 🎉

**Pull request merged**
