### PR TITLE
Move @types/mongodb to devDependencies

### PR DESCRIPTION
**Pull request by Spoki4**
I transpile typescript code to es6 and install only dependencies without devDependencies. But I whatever install types.

### CODE REVIEW

**Comment by pleerock** [comment]
We can't move this to dev dependency because users projects will throw compiler errors because of missing mongodb dependencies in mongodb driver.

**Comment by Spoki4** [comment]
What I can do if I don't wont have a types in dependencies on my production server? But they are installing.

**Comment by pleerock** [comment]
I understand the issue, however there is no good solution for this yet. One solution is to refactor typeorm completely and make it modular however that requires lot of time to think of its new design and implement it. This is planned for the future. For now you have to ignore the fact that you have extra package with typings on your environment. In fact they aren't add so much.

**Comment by Spoki4** [comment]
I'm a perfectionist, but I'm ready to sacrifice this. Thx you for answer.

**Comment by pleerock** [comment]
yeah me too, however we both know that nothing is perfect and there always not perfect choices and tradeoffs we forced to choose. Thanks for PR.

**Pull request closed without merging**
