### PR TITLE
fix: Unnecessary migrations for fulltext indices

### LINKED ISSUE #6633: Postgres, migrations: Fulltext indices continually dropped & re-created
**Issue type:**

[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Given the following entity:

```ts
@Entity()
export class Test {
    @PrimaryColumn()
    id: number;

    @Index("description_index", { fulltext: true })
    @Column()
    description: string;
}
```

Running a migration with postgres will _always_ generate the following queries, even though no changes are made to the schema:

```ts
export class someMigration1598601015234 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "description_index"`, undefined);
        await queryRunner.query(`CREATE INDEX "description_index" ON "test" ("description") `, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "description_index"`, undefined);
        await queryRunner.query(`CREATE INDEX "description_index" ON "test" ("description") `, undefined);
    }
}
```

The reason seems to be that postgres does not support fulltext indices, but in `RdbmsSchemaBuilder.ts` the `tableIndex.isFulltext` property is checked even for postgres, which makes any fulltext indices give false positives:

https://github.com/typeorm/typeorm/blob/d1ed5723bb55d4124be13b21e57d9f729d0bae1a/src/schema-builder/RdbmsSchemaBuilder.ts#L280-L281

This may be related to #5655 and #5159. It also may occur with other database types.

I intend to submit a PR with a fix shortly.

### PR DESCRIPTION
**Pull request by michaelbromley**
Fixes #6633 (see issue for root cause explanation)

### CODE REVIEW

**Comment by pleerock** [comment]
Thanks for PR!

What is the point of using `fulltext` flag for a database that doesn't support it? TypeORM's entities don't try to be database-agnostic.

I can merge it, however it would be better if we change it a bit - we probably need to have a boolean flag in driver like `isFullTextColumnTypeSupported(): boolean`. If you don't want to return back to it, no problem, I'll merge it.

**Comment by michaelbromley** [comment]
> What is the point of using fulltext flag for a database that doesn't support it? TypeORM's entities don't try to be database-agnostic.

Because in my framework (vendure.io) I _do_ want the entities to be DB-agnostic. The end-user passes in the ConnectionOptions to specify which DB they want to use. I have a `SearchIndexItem` entity using fulltext fields, and I aim to support MySQL/MariaDB/Postgres/SQLite. Having DB-specific models is perhaps possible (dynamically defining the metadata at runtime) but it is certainly not convenient or intuitive to figure out what's going on.

I think it makes sense that for non-supported features like this, the DB just totally ignores them and they shouldn't have unexpected side-effects like with the current issue.

> I can merge it, however it would be better if we change it a bit - we probably need to have a boolean flag in driver like isFullTextColumnTypeSupported(): boolean. If you don't want to return back to it, no problem, I'll merge it.

This makes sense, and is consistent with the handling of the other features where support differs between drivers. I can push another commit later this week.

**Comment by michaelbromley** [comment]
Done!

**Comment by pleerock** [comment]
Thank you!

**Pull request merged**
