### PR TITLE
feat: Allows to specify how "undefined" and "null" values should be treated in conditions

### LINKED ISSUE #9316: typeorm findOneBy( { id: null or undefined } ) method return the first record on the table  !
### Expected Behavior

return null

### Actual Behavior
```
const user = await userRepository.findOneBy({
            id: undefined or if it's null
        });
```
this return the first user in the users table !

```
User {
  id:,
  username: ,
  ....
}
```

### Steps to Reproduce

1. create typeorm connection
2. create user entity and migrate it to the database
3. query the database using the user repository ' call findOneBy method '

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `sqlite`          | yes            |

for other idk :)

### PR DESCRIPTION
**Pull request by iJhefe**
This feature Allows to specify how TypeORM should handle "undefined" and "null" values in conditions

### Description of change
before this feature TypeORM just exclude `null` and `undefined` values from conditions. Now it can be defined at "DataSouceOptions".

It changes the default behavior about `null` values. Now it's should be interpreted as `IS NULL` and not exclude it

Allow `null` at `FindWhereConditions`

The options for "null" and "undefined" values are:
- `is-null`: condition will be "IS NULL"
- `exclude`: condition will not be considered
- `throw`: will throw an exception

 FIXES #9316, #9446, #9527

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pleerock** [comment]
This configurable behavour introduces redundant complexity to the code and the ability of making such things flexible brings confusion to the user and I think overall is a bad design step. 

For cases like this `findOneBy( { id: null or undefined } )` I suggest to add another code which iterates over all given properties to a given FindOptionsWhere object and makes sure there is at least one defined property.

**Comment by bombillazo** [comment]
> This configurable behavior introduces redundant complexity to the code and the ability of making such things flexible brings confusion to the user and I think overall is a bad design step.
> 
> For cases like this `findOneBy( { id: null or undefined } )` I suggest to add another code which iterates over all given properties to a given FindOptionsWhere object and makes sure there is at least one defined property.

I agree that making this configurable will be a bad design choice for the long run and brings opposing behaviors to the ORM. The package should establish a convention (my thoughts on that [here](https://github.com/typeorm/typeorm/issues/9316#issuecomment-1299328534)) and let the users/developers add application logic around that convention.

**Comment by pleerock** [comment]
See my answer above ^

**Comment by trim21** [comment]
thanks for your responding

**Comment by bombillazo** [comment]
Yes, I believe this is an issue because null is pretty much broken when it comes to value comparisons. I dont understand why TyoeORM would treat null as undefined when null has a meaning in the DB domain and intuitively maps to the JS domain.

**Comment by cnorthfield** [comment]
@pleerock I’d suggest a breaking change to update the behaviour permanently instead of a configuration option.

**Comment by gugu** [comment]
We are moving to Sequelize because of such issues - this is the only ORM, which cares about security (both null/undefined behavior and JSON injections)

**Comment by mptsonev** [comment]
Why would it ever be ok to specify a where conditional with a value of `undefined` or `null`? Surely there's no discussion to be had here, if a conditional is `null` or `undefined` the ORM should just throw an error, instead of silently ignoring erroneous values. @pleerock please reconsider the approach here, this is an absurd behavior.

**Comment by nikolaipetkov** [comment]
This is a serious security issue which is purposely left unaddressed, pretty wild.

**Comment by gugu** [comment]
We solved this problem by switching to sequelize. It took a lot of resources, but now we have 0 problems

**Comment by twigs67** [comment]
Why was this closed and not merged @iJhefe ? I can't believe this is still an issue with TypeOrm. This is a massive security risk. At the very least, this should be well documented to let users know.

**Comment by iJhefe** [comment]
> Why was this closed and not merged @iJhefe ? I can't believe this is still an issue with TypeOrm. This is a massive security risk. At the very least, this should be well documented to let users know.

finally fixed #11332

**Pull request closed without merging**
