### PR TITLE
feat(query-builder): Allow WHERE clause on joined columns #2707

### LINKED ISSUE #2707: Allow WHERE clause on joined columns.
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

Hi!

As it said in the documentation of `FindManyOptions#where`:
> Querying a column from an embedded entity should be done with respect to the hierarchy in which it was defined.

It is possible to extend this capability to the joined columns ?

For exemple with 2 entities:
```TypeScript
@Entity()
class Contact {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  name: string;
  @ManyToOne(type => Address)
  address: Address;
}

class Address {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  street: string;
  @Column()
  city: string;
}
```

Make  a request like this:
```TypeScript
contactRepository.find({
  relations: [ 'address' ],
  where: {
    address: {
      city: 'Paris'
    }
  }
});
```

SQL:
```SQL
SELECT `Contact`.`id` AS `Contact_id`
    `Contact`.`id` AS `Contact_id`
    `Contact`.`name` AS `Contact_name`
    `Contact`.`addressId` AS `Contact_addressId`
    `Contact_address`.`id` AS `Contact_address_id`
    `Contact_address`.`street` AS `Contact_address_street`
    `Contact_address`.`city` AS `Contact_address_city`
  FROM `contact` `Contact`
  LEFT JOIN `address` `Contact_address`
    ON `Contact_address`.`id` = `Contact`.`addressId`
  WHERE `Contact_address`.`city` = "Paris";
```

I don't have seen any other options in TypeORM documentation to apply where clauses on joined columns. If there another way I am interested about it.

Thank you in advance for your help.

### PR DESCRIPTION
**Pull request by mtwzim**
### Description of change
Hello, my name is Matheus and this pull requets Fixes #2707 which has been open for almost 3 years, the code is capable of reproducing all the situations mentioned in the comment: https://github.com/typeorm/typeorm/issues/2707#issuecomment-748011818
Regarding the verification of tests I created a new test that is available in the folder `/test/github-issues/2707`, these tests also consider all the scenarios mentioned in the comment above, and this passes correctly: 
image

In addition, the lint check is OK for the files I modified

See you later!

PS: Sorry for my English, I am not fluent.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #2707 `
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mtwzim** [comment]
Well it seems that the tests do not work, I will check why this happens.

**Comment by mtwzim** [comment]
Well it seems that all the tests passed :)

**Comment by mtwzim** [comment]
One of the tests failed because of: Segmentation fault (core dumped). Apparently it's a memory dump error on circleci

**Comment by tylermaran** [comment]
Hey @mtwzim. I'm seeing "0 Files Changed". Is this comparing the right branch?

**Comment by mtwzim** [comment]
> Hey @mtwzim. I'm seeing "0 Files Changed". Is this comparing the right branch?

Yes, you are right I think there was a problem with my second change.

**Comment by csabaxyz** [comment]
@AlexMesser Is this really fixed? It says zero files changed and:
```
AlexMesser merged 0 commits into typeorm:master
```
Something seems to be wrong here.

**Comment by mtwzim** [comment]
It seems that the bot is doing something wrong, as soon as I commit the 5 commits appeared. Do you have any idea what I can do to make this not happen?

**Comment by AlexMesser** [comment]
Something weird happened. I have not merged this PR.

**Comment by mtwzim** [comment]
So, what can we do? do I create a new pull request?

**Comment by mtwzim** [comment]
@AlexMesser you can unmerge this?

**Pull request merged**
